 <?php 
 	$this->headTitle('- 分包管理 - 承包商信息');
 	$this->headScript()->prependFile('/js/contractjs/p_contractor.js');
 ?>
	<div id="contentWrapper">
	<div id="p_breadcrumb"></div>
	<div id="p_stage_sidebar">	
	<?php 
		echo $this->placeholder('sidebar');
	?>
		<div id="p_content">
		<h1>分工管理 - 承包商信息 - 新建</h1>
		<div class="p_msg">
			<h3></h3>
			<?php echo $this->errorMsg;?>
		</div>
			<div class="overall_tool">
				<div class="button_group">
					<div><a class="lightbox" href="/employee/index/ajaxadd"><img src="/images/icons/functions/new.png"/><p>快速新建通讯录</p></a></div>	
					<div><a id="reset"><img src="/images/icons/functions/refresh.png"/><p>清空</p></a></div>	
					<div><a href="/contract/contractor"><img src="/images/icons/functions/back.png"/><p>返回</p></a></div>	
				</div><!-- end of button group -->
			</div><!-- end of overall tool -->
			<div class="overall_content">
					<?php
						$this->addForm->setAction($this->url());
						echo $this->addForm;
					?>
			</div><!-- end of overall content -->
		</div><!-- end of p_content -->
	</div><!-- end of page stage -->
	</div><!-- end of contentWrapper -->
