<div id="ajaxMsgBox">
	<div id="ajaxMsgBox_Emp">
	<div class="overall_tool">
			<div class="button_group">
				<div><a href="#"><img src="/images/icons/functions/print.png"/><p>打印</p></a></div>	
				<div><a href="#"><img src="/images/icons/functions/export.png"/><p>导出</p></a></div>	
			</div><!-- end of button group -->
	</div><!-- end of overall tool -->
		<p><?php
			$contractor = $this->contractor;?>
			 </p>
			 <div class="overall_content">
			 <table>
					<colgroup>
						<col style="width:30%"></col>
						<col style="width:70%"></col>
					</colgroup>
					<tr>
						<td>承包商名称: </td>
						<td><?php echo $contractor->getName()?></td>
					</tr>
					<tr>
						<td>安全许可证: </td>
						<td><?php echo $contractor->getLicenseNo() ?></td>
					</tr>
					<tr>
						<td>业务范围: </td>
						<td><?php echo $contractor->getBusiField()?></td>
					</tr>
					<tr>
						<td>联系人: </td>
						<td><?php echo $contractor->getContact()?></td>
					</tr>
					<tr>
						<td>联系电话: </td>
						<td><?php echo $contractor->getPhoneNo()?></td>
					</tr>
					<tr>
						<td>其他联系方式: </td>
						<td><?php echo $contractor->getOtherContact()?></td>
					</tr>
					<tr>
						<td>地址: </td>
						<td><?php echo $contractor->getAddress()?></td>
					</tr>
					<tr>
						<td>备注: </td>
						<td><?php echo $contractor->getRemark()?></td>
					</tr>
					<tr>
						<td>创建时间: </td>
						<td><?php echo $contractor->getCTime()?></td>
					</tr>
				</table>
			</div>
		</div>
	</div>
	</div>
</div>