 <?php 
 	$this->headTitle('- 分包管理 - 承包商信息');
 	$this->headScript()->prependFile('/js/contractjs/contractor.js');
 ?>
	<div id="contentWrapper">
	<div id="p_breadcrumb"></div>
	<div id="p_stage_sidebar">	
	<?php 
		echo $this->placeholder('sidebar');
	?>
		<div id="p_content">
		<h1>分包管理 - 承包商信息 - 详情</h1>
		<div class="p_msg">
			<h3></h3>
			<p class="errorMsg"><?php
				if($this->errorMsg != null)
				{
					echo $this->errorMsg;
			 		}?>
			 		</p>
			</div>
			<div class="overall_tool">
				<div class="button_group">	
					<div><a href="#"><img src="/images/icons/functions/export.png"/><p>导出</p></a></div>	
					<div><a href="#"><img src="/images/icons/functions/print.png"/><p>打印</p></a></div>	
					<div><a href="/worker"><img src="/images/icons/functions/back.png"/><p>返回</p></a></div>
				</div><!-- end of button group -->
			</div><!-- end of overall tool -->
			<div class="overall_content">
				<p class="subMenu">承包商信息</p>
				<?php $contract = $this->contract ?>
				<table>
					<colgroup>
						<col style="width:30%"></col>
						<col style="width:70%"></col>					
					</colgroup>
				 	<tr>
						<td>承包商名称：</td>
						<td><?php echo $contract->getName()?></td>
					</tr>
					<tr>
						<td>法定负责人：</td>
						<td><?php echo $contract->getArtiPerson() ?></td>
					</tr>
					<tr>
						<td>许可证号： </td>
						<td><?php echo $contract->getLicenseNo()?></td>
					</tr>
					<tr>
						<td>联系电话：</td>
						<td><?php echo $contract->getPhoneNo()?></td>
					</tr>
					<tr>
						<td>其他联系方式：</td>
						<td><?php echo $contract->getOtherContact()?></td>
					</tr>
					<tr>
						<td>地址: </td>
						<td><?php echo $contract->getAddress()?></td>
					</tr> 
			</table>
		</div>
	</div>
</div>
	</div>
</div>