 <?php 
 	$this->headTitle('-分包信息管理');
 	$this->headScript()->prependFile('/js/contractjs/p_contractor.js');
 ?>
 	<div id="p_id" class="hide">nav_generalInfo</div>
	<div id="s_id" class="hide">none</div>
	<div id="contentWrapper">
	<div id="p_breadcrumb"></div>
	<div id="p_stage_sidebar">	
	<?php 
		echo $this->placeholder('sidebar');
	?>
		<div id="p_content">
		<h1>分包信息管理 - 承包商信息 - 总览</h1>
		<div class="p_msg">
			<h3>本页显示内容为承包商信息总览</h3>
		</div>
			<div class="overall_tool">
				<div class="button_group">
					<div><input class="tbMedium tbtext" type="text" /></div>
					<div><a href="#"><img src="/images/icons/functions/search.png"/><p>查询</p></a></div>	
					<div><a href="<?php echo $this->url(array('controller'=>'index','action'=>'add'))?>"><img src="/images/icons/functions/new.png"/><p>新建</p></a></div>
					<div><a href="#msgBox" class="lightbox" id="btDel"><img src="/images/icons/functions/delete.png"/><p>删除</p></a></div>
					<div><a href="<?php echo $this->url(); ?>"><img src="/images/icons/functions/refresh.png"/><p>显示全部</p></a></div>
					<div><a href="#"><img src="/images/icons/functions/print.png"/><p>打印</p></a></div>	
					<div><a href="#"><img src="/images/icons/functions/help.png"/><p>帮助</p></a></div>	
				</div><!-- end of button group -->
			</div><!-- end of overall tool -->
			<div class="overall_content">
				<table>
					<colgroup>
						<col style="width:3%"></col>
						<col style="width:2%"></col>
						<col style="width:5%"></col>
						<col style="width:10%"></col>
						<col style="width:15%"></col>
						<col style="width:15%"></col>
						<col style="width:25%"></col>
						<col style="width:15%"></col>
						<col style="width:5%"></col>
						<col style="width:5%"></col>
					</colgroup>
					<thead>
						<th>#</th>
						<th></th>
						<th>承包商</th>
						<th>法定负责人</th>
						<th>许可证号</th>
						<th>联系电话</th>
						<th>其他联系方式</th>
						<th>地址</th>
						<th></th>
						<th></th>
					</thead>
					<tr>
						<td><input type="checkbox" id="cb_sa"></td>
						<td colspan="2">全选/取消</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>	
					<?php $counter = 1;?>	
					<?php foreach($this->arrayContractors as $contractor):?>
					<?php $contractorId = $this->escape($contractor->getContractorId()); ?>
					<tr>
						<td><input type="checkbox" name="cb" value="<?php echo $contractorId; ?>"></td>
						<td><?php 
							echo $counter;
							$counter++;
						?></td>
						<td><a href="<?php echo $this->url(array('controller'=>'index','action'=>'ajaxdisplay','id'=>$contractorId))?>" class="lightbox"><?php echo $this->escape($contractor->getName()) ?></td>
						<td><?php echo $this->escape($contractor->getArtiPerson()) ?></td>
						<td><?php echo $this->escape($contractor->getLicenseNo()) ?></td>
						<td><?php echo $this->escape($contractor->getPhoneNo()) ?></td>
						<td><?php echo $this->escape($contractor->getOtherContact()) ?></td>	
						<td><?php echo $this->escape($contractor->getAddress())?></td>
						<td><a href="<?php echo $this->url(array('controller'=>'index','action'=>'ajaxdisplay','id'=>$contractorId))?>" class="lightbox">详情</a></td>	
						<td><a href="<?php echo $this->url(array('controller'=>'index','action'=>'edit','id'=>$contractorId))?>">修改</a></td>
					</tr>
					<?php endforeach ?>
				</table>
				<div id="msgBox"></div>
			</div><!-- end of overall content -->
		</div><!-- end of p_content -->
	</div><!-- end of page stage -->
	</div><!-- end of contentWrapper -->
