 <?php 
 	$this->headTitle('- 承包商管理 - 承包商信息');
 ?>
	<div id="contentWrapper">
	<div id="p_breadcrumb"></div>
	<div id="p_stage_sidebar">	
	<?php 
		echo $this->placeholder('sidebar');
	?>
		<div id="p_content">
		<h1>承包商管理 - 承包商信息 - 总览</h1>
		<div class="p_msg">
			<h3></h3>
			<p class="errorMsg"><?php
				if($this->errorMsg != null)
				{
					echo $this->errorMsg;
			 		}?>
			 		</p>
			<?php if (count($this->messages)) : ?>
				<ul id="messages">
				<?php foreach ($this->messages as $message) : ?>
					<li><p class="errorMsg"><?php echo $this->escape($message); ?></p></li>
			<?php endforeach; ?>
				</ul>
			<?php endif; ?>
		</div>
			<div class="overall_tool">
				<div class="button_group">
				<div id="searchBox">
					<form method="post" action="<?php echo $this->url()?>">
							<div>
								<select name="condition" class="tbMediumer stStyle">
  									<option value="name">承包商</option>
									<option value="contact">联系人</option>
								</select>
							</div>
							<div><input class="tbMedium tbText" name="key" type="text" /></div>
							<div><input class= "btSearch" type="submit" value=""></input></div>	
						</form>
				</div>	
					<div><a href="<?php echo $this->url(array('controller'=>'index','action'=>'add'))?>"><img src="/images/icons/functions/new.png"/><p>新建</p></a></div>
					<div><a href="#msgBox" class="lightbox" id="btDel"><img src="/images/icons/functions/delete.png"/><p>删除</p></a></div>
					<div><a href="<?php echo $this->url(); ?>"><img src="/images/icons/functions/refresh.png"/><p>显示全部</p></a></div>
					<div><a href="#"><img src="/images/icons/functions/export.png"/><p>导出</p></a></div>	
					<div><a href="#"><img src="/images/icons/functions/print.png"/><p>打印</p></a></div>	
				</div><!-- end of button group -->
			</div><!-- end of overall tool -->
			<div class="overall_content">
				<table>
					<colgroup>
						<col style="width:3%"></col>
						<col style="width:2%"></col>
						<col style="width:10%"></col>
						<col style="width:10%"></col>
						<col style="width:17%"></col>
						<col style="width:13%"></col>
						<col style="width:20%"></col>
						<col style="width:15%"></col>
						<col style="width:5%"></col>
						<col style="width:5%"></col>
					</colgroup>
					<thead>
						<th>#</th>
						<th></th>
						<th>承包商</th>
						<th>联系人</th>
						<th>安全生产许可证</th>
						<th>联系电话</th>
						<th>其他联系方式</th>
						<th>地址</th>
						<th></th>
						<th></th>
					</thead>
					<tr>
						<td><input type="checkbox" id="cb_sa"></td>
						<td colspan="2">全选/取消</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>	
					<?php $counter = 1;?>	
					<?php foreach($this->arrayContractors as $contractor):?>
					<?php $contractorId = $this->escape($contractor->contractorId); ?>
					<tr>
						<td><input type="checkbox" name="cb" value="<?php echo $contractorId; ?>"></td>
						<td><?php 
							echo $counter;
							$counter++;
						?></td>
						<td><a href="<?php echo $this->url(array('controller'=>'index','action'=>'display','id'=>$contractorId))?>"><?php echo $this->escape($contractor->name) ?></td>
						<td><?php echo $this->escape($contractor->contact) ?></td>
						<td><?php echo $this->escape($contractor->licenseNo) ?></td>
						<td><?php echo $this->escape($contractor->phoneNo) ?></td>
						<td><?php echo $this->escape($contractor->otherContact) ?></td>	
						<td><?php echo $this->escape($contractor->address)?></td>
						<td><a href="<?php echo $this->url(array('controller'=>'index','action'=>'edit','id'=>$contractorId))?>">修改</a></td>
						<td><a href="<?php echo $this->url(array('controller'=>'index','action'=>'display','id'=>$contractorId))?>">详情</a></td>	
					</tr>
					<?php endforeach ?>
					<?php if(count($this->arrayContractors) != 0)
						echo "<tr><td colspan='10'>".$this->paginationControl($this->arrayContractors, 'Sliding', 'tmp/control.phtml')."</td></tr>";?>
				</table>
				<div id="msgBox"></div>
			</div><!-- end of overall content -->
		</div><!-- end of p_content -->
	</div><!-- end of page stage -->
	</div><!-- end of contentWrapper -->
