<?php $cpp = $this->cpp;
		$arrayFuncs = $this->arrayFuncs;
?>
<div id="ajaxMsgBox">
	<div id="ajaxMsgBox_Emp">
	<div class="overall_tool">
			<div class="button_group">
				<?php if($arrayFuncs['ajaxpdf'] == 1):?>
				<div><a target="_blank" href="/general/pdf/generate/page/7/id/<?php echo $cpp->cppId?>"><img src="/images/icons/functions/export.png"/><p>导出</p></a></div>
				<?php endif;?>
			</div><!-- end of button group -->
	</div><!-- end of overall tool -->
			<div class="overall_content">
			<table>
					<colgroup>
						<col style="width:30%"></col>
						<col style="width:70%"></col>
					</colgroup>
					<tr>
						<td>员工姓名：</td>
						<td><?php echo $cpp->getContactName()?></td>
					</tr>
					<tr>
						<td>岗位名称：</td>
						<td><?php echo $cpp->getPostName()?></td>
					</tr>
					<tr>
						<td>执业资格：</td>
						<td><?php echo $cpp->getQualif() ?></td>
					</tr>
					<tr>
						<td>证书编号：</td>
						<td><?php echo $cpp->getCertId() ?></td>
					</tr>
					<tr>
						<td>开始承担责任时间：</td>
						<td><?php echo $cpp->getStartDate() ?></td>
					</tr>
					<tr>
						<td>岗位职责：</td>
						<td><?php echo $cpp->getResponsi() ?></td>
					</tr>
					<tr>
						<td>具体职责：</td>
						<td><?php echo $cpp->getPostDetail() ?></td>
					</tr>
					<tr>
						<td>备注：</td>
						<td><?php echo $cpp->getRemark() ?></td>
					</tr>
					<tr>
						<td>上次修改时间：</td>
						<td><?php echo $cpp->getCTime() ?></td>
					</tr>
			</table>
		</div>
	</div>
	</div>
	</div>
</div>