<?php 
	$this->headTitle('- 工程管理 - 工程岗位信息');
	$this->headScript()->prependFile('/js/pment.js');
?>
	<div id="contentWrapper">
	<div id="p_breadcrumb"></div>
	<div id="p_stage_sidebar">	
	<?php 
		echo $this->placeholder('sidebar');
	?>
		<div id="p_content">
		<h1>工程管理 - 工程岗位信息 - 总览</h1>
		<?php 
			$project = $this->project;
			echo $this->displayProject($project);?>
		<div class="p_msg">
			<h3></h3>
			<p class="errorMsg"><?php
				if($this->errorMsg != null)
				{
					echo $this->errorMsg;
					}?>
					</p>
			<?php if (count($this->messages)) : ?>
				<ul id="messages">
				<?php foreach ($this->messages as $message) : ?>
					<li><p class="errorMsg"><?php echo $this->escape($message); ?></p></li>
			<?php endforeach; ?>
				</ul>
			<?php endif; ?>
			</div>
			<div class="overall_tool">
				<div class="button_group">
				<div id="searchBox">
					<form method="post" action="<?php echo $this->url()?>">
							<div>
								<select name="condition" class="tbMediumer stStyle">
  									<option value="name">姓名</option>
  									<option value="postName">岗位名称</option>
								</select>
							</div>
							<div><input class="tbMedium tbText" name="key" type="text" /></div>
							<div><input class= "btSearch" type="submit" value=""></input></div>	
						</form>
					</div>	
					<div><a href="<?php echo $this->url(array('controller'=>'cpp','action'=>'add'))?>"><img src="/images/icons/functions/new.png"/><p>新建</p></a></div>
					<div><a href="#msgBox" class="lightbox" id="btDel"><img src="/images/icons/functions/delete.png"/><p>删除</p></a></div>
					<div><a href="<?php echo $this->url(); ?>"><img src="/images/icons/functions/refresh.png"/><p>显示全部</p></a></div>
					<div><a href="#"><img src="/images/icons/functions/export.png"/><p>导出</p></a></div>	
					<div><a href="#"><img src="/images/icons/functions/print.png"/><p>打印</p></a></div>	
				</div><!-- end of button group -->
			</div><!-- end of overall tool -->
			<div class="overall_content">
				<table>
					<colgroup>
						<col style="width:5%"></col>
						<col style="width:5%"></col>
						<col style="width:10%"></col>
						<col style="width:17%"></col>
						<col style="width:19%"></col>
						<col style="width:18%"></col>
						<col style="width:13%"></col>
						<col style="width:5%"></col>
						<col style="width:8%"></col>
					</colgroup>
					<thead>
						<th>#</th>
						<th><input id="modelName" type="text" class="hide" value="<?php echo $this->modelName ?>"></th>
						<th>姓名</th>
						<th>岗位名称</th>
						<th>执业资格</th>
						<th>证书编号</th>
						<th>开始承担责任时间</th>
						<th><input id="module" type="text" class="hide" value="<?php echo $this->module ?>"></th>
						<th><input id="controller" type="text" class="hide" value="<?php echo $this->controller ?>"></th>
					</thead>
					<tr>
						<td><input type="checkbox" id="cb_sa"></td>
						<td colspan="2">全选/取消</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>	
					<?php $counter = 1;?>
					<?php foreach($this->arrayCpps as $cpp):?>
					<tr>
						<td><input type="checkbox" name="cb" value="<?php echo $this->escape($cpp->getCppId()); ?>"></td>
						<td><?php 
							echo $counter;
							$counter++;
						?></td>
						<td><a class="lightbox" href="/employee/index/ajaxdisplay/id/<?php echo $this->escape($cpp->getContactId()) ?>"><?php echo $this->escape($cpp->getContactName())?></a></td>
						<td><?php echo $this->escape($cpp->getPostName()) ?></td>
						<td><?php echo $this->escape($cpp->getQualif()) ?></td>
						<td><?php echo $this->escape($cpp->getCertId()) ?></td>
						<td><?php echo $this->escape($cpp->getStartDate()) ?></td>
						<td><a href="<?php echo $this->url(array('controller'=>'cpp','action'=>'edit','id'=>$this->escape($cpp->getCppId())))?>">修改</a></td>
						<td><a href="<?php echo $this->url(array('controller'=>'cpp','action'=>'ajaxdisplay','id'=>$this->escape($cpp->getCppId())))?>" class="lightbox">快速查看</a></td>
					</tr>
					<?php endforeach ?>
				</table>
				<div id="msgBox"></div>
			</div><!-- end of overall content -->
		</div><!-- end of p_content -->
	</div><!-- end of page stage -->
	</div><!-- end of contentWrapper -->
