 <?php 
 	$this->headTitle('- 车辆管理 - 车辆使用记录');
 	$this->headScript()->prependFile('/js/form.js');
 ?>
	<div id="contentWrapper">
	<div id="p_breadcrumb"></div>
	<div id="p_stage_sidebar">	
	<?php 
		echo $this->placeholder('sidebar');
	?>
		<div id="p_content">
		<h1>车辆管理 - 车辆使用记录 - 编辑</h1>
		<div class="p_msg">
			<h3></h3>
			<p class="errorMsg"><?php
				if($this->errorMsg != null)
				{
					echo $this->errorMsg;
			 	}?>
			</p>
		</div>
			<div class="overall_tool">
				<div class="button_group">
					<div><a href="/vehicle/verecord/edit/id/<?php echo $this->id?>"><img src="/images/icons/functions/refresh.png"/><p>刷新</p></a></div>
					<div><a href=<?php echo $this->blink ?>><img src="/images/icons/functions/back.png"/><p>返回</p></a></div>	
				</div><!-- end of button group -->
			</div><!-- end of overall tool -->
			<div class="overall_content">
					<?php
						$this->editForm->setAction($this->url());
						echo $this->editForm;
					?>
			</div><!-- end of overall content -->
		</div><!-- end of p_content -->
	</div><!-- end of page stage -->
	</div><!-- end of contentWrapper -->
