 <?php 
 	$this->headTitle('-车辆管理');
 	$this->headScript()->prependFile('/js/vehicle/p_verecord.js');
 ?>
 	<div id="p_id" class="hide">nav_generalInfo</div>
	<div id="s_id" class="hide">none</div>
	<div id="contentWrapper">
	<div id="p_breadcrumb"></div>
	<div id="p_stage_sidebar">	
	<?php 
		echo $this->placeholder('sidebar');
	?>
		<div id="p_content">
		<h1>车辆管理 - 车辆使用记录 - 总览</h1>
		<div class="p_msg">
			<h3>本页显示内容为车辆使用记录总览</h3>
		</div>
			<div class="overall_tool">
				<div class="button_group">
					<div><input class="tbMedium tbtext" type="text" /></div>
					<div><a href="#"><img src="/images/icons/functions/search.png"/><p>查询</p></a></div>	
					<div><a href="<?php echo $this->url(array('controller'=>'verecord','action'=>'add'))?>"><img src="/images/icons/functions/new.png"/><p>新建</p></a></div>
					<div><a href="#msgBox" class="lightbox" id="btDel"><img src="/images/icons/functions/delete.png"/><p>删除</p></a></div>
					<div><a href="<?php echo $this->url(); ?>"><img src="/images/icons/functions/refresh.png"/><p>显示全部</p></a></div>
					<div><a href="#"><img src="/images/icons/functions/print.png"/><p>打印</p></a></div>	
					<div><a href="#"><img src="/images/icons/functions/help.png"/><p>帮助</p></a></div>	
				</div><!-- end of button group -->
			</div><!-- end of overall tool -->
			<div class="overall_content">
				<table>
					<colgroup>
						<col style="width:3%"></col>
						<col style="width:2%"></col>
						<col style="width:15%"></col>
						<col style="width:5%"></col>
						<col style="width:10%"></col>
						<col style="width:15%"></col>
						<col style="width:20%"></col>
						<col style="width:20%"></col>
						<col style="width:5%"></col>
						<col style="width:5%"></col>						
					</colgroup>
					<thead>
						<th>#</th>
						<th></th>
						<th>车牌号</th>
						<th>开始使用日期</th>
						<th>结束使用日期</th>
						<th>本次使用公里数</th>
						<th>驾驶员</th>
						<th>其他使用人</th>
						<th></th>
						<th></th>
					</thead>
					<tr>
						<td><input type="checkbox" id="cb_sa"></td>
						<td colspan="2">全选/取消</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>	
					<?php $counter = 1;?>
					<?php foreach($this->arrayVerecords as $verecord):?>
					<?php $verecordId = $this->escape($verecord->getVerecordId());?>
					<tr>
						<td><input type="checkbox" name="cb" value="<?php echo $verecordId ?>"></td>
						<td><?php 
							echo $counter;
							$counter++;
						?></td>
						<td><a class="lightbox" href="<?php echo $this->url(array('controller'=>'index','action'=>'ajaxdisplay','id'=>$verecord->getVeId()))?>"><?php echo $this->escape($verecord->getPlateNo()) ?></a></td>
						<td><?php echo $this->escape($verecord->getStartDate()) ?></td>	
						<td><?php echo $this->escape($verecord->getEndDate()) ?></td>
						<td>
						<?php echo $this->escape($verecord->getMile())?>
						</td>
						<td>
							<?php echo $this->escape($verecord->getPilot()) ?></td>
						<td><?php echo $this->escape($verecord->getOtherUser())?></td>
						<td><a href="<?php echo $this->url(array('controller'=>'verecord','action'=>'edit','id'=>$verecordId))?>">修改</a></td>
						<td><a class="lightbox" href="<?php echo $this->url(array('controller'=>'verecord','action'=>'ajaxdisplay','id'=>$verecordId))?>">详情</a></td>
					</tr>
					<?php endforeach ?>
				</table>
				<div id="msgBox"></div>
			</div><!-- end of overall content -->
		</div><!-- end of p_content -->
	</div><!-- end of page stage -->
	</div><!-- end of contentWrapper -->
