 <?php 
	$this->headTitle('- 工程文件管理');
	$this->headScript()->prependFile('/js/form.js');
	$this->headScript()->prependFile('/js/conContractor.js'); ?>
	<div id="contentWrapper">
	<div id="p_breadcrumb"></div>
	<div id="p_stage_sidebar">	
	<?php 
			$specId = $this->specId;
			$arraySpecs = $this->arraySpecs;
			echo $this->displayFileSpec($arraySpecs,$specId);?>
		<div id="p_content">
		<?php $spec = $this->spec?>
		<h1>工程文件管理 - <?php echo $spec->getName()?> - 总览</h1>
		<div class="p_msg">
			<h3></h3>
			<p class="errorMsg"><?php
				if($this->errorMsg != null)
				{
					echo $this->errorMsg;
			 	}?>
			</p><?php if (count($this->messages)) : ?>
				<ul id="messages">
				<?php foreach ($this->messages as $message) : ?>
					<li><p class="errorMsg"><?php echo $this->escape($message); ?></p></li>
			<?php endforeach; ?>
				</ul>
			<?php endif; ?>
			</div>
			<div class="overall_tool">
				<div class="button_group">
					<div><a id = "reset"><img src="/images/icons/functions/refresh.png"/><p>清空</p></a></div>		
					<div><a href="/file/index/index/id/<?php echo $specId ?>"><img src="/images/icons/functions/back.png"/><p>返回</p></a></div>	
				</div><!-- end of button group -->
			</div><!-- end of overall tool -->
			<div class="overall_content">
				<div class="formNtable">
					<?php
						$this->fileForm->setAction($this->url());
						echo $this->fileForm;
					?>
				</div>
			</div><!-- end of overall content -->
		</div><!-- end of p_content -->
	</div><!-- end of page stage -->
	</div><!-- end of contentWrapper -->
