<?php
	$this->headTitle('- 工程文件管理');
	$this->headScript()->prependFile('/js/file.js');
	$this->headScript()->prependFile('/js/conContractor.js'); ?>
	<div id="contentWrapper">
	<div id="p_breadcrumb"></div>
	<div id="p_stage_sidebar">
	<?php 
			$specId = $this->specId;
			$arraySpecs = $this->arraySpecs;
			echo $this->displayFileSpec($arraySpecs,$specId);?>
		<div id="p_content">
		<?php $spec = $this->spec?>
		<h1>工程文件管理 - <?php echo $spec->getName()?> - 总览</h1>
		<div class="p_msg">
			<h3></h3>
			<p class="errorMsg"><?php
				if($this->errorMsg != null)
				{
					echo $this->errorMsg;
			 		}?>
			 		</p>
			<?php if (count($this->messages)) : ?>
				<ul id="messages">
				<?php foreach ($this->messages as $message) : ?>
					<li><p class="errorMsg"><?php echo $this->escape($message); ?></p></li>
			<?php endforeach; ?>
				</ul>
			<?php endif; ?>
			</div>
			<div class="overall_tool">
				<div class="button_group">
					<div id="searchBox">
						<form method="post" action="<?php echo $this->url()?>">
							<div>
								<select name="condition" class="tbMediumer stStyle">
									<option value="fileId">文件编号</option>
									<option value="display">文件名</option>
									<option value="edition">文号</option>
								</select>
							</div>
							<div><input class="tbMedium tbText tbSearch" name="key" type="text" /></div>
							<div><input class= "btSearch" type="submit" value=""></input></div>
						</form>
					</div>
					<div><a href="<?php echo $this->url(array('controller'=>'index','action'=>'add','id'=>$specId))?>"><img src="/images/icons/functions/new.png"/><p>新建</p></a></div>
					<div><a href="#msgBox" class="lightbox" id="btDel"><img src="/images/icons/functions/delete.png"/><p>删除</p></a></div>
					<div><a href="<?php echo $this->url(); ?>"><img src="/images/icons/functions/refresh.png"/><p>显示全部</p></a></div>
					<div><a href="#"><img src="/images/icons/functions/export.png"/><p>导出</p></a></div>
					<div><a href="#"><img src="/images/icons/functions/print.png"/><p>打印</p></a></div>
				</div><!-- end of button group -->
			</div><!-- end of overall tool -->
			<div class="overall_content">
			<p class="subMenu slideMenu"><a class="btRdSlide subMenu_switch_open">文件列表</a></p>
			<div class="conRdSlide">
				<table>
					<colgroup>
						<col style="width:5%"></col>
						<col style="width:6%"></col>
						<col style="width:25%"></col>
						<col style="width:13%"></col>
						<col style="width:16%"></col>
						<col style="width:7%"></col>
						<col style="width:7%"></col>
						<col style="width:7%"></col>
						<col style="width:5%"></col>
						<col style="width:5%"></col>
						<col style="width:5%"></col>
					</colgroup>
					<thead>
						<th><input id="modelName" type="text" class="hide" value="<?php echo $this->modelName ?>"></th>
						<th>文件编号</th>
						<th>文件名</th>
						<th>文号</th>
						<th>上级目录</th>
						<th>内部文件</th>
						<th>文件类型</th>
						<th>录入人</th>
						<th>复核状态</th>
						<th><input id="module" type="text" class="hide" value="<?php echo $this->module ?>"></th>
						<th><input id="controller" type="text" class="hide" value="<?php echo $this->controller ?>"></th>
					</thead>
					<tr>
						<td><input type="checkbox" id="cb_sa"></td>
						<td colspan="2">全选/取消</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<?php foreach($this->arrayFiles as $file):?>
					<?php $fileId = $this->escape($file->file_id);?>
					<tr>
						<td><input type="checkbox" name="cb" value="<?php echo $fileId ?>"></td>
						<td><?php
							echo $fileId;
						?></td>
						<td><a class="lightbox" href="<?php echo $this->url(array('controller'=>'index','action'=>'ajaxdisplay','id'=>$fileId))?>"><?php echo $this->escape($file->file_display)?></a></td>
						<td><?php echo $file->file_edition?></td>
						<td><?php echo $file->file_parent?></td>
						<td><?php echo $file->file_inFlag?></td>
						<td><?php echo $file->file_type?></td>
						<td><a class="lightbox" href="/employee/index/ajaxdisplay/id/<?php echo $this->escape($file->contactId) ?>"><?php echo $this->escape($file->contactName)?></a></td>
						<td><?php echo $file->file_status?></td>
						<td><p class="fPreview"><span class="hide hide_a"><?php echo $file->file_name?></span><span class="hide hide_b"><?php echo $file->file_type?></span>预览</p></td>
						<td><a href="http://localhost:8888/<?php echo $file->file_name ?>" class="fDownload">下载</a></td>
					<?php endforeach ?>
					<tr>
						<td colspan="11"><?= $this->paginationControl($this->arrayFiles, 'Sliding', 'tmp/control.phtml'); ?></td>
					</tr>
				</table>
				</div>
				<p class="subMenu slideMenu"><a class="btRdSlide2 subMenu_switch_close">文件预览</a></p>
				<div class="conRdSlide2 hide">
				</div>
				<div id="ajax_id" class="hide"><?php echo $this->specId ?></div>
				<div id="msgBox"></div>
			</div><!-- end of overall content -->
		</div><!-- end of p_content -->
	</div><!-- end of page stage -->
	</div><!-- end of contentWrapper -->
