<div id="ajaxMsgBox">
	<div id="ajaxMsgBox_Emp">
	<div class="overall_tool">
			<div class="button_group">
			<?php 	$arrayFuncs = $this->arrayFuncs;?>
				<?php if($arrayFuncs['ajaxpdf'] == 1):?>
				<div><a href="#"><img src="/images/icons/functions/export.png"/><p>导出</p></a></div>
				<?php endif;?>
			</div><!-- end of button group -->
	</div><!-- end of overall tool -->
		<p><?php
			$subcontract = $this->subcontract;?>
			 </p>
			 <div class="overall_content">
			 <table>
					<colgroup>
						<col style="width:30%"></col>
						<col style="width:70%"></col>
					</colgroup>
					<tr>
						<td>分包类型：</td>
						<td><?php echo $subcontract->getScontrType()?></td>
					</tr>
					<tr>
						<td>承包商名称：</td>
						<td><?php echo $subcontract->getContractorName()?></td>
					</tr>
					<tr>
						<td>分包项目：</td>
						<td><?php echo $subcontract->getContent()?></td>
					</tr>
					<tr>
						<td>具体描述：</td>
						<td><?php echo $subcontract->getDetail()?></td>
					</tr>
					<tr>
						<td>质量等级：</td>
						<td><?php echo $subcontract->getQuality()?></td>
					</tr>
					<tr>
						<td>预计开始时间：</td>
						<td><?php echo $subcontract->getStartDateExp()?></td>
					</tr>
					<tr>
						<td>预计结束时间：</td>
						<td><?php echo $subcontract->getEndDateExp()?></td>
					</tr>
					<tr>
						<td>预计工期：</td>
						<td><?php echo $subcontract->getPeriodExp()?></td>
					</tr>
					<tr>
						<td>实际开始时间：</td>
						<td><?php echo $subcontract->getStartDateAct()?></td>
					</tr>
					<tr>
						<td>实际结束时间：</td>
						<td><?php echo $subcontract->getEndDateAct()?></td>
					</tr>
					<tr>
						<td>实际工期：</td>
						<td><?php echo $subcontract->getPeriodAct()?></td>
					</tr>
					<tr>
						<td>承包方违约情况：</td>
						<td><?php echo $subcontract->getBrConContr()?></td>
					</tr>
					<tr>
						<td>承包方违约责任：</td>
						<td><?php echo $subcontract->getBrResContr()?></td>
					</tr>
					<tr>
						<td>分包方违约情况：</td>
						<td><?php echo $subcontract->getBrConSContr()?></td>
					</tr>
					<tr>
						<td>分包方违约责任：</td>
						<td><?php echo $subcontract->getBrResScontr()?></td>
					</tr>
					<tr>
						<td>合同金额：</td>
						<td><?php echo $subcontract->getContrAmt()?></td>
					</tr>
					<tr>
						<td>履约保函：</td>
						<td><?php echo $subcontract->getGuarantee()?></td>
					</tr>
					<tr>
						<td>工程保证金：</td>
						<td><?php echo $subcontract->getPrjMargin()?></td>
					</tr>
					<tr>
						<td>工程保修金：</td>
						<td><?php echo $subcontract->getPrjWarr()?></td>
					</tr>
					<tr>
						<td>备注：</td>
						<td><?php echo $subcontract->getRemark()?></td>
					</tr>
					<tr>
						<td>上次修改时间：</td>
						<td><?php echo $subcontract->getCTime()?></td>
					</tr>
				</table>
			</div>
		</div>
	</div>
	</div>
</div>