 <?php 
 	$this->headTitle('- 工人管理 - 工人信息');
 	$this->headScript()->prependFile('/js/workerjs/p_worker.js');
 ?>
	<div id="contentWrapper">
	<div id="p_breadcrumb"></div>
	<div id="p_stage_sidebar">	
	<?php 
		echo $this->placeholder('sidebar');
	?>
		<div id="p_content">
		<h1>工人管理 - 工人信息 - 详情</h1>
		<div class="p_msg">
			<h3></h3>
			<p class="errorMsg"><?php
				if($this->errorMsg != null)
				{
					echo $this->errorMsg;
			 		}?>
			 		</p>
			</div>
			<div class="overall_tool">
				<div class="button_group">	
					<div><a href="#"><img src="/images/icons/functions/export.png"/><p>导出</p></a></div>	
					<div><a href="#"><img src="/images/icons/functions/print.png"/><p>打印</p></a></div>	
					<div><a href="/worker/worker"><img src="/images/icons/functions/back.png"/><p>返回</p></a></div>
				</div><!-- end of button group -->
			</div><!-- end of overall tool -->
			<div class="overall_content">
				<p class="subMenu">工人信息</p>
				<table>
					<colgroup>
						<col style="width:30%"></col>
						<col style="width:70%"></col>					
					</colgroup>
					<tr>
					<tr>
						<td>工人姓名: </td>
						<td><?php echo $this->worker->getName()?></td>
					</tr>
					<tr>
						<td>班组名称: </td>
						<td><?php echo $this->worker->getTeamName() ?></a></td>
					</tr>
					<tr>
						<td>联系电话: </td>
						<td><?php echo $this->worker->getPhoneNo() ?></td>
					</tr>
					<tr>
						<td>家庭住址: </td>
						<td><?php echo $this->worker->getAddress()?></td>
					</tr>
					<tr>
						<td>技能: </td>
						<td><?php echo $this->worker->getSkill()?></td>
					</tr>	
					<tr>
						<td>岗位证编号: </td>
						<td><?php echo $this->worker->getCert()?></td>
					</tr>	
					<tr>
						<td>备注: </td>
						<td><?php echo $this->worker->getRemark()?></td>
					</tr>	
					<tr>
						<td>创建时间: </td>
						<td><?php echo $this->worker->getCTime()?></td>
					</tr>	
				</table>
				<p class="subMenu">日工工资记录</p>
				<table>
					<colgroup>
						<col style="width:9%"></col>
						<col style="width:27%"></col>
						<col style="width:27%"></col>
						<col style="width:27%"></col>
						<col style="width:5%"></col>
						<col style="width:5%"></col>						
					</colgroup>
					<thead>
						<th>#</th>
						<th>工资金额</th>
						<th>开始日期</th>
						<th>结束日期</th>
						<th></th>
						<th></th>
					</thead>
					<?php $counter = 1;?>
					<?php foreach($this->arrayWages as $wage):?>
					<?php $wageId = $this->escape($wage->getWagId());?>
					<tr>
						<td><?php 
							echo $counter;
							$counter++;
						?></td>
						<td><?php echo $this->escape($wage->getAmount()) ?></a></td>
						<td><?php echo $this->escape($wage->getStartDate()) ?></td>	
						<td><?php echo $this->escape($wage->getEndDate()) ?></td>
						<td><a href="<?php echo $this->url(array('controller'=>'wage','action'=>'edit','id'=>$wageId))?>">修改</a></td>
						<td><a href="<?php echo $this->url(array('controller'=>'wage','action'=>'ajaxdisplay','id'=>$wageId))?>">详情</a></td>
					</tr>
					<?php endforeach ?>
				</table>
				<p class="subMenu">工人奖励</p>
				<table>
					<colgroup>
						<col style="width:10%"></col>
						<col style="width:20%"></col>
						<col style="width:20%"></col>
						<col style="width:20%"></col>
						<col style="width:20%"></col>						
						<col style="width:5%"></col>
						<col style="width:5%"></col>						
					</colgroup>
					<thead>
						<th>#</th>
						<th>工程名称</th>
						<th>日期</th>
						<th>奖励类型</th>
						<th>金额</th>
						<th></th>
						<th></th>
					</thead>
					<?php $counter = 1;?>
					<?php foreach($this->arrayBonuses as $bon):?>
					<?php $bonId = $this->escape($bon->getBonId());?>
					<tr>
						<td><?php 
							echo $counter;
							$counter++;
						?></td>
						<td><?php echo $this->escape($bon->getProjectName()) ?></a></td>
						<td><?php echo $this->escape($bon->getBonDate()) ?></td>	
						<td><?php echo $this->escape($bon->getTypeName()) ?></td>
						<td><?php echo $this->escape($bon->getAmount()) ?></td>						
						<td><a href="<?php echo $this->url(array('controller'=>'bonuse','action'=>'edit','id'=>$bonId))?>">修改</a></td>
						<td><a href="<?php echo $this->url(array('controller'=>'bonuse','action'=>'ajaxdisplay','id'=>$bonId))?>">详情</a></td>
					</tr>
					<?php endforeach ?>
				</table>
				<p class="subMenu">工人扣款</p>
				<table>
					<colgroup>
						<col style="width:10%"></col>
						<col style="width:20%"></col>
						<col style="width:20%"></col>
						<col style="width:20%"></col>
						<col style="width:20%"></col>						
						<col style="width:5%"></col>
						<col style="width:5%"></col>						
					</colgroup>
					<thead>
						<th>#</th>
						<th>工程名称</th>
						<th>日期</th>
						<th>扣款类型</th>
						<th>金额</th>
						<th></th>
						<th></th>
					</thead>
					<?php $counter = 1;?>
					<?php foreach($this->arrayPenalties as $pen):?>
					<?php $penId = $this->escape($pen->getPenId());?>
					<tr>
						<td><?php 
							echo $counter;
							$counter++;
						?></td>
						<td><?php echo $this->escape($pen->getProjectName()) ?></a></td>
						<td><?php echo $this->escape($pen->getPenDate()) ?></td>	
						<td><?php echo $this->escape($pen->getTypeName()) ?></td>
						<td><?php echo $this->escape($pen->getAmount()) ?></td>						
						<td><a href="<?php echo $this->url(array('controller'=>'penalty','action'=>'edit','id'=>$penId))?>">修改</a></td>
						<td><a href="<?php echo $this->url(array('controller'=>'penalty','action'=>'ajaxdisplay','id'=>$penId))?>">详情</a></td>
					</tr>
					<?php endforeach ?>
				</table>
				<div id="msgBox"></div>
			</div><!-- end of overall content -->
		</div><!-- end of p_content -->
	</div><!-- end of page stage -->
	</div><!-- end of contentWrapper -->
