 <?php 
 	$this->headTitle('- 工人管理 - 工人信息');
 	$this->headScript()->prependFile('/js/workerjs/p_worker.js');
 ?>
	<div id="contentWrapper">
	<div id="p_breadcrumb"></div>
	<div id="p_stage_sidebar">	
	<?php 
		echo $this->placeholder('sidebar');
	?>
		<div id="p_content">
		<h1>工人管理 - 工人信息 - 总览</h1>
		<div class="p_msg">
			<h3></h3>
			<p class="errorMsg"><?php
				if($this->errorMsg != null)
				{
					echo $this->errorMsg;
			 		}?>
			 		</p>
			</div>
			<div class="overall_tool">
				<div class="button_group">
				<div id="searchBox">
					<form method="post" action="<?php echo $this->url()?>">
							<div>
								<select name="condition" class="tbMediumer stStyle">
  									<option value="name">工人姓名</option>
									<option value="phoneNo">联系电话</option>
								</select>
							</div>
							<div><input class="tbMedium tbText" name="key" type="text" /></div>
							<div><input class= "btSearch" type="submit" value=""></input></div>	
						</form>
				</div>		
					<div><a href="<?php echo $this->url(array('controller'=>'worker','action'=>'add'))?>"><img src="/images/icons/functions/new.png"/><p>新建</p></a></div>
					<div><a href="#msgBox" class="lightbox" id="btDel"><img src="/images/icons/functions/delete.png"/><p>删除</p></a></div>
					<div><a href="<?php echo $this->url(); ?>"><img src="/images/icons/functions/refresh.png"/><p>显示全部</p></a></div>
					<div><a href="#"><img src="/images/icons/functions/export.png"/><p>导出</p></a></div>	
					<div><a href="#"><img src="/images/icons/functions/print.png"/><p>打印</p></a></div>	
				</div><!-- end of button group -->
			</div><!-- end of overall tool -->
			<div class="overall_content">
				<table>
					<colgroup>
						<col style="width:5%"></col>
						<col style="width:5%"></col>
						<col style="width:16%"></col>
						<col style="width:16%"></col>
						<col style="width:16%"></col>
						<col style="width:16%"></col>
						<col style="width:16%"></col>
						<col style="width:5%"></col>
						<col style="width:5%"></col>						
					</colgroup>
					<thead>
						<th>#</th>
						<th><input id="modelName" type="text" class="hide" value="<?php echo $this->modelName ?>"></th>
						<th>工人姓名</th>
						<th>班组名称</th>
						<th>联系电话</th>
						<th>家庭住址</th>
						<th>岗位证编号</th>
						<th><input id="module" type="text" class="hide" value="<?php echo $this->module ?>"></th>
						<th><input id="controller" type="text" class="hide" value="<?php echo $this->controller ?>"></th>
					</thead>
					<tr>
						<td><input type="checkbox" id="cb_sa"></td>
						<td colspan="2">全选/取消</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>	
					<?php $counter = 1;?>
					<?php foreach($this->arrayWorkers as $worker):?>
					<?php $workerId = $this->escape($worker->getWorkerId());?>
					<tr>
						<td><input type="checkbox" name="cb" value="<?php echo $workerId ?>"></td>
						<td><?php 
							echo $counter;
							$counter++;
						?></td>
						<td><a href="<?php echo $this->url(array('controller'=>'worker','action'=>'display','id'=>$workerId))?>"><?php echo $this->escape($worker->getName()) ?></a></td>
						<td><?php echo $this->escape($worker->getTeamName()) ?></td>	
						<td><?php echo $this->escape($worker->getPhoneNo()) ?></td>
						<td>
						<?php echo $this->escape($worker->getAddress())?>
						</td>
						<td><?php echo $this->escape($worker->getCert())?></td>
						<td><a href="<?php echo $this->url(array('controller'=>'worker','action'=>'edit','id'=>$workerId))?>">修改</a></td>
						<td><a href="<?php echo $this->url(array('controller'=>'worker','action'=>'display','id'=>$workerId))?>">详情</a></td>
					</tr>
					<?php endforeach ?>
				</table>
				<div id="msgBox"></div>
			</div><!-- end of overall content -->
		</div><!-- end of p_content -->
	</div><!-- end of page stage -->
	</div><!-- end of contentWrapper -->
