<div id="ajaxMsgBox">
	<div id="ajaxMsgBox_Emp">
	<div class="overall_tool">
			<div class="button_group">
				<div><a href="#"><img src="/images/icons/functions/print.png"/><p>打印</p></a></div>	
				<div><a href="#"><img src="/images/icons/functions/export.png"/><p>导出</p></a></div>	
			</div><!-- end of button group -->
	</div><!-- end of overall tool -->
		<p><?php
			$contrqualif = $this->contrqualif;?>
			 </p>
			 <div class="overall_content">
			 <table>
					<colgroup>
						<col style="width:30%"></col>
						<col style="width:70%"></col>
					</colgroup>
					<tr>
						<td>承包商：</td>
						<td><?php echo $contrqualif->getContractorName()?></td>
					</tr>
					<tr>
						<td>资质序列：</td>
						<td><?php echo $contrqualif->getQualifSerie() ?></td>
					</tr>
					<tr>
						<td>资质类别： </td>
						<td><?php echo $contrqualif->getContractorName()?></td>
					</tr>
					<tr>
						<td>资质等级：</td>
						<td><?php echo $contrqualif->getQualifGrade()?></td>
					</tr>
				</table>
			</div>
		</div>
	</div>
	</div>
</div>