<div id="ajaxMsgBox">
	<div id="ajaxMsgBox_Emp">
	<div class="overall_tool">
				<div class="button_group">
					<div><a href="#"><img src="/images/icons/functions/print.png"/><p>打印</p></a></div>	
					<div><a href="#"><img src="/images/icons/functions/export.png"/><p>导出</p></a></div>	
				</div><!-- end of button group -->
	</div><!-- end of overall tool -->
			<p><?php
			$wage = $this->wage;?>
			 </p>
			 <div class="overall_content">
			 <table>
					<colgroup>
						<col style="width:30%"></col>
						<col style="width:70%"></col>						
					</colgroup>
					<tr>
						<td>姓名: </td>
						<td><?php echo $wage->getName()?></td>
					</tr>
					</tr>
					<tr>
						<td>年龄: </td>
						<td><?php echo $wage->getAge() ?></td>
					</tr>
					<tr>
						<td>职称: </td>
						<td><?php echo $wage->getTitleName()?></td>
					</tr>
					<tr>
						<td>身份证: </td>
						<td><?php echo $wage->getIdCard()?></td>
					</tr>	
					<tr>
						<td>联系方式: </td>
						<td><?php echo $wage->getPhoneNo()?></td>
					</tr>
					<tr>
						<td>其他联系方式: </td>
						<td><?php echo $wage->getOtherwage()?></td>
					</tr>	
					<tr>
						<td>现住址: </td>
						<td><?php echo $wage->getAddress()?></td>
					</tr>		
					<tr>
						<td>备注: </td>
						<td><?php echo $wage->getRemark()?></td>
					</tr>	
					<tr>
						<td>创建时间: </td>
						<td><?php echo $wage->getCTime()?></td>
					</tr>		
			</table>
		</div>
	</div>
</div>