 <?php 
 	$this->headTitle('- 工人管理 - 日工工资信息'); //修改处
 	$this->headScript()->prependFile('/js/wagejs/p_wage.js');//修改处
 ?>
 	<!--检查处: 如果出现
 	<div id="p_id" class="hide">nav_generalInfo</div>
	<div id="s_id" class="hide">none</div>
	要删除--> 
	<div id="contentWrapper">
	<div id="p_breadcrumb"></div>
	<div id="p_stage_sidebar">	
	<?php 
		echo $this->placeholder('sidebar');
	?>
		<div id="p_content">
		<h1>工人管理 - 日工工资信息 - 总览</h1><!--修改处-->
		<div class="p_msg">
			<h3></h3>
			<p class="errorMsg">
			<?php
				if($this->errorMsg != null)
					echo $this->errorMsg;?></p>
			</div>
			<div class="overall_tool">
				<div class="button_group">
				<div id="searchBox">
					<form method="post" action="<?php echo $this->url()?>">
							<div>
								<select name="condition" class="tbMediumer stStyle">
  									<option value="workerName">工人姓名</option><!--修改处-->
								</select>
							</div>
							<div><input class="tbMedium tbText" name="key" type="text" /></div>
							<div><input class= "btSearch" type="submit" value=""></input></div>	
						</form>
				</div>		
					<div><a href="<?php echo $this->url(array('controller'=>'wage','action'=>'add'))?>"><img src="/images/icons/functions/new.png"/><p>新建</p></a></div><!--修改处-->
					<div><a href="#msgBox" class="lightbox" id="btDel"><img src="/images/icons/functions/delete.png"/><p>删除</p></a></div>
					<div><a href="<?php echo $this->url(); ?>"><img src="/images/icons/functions/refresh.png"/><p>显示全部</p></a></div>
					<div><a href="#"><img src="/images/icons/functions/export.png"/><p>导出</p></a></div>	
					<div><a href="#"><img src="/images/icons/functions/print.png"/><p>打印</p></a></div>	
				</div><!-- end of button group -->
			</div><!-- end of overall tool -->
			<div class="overall_content">
				<table>
					<colgroup><!--修改处-->
						<col style="width:5%"></col>
						<col style="width:5%"></col>
						<col style="width:20%"></col>
						<col style="width:20%"></col>
						<col style="width:20%"></col>
						<col style="width:20%"></col>
						<col style="width:5%"></col>
						<col style="width:5%"></col>						
					</colgroup>
					<thead>
						<th>#</th>
						<th><input id="modelName" type="text" class="hide" value="<?php echo $this->modelName ?>"></th><!--检查处-->
						<th>工人姓名</th><!--修改处-->
						<th>工资金额</th>
						<th>开始日期</th>
						<th>结束日期</th>
						<th><input id="module" type="text" class="hide" value="<?php echo $this->module ?>"></th><!--检查处-->
						<th><input id="controller" type="text" class="hide" value="<?php echo $this->controller ?>"></th><!--检查处-->
					</thead>
					<tr>
						<td><input type="checkbox" id="cb_sa"></td>
						<td colspan="2">全选/取消</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td><!--检查处-->
					</tr>	
					<?php $counter = 1;?>
					<?php foreach($this->arrayWages as $wage):?><!--修改处-->
					<?php $wagId = $this->escape($wage->getWagId());?><!--修改处-->
					<tr>
						<td><input type="checkbox" name="cb" value="<?php echo $wagId ?>"></td>
						<td><?php 
							echo $counter;
							$counter++;
						?></td>
						<td><?php echo $this->escape($wage->getWorkerName()) ?></a></td>
						<td><?php echo $this->escape($wage->getAmount()) ?></td>	
						<td><?php echo $this->escape($wage->getStartDate()) ?></td>
						<td>
						<?php echo $this->escape($wage->getEndDate())?>
						</td>
						<td><a href="<?php echo $this->url(array('controller'=>'wage','action'=>'edit','id'=>$wagId))?>">修改</a></td><!--修改处-->
						<td><a class="lightbox" href="/worker/wage/ajaxdisplay/id/<?php echo $wagId ?>">详情</a></td><!--修改处-->
					</tr>
					<?php endforeach ?>
				</table>
				<div id="msgBox"></div>
			</div><!-- end of overall content -->
		</div><!-- end of p_content -->
	</div><!-- end of page stage -->
	</div><!-- end of contentWrapper --> 