<link href="/css/p_login.css" rel="stylesheet" type="text/css" />
 <?php 
 	$this->headTitle('- 无权访问');
 ?>
<div id="contentWrapper">
	<div id="p_stage">
		<div id="p_login">
			<div id="cap_top"></div>
			<div id="cap_body">
					<h1 class="warning allignCenter">您未授权访问该页</h1>
			</div><!-- end of cap_body -->
			<div id="cap_bottom"></div>
		</div><!-- end of page login -->
	</div><!-- end of page stage -->
	</div><!-- end of contentWrapper -->