<link href="/css/p_login.css" rel="stylesheet" type="text/css" />
<?php 
	$this->headTitle('- 浏览器错误e');
 ?>
<div id="e_id" class="hide">emsg</div>
<div id="contentWrapper">
	<div id="p_stage">
		<div id="p_login">
			<div id="cap_top"></div>
			<div id="cap_body">
				<div id="panel_Msg">
					<img src="/images/icons/functions/firefox.png" />
				</div>
				<p class="errors allignCenter">您正在使用IE或含IE内核的浏览器，为保证本系统的安全，请使用火狐(Firefox)浏览器，<a class="errors underline" target="_blank" href="http://firefox.com.cn/">点击下载</a></p>
			</div><!-- end of cap_body -->
			<div id="cap_bottom"></div>
		</div><!-- end of page login -->
	</div><!-- end of page stage -->
	</div><!-- end of contentWrapper -->