<link href="/css/p_login.css" rel="stylesheet" type="text/css" />
 <?php 
 	$this->headTitle('- 建设中e');
 ?>
<div id="contentWrapper">
	<div id="p_stage">
		<div id="p_login">
			<div id="cap_top"></div>
			<div id="cap_body">
					<img src="/images/icons/functions/underc.jpg" />
					<h1 class="warning allignCenter">页面建设中</h1>
			</div><!-- end of cap_body -->
			<div id="cap_bottom"></div>
		</div><!-- end of page login -->
	</div><!-- end of page stage -->
	</div><!-- end of contentWrapper -->