<link href="/css/p_login.css" rel="stylesheet" type="text/css" />
 <?php 
 	$this->headTitle('- 出错了');
 ?>
<div id="contentWrapper">
	<div id="p_stage">
		<div id="p_login">
			<div id="cap_top"></div>
			<div id="cap_body">
				<div id="panel_Msg">
					<img src="/images/icons/functions/error.png" />
					<p class="errors allignCenter">出错了，<a class="errors underline" href="/">返回首页</a></p>
				</div>
			</div><!-- end of cap_body -->
			<div id="cap_bottom"></div>
		</div><!-- end of page login -->
	</div><!-- end of page stage -->
	</div><!-- end of contentWrapper -->