 <?php 
	$this->headTitle(' - '.$this->modCName.' - '.$this->sidName);
 	$this->headScript()->prependFile('/js/pment.js');
 	$this->headScript()->prependFile('/js/form.js');
 	$this->headScript()->prependFile('/js/conPrg.js');
 ?>
	<div id="contentWrapper">
	<div id="p_breadcrumb"></div>
	<div id="p_stage_sidebar">	
	<?php 
		echo $this->placeholder('sidebar');
		$arrayFuncs = $this->arrayFuncs;
	?>
		<div id="p_content">
		<h1><?php echo $this->modCName.' - '.$this->sidName.' - '.$this->actCName?></h1>
		<?php 
			$project = $this->project;
			echo $this->displayProject($project);?>
		<div class="p_msg">
			<h3></h3>
			<?php if (count($this->messages)) : ?>
				<ul id="messages">
				<?php foreach ($this->messages as $message) : ?>
					<li><p class="errorMsg"><?php echo $this->escape($message); ?></p></li>
			<?php endforeach; ?>
				</ul>
			<?php endif; ?>
		</div>
		<?php $plog = $this->plog?>
			<div class="overall_tool">
				<div class="button_group">
					<?php if($arrayFuncs['edit'] == 1):?>
					<div><a href="<?php echo $this->url(array('controller'=>'plog','action'=>'edit','id'=>$plog->getPlogId()))?>"><img src="/images/icons/functions/modify.png"/><p>修改</p></a></div>
					<?php endif;?>
					<?php if($arrayFuncs['ajaxpdf'] == 1):?>
					<div><a target="_blank" href="/general/pdf/generate/page/10/id/<?php echo $plog->plogId;?>"><img src="/images/icons/functions/export.png"/><p>导出</p></a></div>
					<?php endif;?>
					<div><a href="/pment/plog"><img src="/images/icons/functions/back.png"/><p>返回</p></a></div>	
				</div><!-- end of button group -->
			</div><!-- end of overall tool -->
			<div class="overall_content">
				<p class="subMenu slideMenu">日志详情</p>
				<table>
					<colgroup>
						<col style="width:30%"></col>
						<col style="width:70%"></col>
					</colgroup>
					<tr>
						<td>日期: </td>
						<td><?php echo $plog->getLogDate()?></td>
					</tr>
					<tr>
						<td>天气(上午): </td>
						<td><?php echo $plog->getWeatherAm()?></td>
					</tr>
					<tr>
						<td>天气(下午): </td>
						<td><?php echo $plog->getWeatherPm()?></td>
					</tr>
					<tr>
						<td>最高温度(摄氏度): </td>
						<td><?php echo $plog->getTempHi()?></td>
					</tr>
					<tr>
						<td>最低温度(摄氏度): </td>
						<td><?php echo $plog->getTempLo()?></td>
					</tr>
					<tr>
						<td>施工部位: </td>
						<td><?php echo $plog->getPart()?></td>
					</tr>
					<tr>
						<td>施工人数: </td>
						<td><?php echo $plog->getNumber()?></td>
					</tr>
					<tr>
						<td>负责操作人: </td>
						<td><?php echo $plog->getOperator()?></td>
					</tr>
					<tr>
						<td>责任工长: </td>
						<td><?php echo $plog->getForeman()?></td>
					</tr>
					<tr>
						<td>安全情况: </td>
						<td><?php echo $plog->getSafety()?></td>
					</tr>
					<tr>
						<td>存在问题: </td>
						<td><?php echo $plog->getProblem()?></td>
					</tr>
					<tr>
						<td>解决问题: </td>
						<td><?php echo $plog->getResolve()?></td>
					</tr>
					<tr>
						<td>往来文件: </td>
						<td><?php echo $plog->getRelatedFile()?></td>
					</tr>
					<tr>
						<td>变更签证: </td>
						<td><?php echo $plog->getChangeSig()?></td>
					</tr>
					<tr>
						<td>材料设备情况: </td>
						<td><?php echo $plog->getMaterial()?></td>
					</tr>
					<tr>
						<td>填报人: </td>
						<td><a class="lightbox" href="/employee/index/ajaxdisplay/id/<?php echo $plog->getContactId() ?>"><?php echo $plog->getContactName() ?></td>
					</tr>
					<tr>
						<td>备注: </td>
						<td><?php echo $plog->getRemark()?></td>
					</tr>
					<tr>
						<td>创建时间: </td>
						<td><?php echo $plog->getCTime()?></td>
					</tr>
				</table>
			<div id="msgBox"></div>
			</div><!-- end of overall content -->
		</div><!-- end of p_content -->
	</div><!-- end of page stage -->
	</div><!-- end of contentWrapper -->
