<link href="css/p_generalinfo.css" rel="stylesheet" type="text/css" />
	<div id="p_id" class="hide">nav_generalInfo</div>
	<div id="s_id" class="hide">none</div>
<title>工程管理DEMO - 工程信息管理</title>
	<div id="contentWrapper">
	<div id="p_breadcrumb"></div>
	<div id="p_stage_sidebar">
		<div id="p_sidebar" class="p_sidebar_general">
			<ul>
				<li><a href="/project">工程信息</a></li>
				<li><a href="/project/progress">工程进度管理</a></li>
				<li><a href="/project/plog">总施工日志</a></li>
				<li><a href="/project/glog">班组施工日志</a></li>
			</ul>
		</div>
		<div id="p_content">
		<h1>工程管理 - 工程信息 - 总览</h1>
		<div class="p_msg">
			<h3>本页显示内容为固定资产基本信息总览</h3>
		</div>
			<div class="overall_tool">
				<div class="button_group">
					<div><input class="tbMedium tbtext" type="text" /></div>
					<div><a href="project/index/search"><img src="images/icons/functions/search.png"/><p>查询</p></a></div>	
					<div><a href="project/index/new"><img src="images/icons/functions/new.png"/><p>新建</p></a></div>
					<div><a href="project/index/delete"><img src="images/icons/functions/delete.png"/><p>删除</p></a></div>
					<div><a href="project"><img src="images/icons/functions/refresh.png"/><p>显示全部</p></a></div>
					<div><a href="#"><img src="images/icons/functions/print.png"/><p>打印</p></a></div>	
					<div><a href="#"><img src="images/icons/functions/help.png"/><p>帮助</p></a></div>	
				</div><!-- end of button group -->
			</div><!-- end of overall tool -->
			<div class="overall_content">
				<table>
					<colgroup>
						<col style="width:5%"></col>
						<col style="width:10%"></col>
						<col style="width:30%"></col>
						<col style="width:10%"></col>
						<col style="width:10%"></col>
						<col style="width:35%"></col>
					</colgroup>
					<thead>
						<th>#</th>
						<th>工程编号</th>
						<th>工程名称</th>
						<th>工程状态</th>
						<th>用途</th>
						<th>建筑面积</th>
					</thead>
										<tr>
						<td><input type="checkbox"></td>
						<td><a href="#"><a href="generalInfo_update.php">ZC-0001</a></a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
										<tr>
						<td><input type="checkbox"></td>
						<td><a href="#"><a href="generalInfo_update.php">ZC-0001</a></a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
					<tr>
						<td><input type="checkbox"></td>
						<td><a href="generalInfo_update.php">ZC-0001</a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
					<tr>
						<td><input type="checkbox"></td>
						<td><a href="generalInfo_update.php">ZC-0001</a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
										<tr>
						<td><input type="checkbox"></td>
						<td><a href="generalInfo_update.php">ZC-0001</a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
					<tr>
						<td><input type="checkbox"></td>
						<td><a href="generalInfo_update.php">ZC-0001</a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
					
					<tr>
						<td><input type="checkbox"></td>
						<td><a href="generalInfo_update.php">ZC-0001</a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
										<tr>
						<td><input type="checkbox"></td>
						<td><a href="generalInfo_update.php">ZC-0001</a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
					<tr>
						<td><input type="checkbox"></td>
						<td><a href="generalInfo_update.php">ZC-0001</a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
					<tr>
						<td><input type="checkbox"></td>
						<td><a href="generalInfo_update.php">ZC-0001</a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
										<tr>
						<td><input type="checkbox"></td>
						<td><a href="generalInfo_update.php">ZC-0001</a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
					<tr>
						<td><input type="checkbox"></td>
						<td><a href="generalInfo_update.php">ZC-0001</a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
						<tr>
						<td><input type="checkbox"></td>
						<td><a href="generalInfo_update.php">ZC-0001</a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
										<tr>
						<td><input type="checkbox"></td>
						<td><a href="generalInfo_update.php">ZC-0001</a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
					<tr>
						<td><input type="checkbox"></td>
						<td><a href="generalInfo_update.php">ZC-0001</a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
					<tr>
						<td><input type="checkbox"></td>
						<td><a href="#"><a href="generalInfo_update.php">ZC-0001</a></a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
										<tr>
						<td><input type="checkbox"></td>
						<td><a href="#"><a href="generalInfo_update.php">ZC-0001</a></a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
					<tr>
						<td><input type="checkbox"></td>
						<td><a href="generalInfo_update.php">ZC-0001</a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
					<tr>
						<td><input type="checkbox"></td>
						<td><a href="generalInfo_update.php">ZC-0001</a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
										<tr>
						<td><input type="checkbox"></td>
						<td><a href="generalInfo_update.php">ZC-0001</a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
					<tr>
						<td><input type="checkbox"></td>
						<td><a href="generalInfo_update.php">ZC-0001</a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
					
					<tr>
						<td><input type="checkbox"></td>
						<td><a href="generalInfo_update.php">ZC-0001</a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
										<tr>
						<td><input type="checkbox"></td>
						<td><a href="generalInfo_update.php">ZC-0001</a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
					<tr>
						<td><input type="checkbox"></td>
						<td><a href="generalInfo_update.php">ZC-0001</a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
					<tr>
						<td><input type="checkbox"></td>
						<td><a href="generalInfo_update.php">ZC-0001</a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
										<tr>
						<td><input type="checkbox"></td>
						<td><a href="generalInfo_update.php">ZC-0001</a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
					<tr>
						<td><input type="checkbox"></td>
						<td><a href="generalInfo_update.php">ZC-0001</a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
						<tr>
						<td><input type="checkbox"></td>
						<td><a href="generalInfo_update.php">ZC-0001</a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
										<tr>
						<td><input type="checkbox"></td>
						<td><a href="generalInfo_update.php">ZC-0001</a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
					<tr>
						<td><input type="checkbox"></td>
						<td><a href="generalInfo_update.php">ZC-0001</a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
				</table>			</div><!-- end of overall content -->
		</div><!-- end of p_content -->
	</div><!-- end of page stage -->
	</div><!-- end of contentWrapper -->
