<?php
	$this->headTitle('- 工程管理');
?>
	<div id="contentWrapper">
	<div id="p_breadcrumb"></div>
	<div id="p_stage_sidebar">
	<?php
		echo $this->placeholder('sidebar');
	?>
		<div id="p_content">
		<h1>工程管理 - 总览</h1>
		<div class="p_msg">
			<h3></h3>
			<p class="errorMsg"><?php
				if($this->errorMsg != null)
				{
					echo $this->errorMsg;
			 		}?>
			 		</p>
			<?php if (count($this->messages)) : ?>
				<ul id="messages">
				<?php foreach ($this->messages as $message) : ?>
					<li><p class="errorMsg"><?php echo $this->escape($message); ?></p></li>
			<?php endforeach; ?>
				</ul>
			<?php endif; ?>
		</div>
			<div class="overall_tool">
				<div class="button_group">
					<div id="searchBox">
						<form method="post" action="<?php echo $this->url()?>">
							<div>
								<select name="condition" class="tbMediumer stStyle">
									<option value="projectName">工程名称</option>
									<option value="structype">结构类型</option>
									<option value="name">负责人</option>
								</select>
							</div>
							<div><input class="tbMedium tbText" name="key" type="text" /></div>
							<div><input class= "btSearch" type="submit" value=""></input></div>
						</form>
					</div>
					<div><a href="<?php echo $this->url(array('controller'=>'index','action'=>'add'))?>"><img src="/images/icons/functions/new.png"/><p>新建</p></a></div>
					<div><a href="#msgBox" class="lightbox" id="btDel"><img src="/images/icons/functions/delete.png"/><p>删除</p></a></div>
					<div><a href="<?php echo $this->url(); ?>"><img src="/images/icons/functions/refresh.png"/><p>显示全部</p></a></div>
					<div><a href="#"><img src="/images/icons/functions/export.png"/><p>导出</p></a></div>
					<div><a href="#"><img src="/images/icons/functions/print.png"/><p>打印</p></a></div>
				</div><!-- end of button group -->
			</div><!-- end of overall tool -->
			<div class="overall_content">
				<table>
					<colgroup>
						<col style="width:3%"></col>
						<col style="width:2%"></col>
						<col style="width:25%"></col>
						<col style="width:8%"></col>
						<col style="width:10%"></col>
						<col style="width:10%"></col>
						<col style="width:10%"></col>
						<col style="width:15%"></col>
						<col style="width:5%"></col>
						<col style="width:5%"></col>
						<col style="width:7%"></col>
					</colgroup>
					<thead>
						<th>#</th>
						<th><input id="modelName" type="text" class="hide" value="<?php echo $this->modelName ?>"></th>
						<th>工程名称</th>
						<th>工程状态</th>
						<th>结构类型</th>
						<th>开工时间</th>
						<th>项目经理</th>
						<th>施工许可证编号</th>
						<th>当前进度阶段</th>
						<th><input id="module" type="text" class="hide" value="<?php echo $this->module ?>"></th>
						<th><input id="controller" type="text" class="hide" value="<?php echo $this->controller ?>"></th>
					</thead>
					<tr>
						<td><input type="checkbox" id="cb_sa"></td>
						<td colspan="2">全选/取消</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<?php $counter = 1;?>
					<?php foreach($this->arrayProjects as $project):?>
					<?php $projectId = $this->escape($project->getProjectId());?>
					<tr>
						<td><input type="checkbox" name="cb" value="<?php echo $projectId ?>"></td>
						<td><?php
							echo $counter;
							$counter++;
						?></td>
						<td><a class="lightbox" href="<?php echo $this->url(array('controller'=>'index','action'=>'ajaxdisplay','id'=>$projectId))?>"><?php echo $this->escape($project->getName()) ?></a></td>
						<td><?php echo $this->escape($project->getStatus())?></td>
						<td><?php echo $this->escape($project->getStructype()) ?></td>
						<td><?php echo $this->escape($project->getStartDate()) ?></td>
						<td><a class="lightbox" href="/employee/index/ajaxdisplay/id/<?php echo $this->escape($project->getContactId()) ?>"><?php echo $this->escape($project->getContactName())?></a></td>
						<td><?php echo $this->escape($project->getLicense()) ?></td>
						<td><?php echo $this->escape($project->getStage()) ?></td>
						<td><a href="<?php echo $this->url(array('controller'=>'index','action'=>'edit','id'=>$projectId))?>">修改</a></td>
						<td><a href="pment/index/index/id/<?php echo $projectId?>">管理工程</a></td>
					</tr>
					<?php endforeach ?>
				</table>
				<div id="msgBox"></div>
			</div><!-- end of overall content -->
		</div><!-- end of p_content -->
	</div><!-- end of page stage -->
	</div><!-- end of contentWrapper -->
