 <?php 
 	$this->headTitle('- 分包管理 - 分包单信息');
 	$this->headScript()->prependFile('/js/contractjs/p_subcontract.js');
 ?>
	<div id="contentWrapper">
	<div id="p_breadcrumb"></div>
	<div id="p_stage_sidebar">	
	<?php 
		echo $this->placeholder('sidebar');
	?>
		<div id="p_content">
		<h1>分包管理 - 分包单信息 - 总览</h1>
		<div class="p_msg">
			<h3></h3>
			<p class="errorMsg"><?php
				if($this->errorMsg != null)
				{
					echo $this->errorMsg;
			 		}?>
			 		</p>
		</div>
			<div class="overall_tool">
				<div class="button_group">
				<div id="searchBox">
					<form method="post" action="<?php echo $this->url()?>">
							<div>
								<select name="condition" class="tbMediumer stStyle">
  									<option value="projectName">工程名称</option>
									<option value="contractorName">承包商名称</option>
								</select>
							</div>
							<div><input class="tbMedium tbText" name="key" type="text" /></div>
							<div><input class= "btSearch" type="submit" value=""></input></div>	
						</form>
				</div>	
					<div><a href="<?php echo $this->url(array('controller'=>'subcontract','action'=>'add'))?>"><img src="/images/icons/functions/new.png"/><p>新建</p></a></div>
					<div><a href="#msgBox" class="lightbox" id="btDel"><img src="/images/icons/functions/delete.png"/><p>删除</p></a></div>
					<div><a href="<?php echo $this->url(); ?>"><img src="/images/icons/functions/refresh.png"/><p>显示全部</p></a></div>
					<div><a href="#"><img src="/images/icons/functions/export.png"/><p>导出</p></a></div>	
					<div><a href="#"><img src="/images/icons/functions/print.png"/><p>打印</p></a></div>	
				</div><!-- end of button group -->
			</div><!-- end of overall tool -->
			<div class="overall_content">
				<table>
					<colgroup>
						<col style="width:3%"></col>
						<col style="width:2%"></col>
						<col style="width:10%"></col>
						<col style="width:10%"></col>
						<col style="width:12%"></col>
						<col style="width:13%"></col>
						<col style="width:25%"></col>
						<col style="width:15%"></col>
						<col style="width:5%"></col>
						<col style="width:5%"></col>
					</colgroup>
					<thead>
						<th>#</th>
						<th><input id="modelName" type="text" class="hide" value="<?php echo $this->modelName ?>"></th>
						<th>工程名称</th>
						<th>分包类型</th>
						<th>承包商名称</th>
						<th>预计工期</th>
						<th>实际工期</th>
						<th>合同造价</th>
						<th><input id="module" type="text" class="hide" value="<?php echo $this->module ?>"></th>
						<th><input id="controller" type="text" class="hide" value="<?php echo $this->controller ?>"></th>
					</thead>
					<tr>
						<td><input type="checkbox" id="cb_sa"></td>
						<td colspan="2">全选/取消</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>	
					<?php $counter = 1;?>	
					<?php foreach($this->arraySubcontracts as $subcontract):?>
					<?php $scontrId = $this->escape($subcontract->getScontrId()); ?>
					<tr>
						<td><input type="checkbox" name="cb" value="<?php echo $scontrId; ?>"></td>
						<td><?php 
							echo $counter;
							$counter++;
						?></td>
						<td><a href="/project/index/display/id/<?php echo $this->escape($subcontract->getProjectId()) ?>"><?php echo $this->escape($subcontract->getProjectName()) ?></a></td>
						<td><?php echo $this->escape($subcontract->getScontrType()) ?></td>
						<td><a href="/contract/index/display/id/<?php echo $this->escape($subcontract->getContractorId()) ?>"><?php echo $this->escape($subcontract->getContractorName()) ?></td>
						<td><?php echo $this->escape($subcontract->getPeriodExp()) ?></td>
						<td><?php echo $this->escape($subcontract->getPeriodAct()) ?></td>	
						<td><?php echo $this->escape($subcontract->getContrAmt())?></td>
						<td><a href="<?php echo $this->url(array('controller'=>'subcontract','action'=>'edit','id'=>$scontrId))?>">修改</a></td>	
						<td><a href="<?php echo $this->url(array('controller'=>'subcontract','action'=>'ajaxdisplay','id'=>$scontrId))?>" class="lightbox">详情</a></td>
					</tr>
					<?php endforeach ?>
				</table>
				<div id="msgBox"></div>
			</div><!-- end of overall content -->
		</div><!-- end of p_content -->
	</div><!-- end of page stage -->
	</div><!-- end of contentWrapper -->
