 <?php 
 	$this->headTitle('- 机械设备管理 - 机械设备需求计划');
 	$this->headScript()->prependFile('/js/equipmentjs/p_local.js');
 ?>
	<div id="contentWrapper">
	<div id="p_breadcrumb"></div>
	<div id="p_stage_sidebar">	
	<?php 
		echo $this->placeholder('sidebar');
	?>
		<div id="p_content">
		<h1>机械设备管理 - 机械设备需求计划 - 新建设备</h1>
		<div class="p_msg">
			<h3></h3>
		</div>
			<div class="overall_tool">
				<div class="button_group">
					<div><a href="#msgBox" class="lightbox" id="btDel"><img src="/images/icons/functions/delete.png"/><p>删除</p></a></div>
					<div><a href="/equipment/plan/edit/id/<?php echo $this->id?>"><img src="/images/icons/functions/pre.png"/><p>上页</p></a></div>	
					<div><a href="/equipment/plan/"><img src="/images/icons/functions/back.png"/><p>返回</p></a></div>	

				</div><!-- end of button group -->
			</div><!-- end of overall tool -->
			<div class="overall_content">
				<div class="overall_content_left">
				<p class="subMenu">机械设备需求计划</p>
				<?php $plan = $this->plan?>
				<table>
					<colgroup>
						<col style="width:30%"></col>
						<col style="width:70%"></col>					
					</colgroup>
					<tr>
					<tr>
						<td>工程名称: </td>
						<td><?php echo $plan->getProjectName()?></td>
					</tr>
					<tr>
						<td>计划类型: </td>
						<td><?php echo $plan->getPlanType()?></td>
					</tr>
					<tr>
						<td>计划到位时间: </td>
						<td><?php echo $plan->getDueDate()?></td>
					</tr>
					<tr>
						<td>申报人: </td>
						<td><?php echo $plan->getApplicName()?></td>
					</tr>
					<tr>
						<td>申报时间: </td>
						<td><?php echo $plan->getApplicDate()?></td>
					</tr>
					<tr>
						<td>审批人: </td>
						<td><?php echo $plan->getApprovName()?></td>
					</tr>
					<tr>
						<td>审批时间: </td>
						<td><?php echo $plan->getApprovDate()?></td>
					</tr>
					<tr>
						<td>备注: </td>
						<td><?php echo $plan->getRemark()?></td>
					</tr>
					<tr>
						<td>上次修改时间: </td>
						<td><?php echo $plan->getCTime()?></td>
					</tr>
				</table>

				</div><!-- end of overall_content_left -->
				<div class="overall_content_right">
				<p class="subMenu">新增设备</p>
				<form action="<?php echo $this->url()?>" method="post">
				<table>
					<tr>
						<td><label>类别: </label></td>
						<td><select id="eqptype" name="eqptype" class="tbMedium tbText"></select></td>
						<td><label>名称: </label></td>
						<td><select id="eqpId" name="eqpId" class="tbMedium tbText"></select></td>
					</tr>
					<tr>
						<td><label>单价: </label></td>
						<td><input type="text" name="price" id="ajax_price" class="tbMedium tbText"/></td>
						<td><label>数量: </label></td>
						<td><input type="text" name="quantity" id="ajax_quantity" class="tbMedium tbText"/></td>
					</tr>
					<tr>
						<td colspan="2"><!-- <p id ="reset" class="btConfirmVar radius floatr">重填</p> --></td>
						<td colspan="2"><input type="submit" id ="submit" value="添加" class="btConfirmVar radius floatl"/></td>
					</tr>		
					</table>
					</form>
					<p class="subMenu">计划相关机械设备信息</p>
					<table>
					<colgroup>
						<col style="width:10%"></col>
						<col style="width:10%"></col>
						<col style="width:20%"></col>
						<col style="width:20%"></col>
						<col style="width:20%"></col>
						<col style="width:20%"></col>
					</colgroup>
					<thead>
						<th>#</th>
						<th></th>
						<th>机械设备名称</th>
						<th>单价</th>
						<th>数量</th>
						<th>金额</th>
					</thead>
					<tr>
						<td><input type="checkbox" id="cb_sa"></td>
						<td colspan="2">全选/取消</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<?php $counter = 1;?>
					<?php foreach($this->arrayEqpplans as $eqpplan):?>
					<?php $eplanId = $this->escape($eqpplan->getEplanId());?>
					<tr>
						<td><input type="checkbox" name="cb" value="<?php echo $eplanId ?>"></td>
						<td><?php
							echo $counter;
							$counter++;
						?></td>
						<td><a class="lightbox" href="/equipment/index/ajaxdisplay/id/<?php echo $this->escape($eqpplan->getEqpId())?>"><?php echo $this->escape($eqpplan->getEqpName()) ?></a></td>
						<td><?php echo $this->escape($eqpplan->getPrice())?></td>
						<td><?php echo $this->escape($eqpplan->getQuantity())?></td>
						<td><?php echo $this->escape($eqpplan->getAmount())?></td>
					</tr>
					<?php endforeach ?>
				</table>
				<div id="msgBox"></div>
				<p id="ajax_id" class="hide"><?php echo $this->id?></p>
				<input id="modelName" type="text" class="hide" value="<?php echo $this->modelName ?>">
				<input id="module" type="text" class="hide" value="<?php echo $this->module ?>">
				<input id="controller" type="text" class="hide" value="<?php echo $this->controller ?>">
				</div><!-- end of overall_content_right -->
			</div><!-- end of overall content -->
		</div><!-- end of p_content -->
	</div><!-- end of page stage -->
	</div><!-- end of contentWrapper -->
