<div id="ajaxMsgBox">
<div id="ajaxMsgBox_Emp">
	<div class="overall_tool">
		<div class="button_group">
		<?php 	$arrayFuncs = $this->arrayFuncs;?>
			<?php if($arrayFuncs['ajaxpdf'] == 1):?>
			<div><a href="#"><img src="/images/icons/functions/export.png"/><p>导出</p></a></div>
			<?php endif;?>
			</div><!-- end of button group -->
	</div><!-- end of overall tool -->
	<?php $measure = $this->measure;?>
	<div class="overall_content">
		<table>
			<colgroup>
				<col style="width:30%"></col>
				<col style="width:70%"></col>
			</colgroup>
			<tr>
				<td>日期：</td>
				<td><?php echo $measure->getMeaDate()?></td>
			</tr>
			<tr>
				<td>存在问题：</td>
				<td><?php echo $measure->getProblem() ?></td>
			</tr>
			<tr>
				<td>采取方法： </td>
				<td><?php echo $measure->getMeasure()?></td>
			</tr>
			<tr>
				<td>填报人：</td>
				<td><?php echo $this->escape($measure->getContactName())?></td>
			</tr>
			<tr>
				<td>备注：</td>
				<td><?php echo $measure->getRemark()?></td>
			</tr>
			<tr>
				<td>上次修改时间：</td>
				<td><?php echo $measure->getCTime()?></td>
			</tr>
		</table>
	</div>
</div>
</div>