
	<div id="p_id" class="hide">nav_generalInfo</div>
	<div id="s_id" class="hide">none</div>
<title>- 固定资产管理 - 固定资产购置信息</title>
	<div id="contentWrapper">
	<div id="p_breadcrumb"></div>
	<div id="p_stage_sidebar">
		<div id="p_sidebar" class="p_sidebar_general">
			<ul>
				<li><a href="generalInfo.php">固定资产<span class="hide">gi_gdzc</span></a></li>
				<li><a href="#">仓库</a></li>
				<li><a href="#">材料类别</a></li>
				<li><a href="#">供应商</a></li>
				<li><a href="#">设备</a></li>
				<li><a href="#">单位及收支类别</a></li>
				<li><a href="#">银行账户</a></li>
				<li><a href="#">工程信息</a></li>
			</ul>
		</div>
		<div id="p_content">
		<h1>固定资产管理 - 固定资产购置信息 - 总览</h1>
		<div class="p_msg">
			<h3></h3>
		</div>
			<div class="overall_tool">
				<div class="button_group">
					<div><input class="tbMedium tbtext" type="text" /></div>
					<div><a href="#"><img src="images/icons/functions/search.png"/><p>查询</p></a></div>	
					<div><a href="generalInfo_new.php"><img src="images/icons/functions/new.png"/><p>新建</p></a></div>
					<div><a href="#"><img src="images/icons/functions/delete.png"/><p>删除</p></a></div>
					<div><a href="generalInfo.php"><img src="images/icons/functions/refresh.png"/><p>显示全部</p></a></div>
					<div><a href="#"><img src="images/icons/functions/print.png"/><p>打印</p></a></div>	
					<div><a href="#"><img src="images/icons/functions/help.png"/><p>帮助</p></a></div>	
				</div><!-- end of button group -->
			</div><!-- end of overall tool -->
			<div class="overall_content">
				<table>
					<colgroup>
						<col style="width:5%"></col>
						<col style="width:10%"></col>
						<col style="width:30%"></col>
						<col style="width:10%"></col>
						<col style="width:10%"></col>
						<col style="width:35%"></col>
					</colgroup>
					<thead>
						<th>#</th>
						<th>资产编号</th>
						<th>资产名称</th>
						<th>单位</th>
						<th>规格型号</th>
						<th>生产厂家</th>
					</thead>
										<tr>
						<td><input type="checkbox"></td>
						<td><a href="#"><a href="generalInfo_update.php">ZC-0001</a></a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
										<tr>
						<td><input type="checkbox"></td>
						<td><a href="#"><a href="generalInfo_update.php">ZC-0001</a></a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
					<tr>
						<td><input type="checkbox"></td>
						<td><a href="generalInfo_update.php">ZC-0001</a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
					<tr>
						<td><input type="checkbox"></td>
						<td><a href="generalInfo_update.php">ZC-0001</a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
										<tr>
						<td><input type="checkbox"></td>
						<td><a href="generalInfo_update.php">ZC-0001</a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
					<tr>
						<td><input type="checkbox"></td>
						<td><a href="generalInfo_update.php">ZC-0001</a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
					
					<tr>
						<td><input type="checkbox"></td>
						<td><a href="generalInfo_update.php">ZC-0001</a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
										<tr>
						<td><input type="checkbox"></td>
						<td><a href="generalInfo_update.php">ZC-0001</a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
					<tr>
						<td><input type="checkbox"></td>
						<td><a href="generalInfo_update.php">ZC-0001</a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
					<tr>
						<td><input type="checkbox"></td>
						<td><a href="generalInfo_update.php">ZC-0001</a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
										<tr>
						<td><input type="checkbox"></td>
						<td><a href="generalInfo_update.php">ZC-0001</a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
					<tr>
						<td><input type="checkbox"></td>
						<td><a href="generalInfo_update.php">ZC-0001</a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
						<tr>
						<td><input type="checkbox"></td>
						<td><a href="generalInfo_update.php">ZC-0001</a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
										<tr>
						<td><input type="checkbox"></td>
						<td><a href="generalInfo_update.php">ZC-0001</a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
					<tr>
						<td><input type="checkbox"></td>
						<td><a href="generalInfo_update.php">ZC-0001</a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
					<tr>
						<td><input type="checkbox"></td>
						<td><a href="#"><a href="generalInfo_update.php">ZC-0001</a></a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
										<tr>
						<td><input type="checkbox"></td>
						<td><a href="#"><a href="generalInfo_update.php">ZC-0001</a></a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
					<tr>
						<td><input type="checkbox"></td>
						<td><a href="generalInfo_update.php">ZC-0001</a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
					<tr>
						<td><input type="checkbox"></td>
						<td><a href="generalInfo_update.php">ZC-0001</a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
										<tr>
						<td><input type="checkbox"></td>
						<td><a href="generalInfo_update.php">ZC-0001</a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
					<tr>
						<td><input type="checkbox"></td>
						<td><a href="generalInfo_update.php">ZC-0001</a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
					
					<tr>
						<td><input type="checkbox"></td>
						<td><a href="generalInfo_update.php">ZC-0001</a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
										<tr>
						<td><input type="checkbox"></td>
						<td><a href="generalInfo_update.php">ZC-0001</a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
					<tr>
						<td><input type="checkbox"></td>
						<td><a href="generalInfo_update.php">ZC-0001</a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
					<tr>
						<td><input type="checkbox"></td>
						<td><a href="generalInfo_update.php">ZC-0001</a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
										<tr>
						<td><input type="checkbox"></td>
						<td><a href="generalInfo_update.php">ZC-0001</a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
					<tr>
						<td><input type="checkbox"></td>
						<td><a href="generalInfo_update.php">ZC-0001</a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
						<tr>
						<td><input type="checkbox"></td>
						<td><a href="generalInfo_update.php">ZC-0001</a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
										<tr>
						<td><input type="checkbox"></td>
						<td><a href="generalInfo_update.php">ZC-0001</a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
					<tr>
						<td><input type="checkbox"></td>
						<td><a href="generalInfo_update.php">ZC-0001</a></td>
						<td>推土机</td>
						<td>辆</td>
						<td>GASDF-ASDF11</td>
						<td>一汽大众</td>
					</tr>
				</table>			</div><!-- end of overall content -->
		</div><!-- end of p_content -->
	</div><!-- end of page stage -->
	</div><!-- end of contentWrapper -->
