 <?php 
 	$this->headTitle('- 机械设备管理 - 机械设备需求计划');
 	$this->headScript()->prependFile('/js/equipmentjs/p_plan.js');
 ?>
	<div id="contentWrapper">
	<div id="p_breadcrumb"></div>
	<div id="p_stage_sidebar">	
	<?php 
		echo $this->placeholder('sidebar');
	?>
		<div id="p_content">
		<h1>机械设备管理 - 机械设备需求计划 - 总览</h1>
		<div class="p_msg">
			<h3></h3>
			<p class="errorMsg"><?php
				if($this->errorMsg != null)
				{
					echo $this->errorMsg;
			 		}?>
			 		</p>
		</div>
			<div class="overall_tool">
				<div class="button_group">
					<div id="searchBox">
					<form method="post" action="<?php echo $this->url()?>">
							<div>
								<select name="condition" class="tbMediumer stStyle">
  									<option value="planType">计划类型</option>
									<option value="projectName">工程名称</option>
  									<option value="applicName">申报人</option>
								</select>
							</div>
							<div><input class="tbMedium tbText" name="key" type="text" /></div>
							<div><input class= "btSearch" type="submit" value=""></input></div>	
						</form>
					</div>	
					<div><a href="<?php echo $this->url(array('controller'=>'plan','action'=>'add'))?>"><img src="/images/icons/functions/new.png"/><p>新建</p></a></div>
					<div><a href="#msgBox" class="lightbox" id="btDel"><img src="/images/icons/functions/delete.png"/><p>删除</p></a></div>
					<div><a href="<?php echo $this->url(); ?>"><img src="/images/icons/functions/refresh.png"/><p>显示全部</p></a></div>
					<div><a href="#"><img src="/images/icons/functions/export.png"/><p>导出</p></a></div>	
					<div><a href="#"><img src="/images/icons/functions/print.png"/><p>打印</p></a></div>	
				</div><!-- end of button group -->
			</div><!-- end of overall tool -->
			<div class="overall_content">
				<table>
					<colgroup>
						<col style="width:5%"></col>
						<col style="width:5%"></col>
						<col style="width:16%"></col>
						<col style="width:16%"></col>
						<col style="width:16%"></col>
						<col style="width:16%"></col>
						<col style="width:16%"></col>						
						<col style="width:5%"></col>
						<col style="width:5%"></col>
					</colgroup>
					<thead>
						<th>#</th>
						<th><input id="modelName" type="text" class="hide" value="<?php echo $this->modelName ?>"></th>
						<th>项目名称</th>
						<th>计划类型</th>
						<th>计划到位时间</th>
						<th>申报人</th>
						<th>总金额</th>
						<th><input id="module" type="text" class="hide" value="<?php echo $this->module ?>"></th>
						<th><input id="controller" type="text" class="hide" value="<?php echo $this->controller ?>"></th>
					</thead>
					<tr>
						<td><input type="checkbox" id="cb_sa"></td>
						<td colspan="2">全选/取消</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<?php $counter = 1;?>	
					<?php foreach($this->arrayPlans as $plan):?>
					<?php $planId = $this->escape($plan->getPlanId()); ?>
					<tr>
						<td><input type="checkbox" name="cb" value="<?php echo $planId; ?>"></td>
						<td><?php 
							echo $counter;
							$counter++;
						?></td>
						<td><a href="/project/index/display/id/<?php echo $this->escape($plan->getProjectId())?>"><?php echo $this->escape($plan->getProjectName()) ?></a></td>
						<td><?php echo $this->escape($plan->getPlanType())?></td>	
						<td><?php echo $this->escape($plan->getDueDate())?></td>
						<td><a class="lightbox" href="/employee/index/ajaxdisplay/id/<?php echo $this->escape($plan->getApplicId())?>"><?php echo $this->escape($plan->getApplicName()) ?></a></td>
						<td><?php echo $this->escape($plan->getTotal())?></td>	
						<td><a href="<?php echo $this->url(array('controller'=>'plan','action'=>'edit','id'=>$planId))?>">修改</a></td>
						<td><a href="<?php echo $this->url(array('controller'=>'plan','action'=>'display','id'=>$planId))?>">详情</a></td>
					</tr>
					<?php endforeach ?>
				</table>
				<div id="msgBox"></div>
			</div><!-- end of overall content -->
		</div><!-- end of p_content -->
	</div><!-- end of page stage -->
	</div><!-- end of contentWrapper -->
