 <?php 
 	$this->headTitle('-员工基本信息管理');
 	$this->headScript()->prependFile('/js/employeejs/p_employee.js');
 ?>
 	<div id="p_id" class="hide">nav_generalInfo</div>
	<div id="s_id" class="hide">none</div>
	<div id="contentWrapper">
	<div id="p_breadcrumb"></div>
	<div id="p_stage_sidebar">	
	<?php 
		echo $this->placeholder('sidebar');
	?>
		<div id="p_content">
		<h1>员工及岗位管理 - 公司员工基本信息管理 - 总览</h1>
		<div class="p_msg">
			<h3>本页显示内容为公司员工基本信息总览</h3>
		</div>
			<div class="overall_tool">
				<div class="button_group">
					<div><input class="tbMedium tbtext" type="text" /></div>
					<div><a href="#"><img src="/images/icons/functions/search.png"/><p>查询</p></a></div>	
					<div><a href="<?php echo $this->url(array('controller'=>'employee','action'=>'add'))?>"><img src="/images/icons/functions/new.png"/><p>新建</p></a></div>
					<div><a href="#msgBox" class="lightbox" id="btDel"><img src="/images/icons/functions/delete.png"/><p>删除</p></a></div>
					<div><a href="<?php echo $this->url(); ?>"><img src="/images/icons/functions/refresh.png"/><p>显示全部</p></a></div>
					<div><a href="#"><img src="/images/icons/functions/print.png"/><p>打印</p></a></div>	
					<div><a href="#"><img src="/images/icons/functions/help.png"/><p>帮助</p></a></div>	
				</div><!-- end of button group -->
			</div><!-- end of overall tool -->
			<div class="overall_content">
				<table>
					<colgroup>
						<col style="width:3%"></col>
						<col style="width:2%"></col>
						<col style="width:10%"></col>
						<col style="width:15%"></col>
						<col style="width:15%"></col>
						<col style="width:15%"></col>
						<col style="width:25%"></col>
						<col style="width:10%"></col>
						<col style="width:5%"></col>
					</colgroup>
					<thead>
						<th>#</th>
						<th></th>
						<th>姓名</th>
						<th>部门</th>
						<th>职务</th>
						<th>职称</th>
						<th>联系电话</th>
						<th>状态</th>
						<th></th>
					</thead>
					<tr>
						<td><input type="checkbox" id="cb_sa"></td>
						<td colspan="2">全选/取消</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>	
					<?php $counter = 1;?>	
					<?php foreach($this->employees as $employee):?>
					<?php $empId = $this->escape($employee->getEmpId()); ?>
					<tr>
						<td><input type="checkbox" name="cb" value="<?php echo $empId; ?>"></td>
						<td><?php 
							echo $counter;
							$counter++;
						?></td>
						<td><a href="<?php echo $this->url(array('controller'=>'index','action'=>'ajaxdisplay','id'=>$empId))?>" class="lightbox"><?php echo $this->escape($employee->getEmpName()) ?></td>
						<td><?php echo $this->escape($employee->getDeptName()) ?></td>
						<td><?php echo $this->escape($employee->getDutyName()) ?></td>
						<td><?php echo $this->escape($employee->getTitleName()) ?></td>
						<td><?php echo $this->escape($employee->getPhoneNo()) ?></td>	
						<td><?php 
							$status = $this->escape($employee->getStatus());
							$stDis = "none";
							if($status == 0)
							{
								$stDis = "在职";
								}
								else
								{
									$stDis = "离职";
									}
						echo $stDis;
						  ?></td>	
						<td><a href="<?php echo $this->url(array('controller'=>'employee','action'=>'edit','id'=>$empId))?>">修改</a></td>
					</tr>
					<?php endforeach ?>
				</table>
				<div id="msgBox"></div>
			</div><!-- end of overall content -->
		</div><!-- end of p_content -->
	</div><!-- end of page stage -->
	</div><!-- end of contentWrapper -->
