 <?php 
 	$this->headTitle('-通讯录管理');
 	$this->headLink()->appendStylesheet('/css/p_employee.css');
 	$this->headScript()->prependFile('/js/empjs/p_employee.js');
 ?>
 	<div id="p_id" class="hide">nav_generalInfo</div>
	<div id="s_id" class="hide">none</div>
	<div id="contentWrapper">
	<div id="p_breadcrumb"></div>
	<div id="p_stage_sidebar">	
	<?php 
		echo $this->placeholder('sidebar');
	?>
		<div id="p_content">
		<h1>员工及岗位管理 - 通讯录管理 - 总览</h1>
		<div class="p_msg">
			<h3>本页显示内容为通讯录总览</h3>
		</div>
			<div class="overall_tool">
				<div class="button_group">
					<div><input class="tbMedium tbtext" type="text" /></div>
					<div><a href="#"><img src="/images/icons/functions/search.png"/><p>查询</p></a></div>	
					<div><a href="<?php echo $this->url(array('controller'=>'employee','action'=>'add'))?>"><img src="/images/icons/functions/new.png"/><p>新建</p></a></div>
					<div><a href="#msgBox" class="lightbox" id="btDelete"><img src="/images/icons/functions/delete.png"/><p>删除</p></a></div>
					<div><a href="<?php echo $this->url(); ?>"><img src="/images/icons/functions/refresh.png"/><p>显示全部</p></a></div>
					<div><a href="#"><img src="/images/icons/functions/print.png"/><p>打印</p></a></div>	
					<div><a href="#"><img src="/images/icons/functions/help.png"/><p>帮助</p></a></div>	
				</div><!-- end of button group -->
			</div><!-- end of overall tool -->
			<div class="overall_content">
				<table>
					<colgroup>
						<col style="width:5%"></col>
						<col style="width:10%"></col>
						<col style="width:15%"></col>
						<col style="width:15%"></col>
						<col style="width:15%"></col>
						<col style="width:25%"></col>
						<col style="width:10%"></col>
						<col style="width:5%"></col>
					</colgroup>
					<thead>
						<th>#</th>
						<th>员工录编号</th>
						<th>姓名</th>
						<th>性别</th>
						<th>部门</th>
						<th>职务</th>
						<th>职称</th>
						<th></th>
					</thead>
					<tr>
						<td><input type="checkbox" id="cb_sa"></td>
						<td>全选/取消</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>	
					<?php foreach($this->entries as $entry):?>
					<tr>
						<td><input type="checkbox" name="cbEmp" value="<?php echo $this->escape($entry->contactId); ?>"></td>
						<td><a href="<?php echo $this->url(array('controller'=>'index','action'=>'ajaxdisplay','id'=>$this->escape($entry->contactId)))?>" class="lightbox"><?php echo 'YG'.$this->escape($entry->contactId) ?></a></td>
						<td><?php echo $this->escape($entry->name) ?></td>
						<td><?php echo $this->escape($entry->gender) ?></td>	
						<td><?php echo $this->escape($entry->deptName) ?></td>
						<td><?php echo $this->escape($entry->dutyName) ?></td>
						<td><?php echo $this->escape($entry->titleName) ?></td>
						<td><a href="<?php echo $this->url(array('controller'=>'index','action'=>'edit','id'=>$this->escape($entry->contactId)))?>">修改</a></td>
					</tr>
					<?php endforeach ?>
				</table>
				<div id="msgBox"></div>
			</div><!-- end of overall content -->
		</div><!-- end of p_content -->
	</div><!-- end of page stage -->
	</div><!-- end of contentWrapper -->
