<link href="/css/buble.css" rel="stylesheet" type="text/css" />
<?php 
 	$this->headTitle('- 工程管理 - 工程月进度计划');
 	$this->headScript()->prependFile('/js/pment.js');
 	$this->headScript()->prependFile('/js/form.js');
 	$this->headScript()->prependFile('/js/conPrg.js');
 	$this->headScript()->prependFile('/js/buble.js');
 ?>

	<div id="contentWrapper">
	<div id="p_breadcrumb"></div>
	<div id="p_stage_sidebar">	
	<?php 
		echo $this->placeholder('sidebar');
	?>
		<div id="p_content">
		<h1>工程管理 - 工程月进度计划 - 详情</h1>
		<?php 
			$project = $this->project;
			echo $this->displayProject($project);?>
		<div class="p_msg">
			<h3></h3>
			<p class="errorMsg"><?php
				if($this->errorMsg != null)
				{
					echo $this->errorMsg;
			 	}?>
			</p>
		</div>
			<div class="overall_tool">
				<div class="button_group">
					<div><a href="#"/><img src="/images/icons/functions/export.png"/><p>导出</p></a></div>
					<div><a href="#"><img src="/images/icons/functions/print.png"/><p>打印</p></a></div>	
					<div><a href="/pment/monprg"><img src="/images/icons/functions/back.png"/><p>返回</p></a></div>	
				</div><!-- end of button group -->
			</div><!-- end of overall tool -->
			<div class="overall_content">
				<p class="subMenu slideMenu"><a id="btMst" class="subMenu_switch_open">任务详情</a></p>
				<?php $monprg = $this->monprg?>
				<table>
					<colgroup>
						<col style="width:30%"></col>
						<col style="width:70%"></col>
					</colgroup>
					<tr>
						<td>年份: </td>
						<td><?php echo $monprg->getYearNum()?></td>
					</tr>
					<tr>
						<td>月份: </td>
						<td><?php echo $monprg->getMonNum()?></td>
					</tr>
					<tr>
						<td>总进度任务名称: </td>
						<td><?php echo $monprg->getSubTask()?></td>
					</tr>
				</table>
				<div id="conMst" class="hide">
				<table>
					<colgroup>
						<col style="width:30%"></col>
						<col style="width:70%"></col>
					</colgroup>
					<tr>
						<td>开始日期: </td>
						<td><?php echo $monprg->getStartDate()?></td>
					</tr>
					<tr>
						<td>结束日期: </td>
						<td><?php echo $monprg->getEndDate()?></td>
					</tr>
					<tr>
						<td>工期(天): </td>
						<td><?php echo $monprg->getPeriod()?></td>
					</tr>
					<tr>
						<td>编制人: </td>
						<td><a class="lightbox" href="/employee/index/ajaxdisplay/id/<?php echo $monprg->getContactId() ?>"><?php echo $monprg->getContactName() ?></a></td>
					</tr>
					<tr>
						<td>备注: </td>
						<td><?php echo $monprg->getRemark()?></td>
					</tr>
					<tr>
						<td>创建时间: </td>
						<td><?php echo $monprg->getCTime()?></td>
					</tr>
				</table>
				</div>
			<p class="subMenu slideMenu"><a id="btImgUpload" class="subMenu_switch_close">施工图片上传</a></p>
			<div id="conUpload">
				<?php
					$this->imageForm->setAction($this->url());
					echo $this->imageForm;
				?>
			</div>
			<p class="subMenu slideMenu"><a id="btImgShow" class="subMenu_switch_open">施工图片展示</a></p>
			<div id="conImage">
			<?php foreach($this->arrayImages as $image):?>
				<div class="conImage_cell bubbleInfo">
					<div>
						<a class="lightbox" href="/images/upload/<?php echo $image->getImageSn() ?>"><img class="trigger" src="/images/upload/thumbs/<?php echo $image->getImageSn() ?>"></a>
					</div>
					<div id="dpop" class="popup">
						<div id="cap_top"></div>
						<div id="cap_body">
							<div>
								<p><span class="ptitle">图片描述:</span><?php echo $image->getDescription() ?></p>
								<p><span class="ptitle">上传时间:</span> <?php echo $image->getCTime()?></p>
							</div>
						</div>
						<div id="cap_bottom"></div>
					</div>
				</div>
			<?php endforeach ?>
			</div>
			<div id="msgBox"></div>
			</div><!-- end of overall content -->
		</div><!-- end of p_content -->
	</div><!-- end of page stage -->
	</div><!-- end of contentWrapper -->
