<?php
	$this->headTitle(' - '.$this->modCName.' - '.$this->sidName);
	$this->headScript()->prependFile('/js/pment.js');
	$this->headScript()->prependFile('/js/conPrg.js');
?>
	<div id="contentWrapper">
	<div id="p_breadcrumb"></div>
	<div id="p_stage_sidebar">
	<?php
		echo $this->placeholder('sidebar');
		$arrayFuncs = $this->arrayFuncs;
	?>
		<div id="p_content">
		<p id="expand" class="hide"><?php echo $this->expand ?></p>
		<h1><?php echo $this->modCName.' - '.$this->sidName.' - '.$this->actCName?></h1>
		<?php 
			$project = $this->project;
			echo $this->displayProject($project);?>
		<div class="p_msg">
			<h3></h3>
			<p class="errorMsg"><?php
				if($this->errorMsg != null)
				{
					echo $this->errorMsg;
			 		}?>
			 		</p>
			<?php if (count($this->messages)) : ?>
				<ul id="messages">
				<?php foreach ($this->messages as $message) : ?>
					<li><p class="errorMsg"><?php echo $this->escape($message); ?></p></li>
			<?php endforeach; ?>
				</ul>
			<?php endif; ?>
			</div>
			<div class="overall_tool">
				<div class="button_group">
					<div id="searchBox">
						<form method="post" action="<?php echo $this->url()?>">
							<div>
								<select name="condition" class="tbMediumer stStyle stSearch">
									<option value="task">任务名称</option>
									<option value="date">任务日期</option>
								</select>
							</div>
							<div><input class="tbMedium tbText tbSearch" name="key" type="text" /></div>
							<div><input class= "btSearch" type="submit" value=""></input></div>
						</form>
					</div>
					<?php if($arrayFuncs['add'] == 1):?>
					<div><a href="<?php echo $this->url(array('controller'=>'monprg','action'=>'add'))?>"><img src="/images/icons/functions/new.png"/><p>新建</p></a></div>
					<?php endif;?>
					<?php if($arrayFuncs['ajaxdelete'] == 1):?>
					<div><a href="#msgBox" class="lightbox" id="btDel"><img src="/images/icons/functions/delete.png"/><p>删除</p></a></div>
					<?php endif;?>
					<div><a href="<?php echo $this->url(); ?>"><img src="/images/icons/functions/refresh.png"/><p>显示全部</p></a></div>
					<?php if($arrayFuncs['ajaxpdf'] == 1):?>
					<div><a href="#"><img src="/images/icons/functions/export.png"/><p>导出</p></a></div>
					<?php endif;?>
				</div><!-- end of button group -->
			</div><!-- end of overall tool -->
			<div class="overall_content">
			<p class="subMenu">工程月进度任务</p>
				<table>
					<colgroup>
						<col style="width:5%"></col>
						<col style="width:35%"></col>
						<col style="width:15%"></col>
						<col style="width:15%"></col>
						<col style="width:10%"></col>
						<col style="width:10%"></col>
						<?php if($arrayFuncs['edit'] == 1):?>
						<col style="width:5%"></col>
						<col style="width:5%"></col>
						<?php else:?>
						<col style="width:10%"></col>
						<?php endif;?>
					</colgroup>
					<thead>
						<th></th>
						<th>总进度任务名称</th>
						<th>开始日期</th>
						<th>结束日期</th>
						<th>工期(天)</th>
						<th>编制人</th>
						<?php if($arrayFuncs['edit'] == 1):?>
						<th></th>
						<?php endif;?>
						<th></th>
					</thead>
					<tr>
						<td><input type="checkbox" id="cb_sa"></td>

						<td colspan="2">全选/取消</td>
						<td></td>
						<td></td>
						<td></td>
						<?php if($arrayFuncs['edit'] == 1):?>
						<td></td>
						<?php endif;?>
						<td></td>
					</tr>
				</table>
					<?php $arrayYm = $this->arrayYm;?>
					<?php if ($arrayYm != null) : ?>
					<?php krsort($arrayYm)?>
					<?php foreach($arrayYm as $key => $value):?>
					<?php krsort($value);?>
					<?php foreach($value as $key2 => $value2):?>
					<div>
					<p class="subMenu slideMenu"><a class="btMonAll subMenu_switch_close"><?php echo $key.'年'.$key2.'月'?></a></p>
					<div class="conMonAll">
						<table>
								<colgroup>
								<col style="width:5%"></col>
								<col style="width:35%"></col>
								<col style="width:15%"></col>
								<col style="width:15%"></col>
								<col style="width:10%"></col>
								<col style="width:10%"></col>
								<?php if($arrayFuncs['edit'] == 1):?>
								<col style="width:5%"></col>
								<col style="width:5%"></col>
								<?php else:?>
								<col style="width:10%"></col>
								<?php endif;?>
							</colgroup>
							<?php foreach($value2 as $key3 => $value3):?>
							<tr>
								<?php $monprgId = $value3->getMonprgId()?>
								<td><input type="checkbox" name="cb" value="<?php echo $monprgId ?>"></td>
								<td><a href="<?php echo $this->url(array('controller'=>'monprg','action'=>'display','id'=>$monprgId))?>"><?php echo $value3->getSubTask()?></a></td>
								<td><?php echo $value3->getStartDate()?></td>
								<td><?php echo $value3->getEndDate()?></td>
								<td><?php echo $value3->getPeriod()?></td>
								<td><a class="lightbox" href="/employee/index/ajaxdisplay/id/<?php echo $this->escape($value3->getContactId()) ?>"><?php echo $this->escape($value3->getContactName())?></a></td>
								<?php if($arrayFuncs['edit'] == 1):?>
								<td><a href="<?php echo $this->url(array('controller'=>'monprg','action'=>'edit','id'=>$monprgId))?>">修改</a></td>
								<?php endif;?>
								<td><a href="<?php echo $this->url(array('controller'=>'monprg','action'=>'display','id'=>$monprgId))?>">详情</a></td>
							</tr>
					<?php endforeach ?>
						</table>
					</div>
					</div>
					<?php endforeach ?>
					<?php endforeach ?>
					<?php endif; ?>
				<div id="msgBox"></div>
			</div><!-- end of overall content -->
		</div><!-- end of p_content -->
	</div><!-- end of page stage -->
	</div><!-- end of contentWrapper -->
