	<div id="contentWrapper">
	<div id="p_breadcrumb"></div>
	<div id="p_stage_sidebar">
		<div id="p_sidebar" class="p_sidebar_general">
		<?php echo $this->checkContact() ?>
		<?php echo $this->showQuicklink()?>
		<?php echo $this->showCalendar() ?>
		</div>
		<div id="p_content">
		<h1>首页</h1>
		<div class="p_msg">
			<h3>欢迎登录工程管理系统 Demo <?php echo $this->module?></h3>
			<p class="errorMsg"><?php
				if($this->errorMsg != null)
				{
					echo $this->errorMsg;
					}?>
			</p>
			<?php if (count($this->messages)) : ?>
			<ul id="messages">
			<?php foreach ($this->messages as $message) : ?>
				<li><p class="errorMsg"><?php echo $this->escape($message); ?></p></li>
			<?php endforeach; ?>
			</ul>
		<?php endif; ?>
		</div>
		<div class="overall_content">
			<div class="overall_content_half floatl">
				<p class="subMenu">新闻,通知</p>
				<table>
					<colgroup>
						<col style="width:5%"></col>
						<col style="width:55%"></col>
						<col style="width:15%"></col>
						<col style="width:15%"></col>
						<col style="width:10%"></col>
					</colgroup>
					<thead>
						<th>#</th>
						<th>标题</th>
						<th>发布人</th>
						<th>发布时间</th>
						<th></th>
					</thead>
					<?php if($this->arrayPresses != null):?>
					<?php $counter = 1;?>
					<?php foreach($this->arrayPresses as $press):?>
					<?php $prId = $this->escape($press->getPrId());?>
					<tr>
						<td><?php 
							echo $counter;
							$counter++;
						?></td>
						<td><?php echo $this->escape($press->getTitle())?></td>
						<td><a class="lightbox" href="/employee/index/ajaxdisplay/id/<?php echo $this->escape($press->getContactId()) ?>"><?php echo $this->escape($press->getContactName()) ?></a></td>
						<td><?php echo $this->escape($press->getPDate())?></td>
						<td><a href="">阅读</a></td>
					</tr>
					<?php endforeach ?>
					<?php else:?>
					<tr>
						<td></td>
						<td colspan="3">暂无新闻,通知</td>
						<td></td>
					</tr>
					<? endif;?>
				</table>
			</div>
			<div class="overall_content_half floatr">
				<p class="subMenu">未读站内信息</p>
				<table>
					<colgroup>
						<col style="width:5%"></col>
						<col style="width:15%"></col>
						<col style="width:45%"></col>
						<col style="width:20%"></col>
						<col style="width:15%"></col>
					</colgroup>
					<thead>
						<th>#</th>
						<th>发件人</th>
						<th>名称</th>
						<th>收件时间</th>
						<th></th>
					</thead>
					<?php if($this->arrayMessages != null):?>
					<?php $counter = 1;?>
					<?php foreach($this->arrayMessages as $message):?>
					<?php $msgId = $this->escape($message->getMsgId());
							$counter++; ?>
					<tr>
						<td><img src="/images/mail/0.png"></td>
						<td><a class="lightbox" href="/employee/index/ajaxdisplay/id/<?php echo $this->escape($message->getFromCId())?>"><?php echo $this->escape($message->getFromCName())?></a></td>
						<td><?php echo $this->escape($message->getTitle()) ?></td>
						<td><?php echo $this->escape($message->getSendTime()) ?></td>
						<td><a href="/admin/message/display/id/<?php echo $message->getMsgId()?>">阅读</a></td>
					</tr>
					<?php endforeach ?>
					<?php else:?>
					<tr>
						<td></td>
						<td colspan="3">暂无未读站内信息</td>
						<td></td>
					</tr>
					<? endif;?>
				</table>
			</div>
		</div>
		<div class="overall_content">
			<div class="overall_content_half floatl">
				<p class="subMenu">待核验材料计划</p>
				<table>
					<colgroup>
						<col style="width:30%"></col>
						<col style="width:20%"></col>
						<col style="width:15%"></col>
						<col style="width:15%"></col>
						<col style="width:10%"></col>
						<col style="width:10%"></col>
					</colgroup>
					<thead>
						<th>材料计划名称</th>
						<th>材料计划类型</th>
						<th>材料计划时间</th>
						<th>填报人</th>
						<th>填报日期</th>
						<th></th>
					</thead>
					<?php $counter = 1;?>
					<?php foreach($this->arrayValidations as $plan):?>
					<?php $planId = $this->escape($plan->planId);?>
					<tr>
						<td><?php echo $this->escape($plan->planName)?></td>
						<td><?php echo $this->escape($plan->typeName)?></td>
						<td><?php echo $this->escape($plan->yearNum)."年".$this->escape($plan->monNum)."月"?></td>
						<td><a class="lightbox" href="/employee/index/ajaxdisplay/id/<?php echo $this->escape($plan->contactId)?>"><?php echo $this->escape($plan->contactName) ?></a></td>
						<td><?php echo $this->escape($plan->pDate)?></td>
						<td><a href="/pment/mplan/validation/planId/<?php echo $planId ?>">进入核验</a></td>
					</tr>
					<?php endforeach ?>
				</table>
			</div>
				<div class="overall_content_half floatr">
				<p class="subMenu">项目总览</p>
				<table>
					<colgroup>
						<col style="width:10%"></col>
						<col style="width:15%"></col>
						<col style="width:45%"></col>
						<col style="width:15%"></col>
						<col style="width:15%"></col>
					</colgroup>
					<thead>
						<th>#</th>
						<th></th>
						<th>项目名</th>
						<th>结构类型</th>
						<th>项目经理</th>
					</thead>
					<?php $counter = 1;?>
					<?php foreach($this->arrayProjects as $project):?>
					<?php $projectId = $this->escape($project->projectId) ?>
					<tr>
						<td><?php 
							echo $counter;
							$counter++;
						?></td>
						<td><a href="/pment/index/index/id/<?php echo $projectId ?>">进入工程管理</a></td>
						<td><a class="lightbox" href="/project/index/ajaxdisplay/id/<?php echo $projectId ?>"><?php echo $this->escape($project->name) ?></a></td>
						<td><?php echo $this->escape($project->structype) ?></td>
						<td><a class="lightbox" href="/employee/index/ajaxdisplay/id/<?php echo $this->escape($project->contactId)?>"><?php echo $this->escape($project->contactName)?></a></td>
					</tr>
					<?php endforeach ?>
				</table>
			</div>
				<div class="overall_content_half floatl">
				<p class="subMenu">车辆总览</p>
				<table>
					<colgroup>
						<col style="width:10%"></col>
						<col style="width:30%"></col>
						<col style="width:25%"></col>
						<col style="width:25%"></col>
						<col style="width:10%"></col>
					</colgroup>
					<thead>
						<th>#</th>
						<th>车牌号</th>
						<th>行驶证号</th>
						<th>车辆负责人</th>
						<th></th>
					</thead>
					<?php $counter = 1;?>
					<?php foreach($this->arrayVehicles as $vehicle):?>
					<?php $veId = $this->escape($vehicle->veId);?>
					<tr>
						<td><?php 
							echo $counter;
							$counter++;
						?></td>
						<td><a class="lightbox" href="/vehicle/index/ajaxdisplay/id/<?php echo $veId ?>"><?php echo $this->escape($vehicle->plateNo) ?></a></td>
						<td>
						<?php echo $this->escape($vehicle->license)?>
						</td>
						<td><a class="lightbox" href="/employee/index/ajaxdisplay/id/<?php echo $this->escape($vehicle->contactId) ?>"><?php echo $this->escape($vehicle->cName) ?></a></td>
						<td><a href="/vehicle/index/display/id/<?php echo $veId ?>">详情</a></td>
					</tr>
					<?php endforeach ?>
				</table>
			</div>
		</div><!-- end of overall content -->
		</div>
	<div id="msgBox"></div>
	</div><!-- end of page stage -->
	</div><!-- end of contentWrapper -->
