<?php $this->placeholder('sidebar')->captureStart()?>
<div id="p_sidebar" class="p_sidebar_general"> 
	<ul>
		<li><a href="/equipment">机械设备信息</a></li>
		<li><a href="/equipment/plan">机械设备需求计划</a></li>
		<li><a href="/equipment/purchase">机械设备采购单</a></li>
		<li><a href="/equipment/rent">机械设备租赁单</a></li>
		<li><a href="/equipment/transfer">机械设备调拨单</a></li>

	</ul>
</div>
<?php $this->placeholder('sidebar')->captureEnd()?>