 <?php 
 	$this->headTitle('- 工人管理 - 班组信息');
 	$this->headScript()->prependFile('/js/worker/p_team.js');
 ?>
	<div id="contentWrapper">
	<div id="p_breadcrumb"></div>
	<div id="p_stage_sidebar">	
	<?php 
		echo $this->placeholder('sidebar');
	?>
		<div id="p_content">
		<h1>工人管理 - 班组信息 - 总览</h1>
		<div class="p_msg">
			<h3>本页显示内容为班组信息总览</h3>
			<p class="errorMsg"><?php
				if($this->errorMsg != null)
				{
					if($this->errorMsg == 2)
					{
						echo '错误: 没有找到符合条件的结果。'; 
						}
						elseif($this->errorMsg == 1)
						{
							echo '错误: 请输入搜索关键字。';
							}
			 		}?>
			 		</p>
			</div>
			<div class="overall_tool">
				<div class="button_group">
				<div id="searchBox">
					<form method="post" action="<?php echo $this->url()?>">
							<div>
								<select name="condition" class="tbMediumer stStyle">
  									<option value="name">班组名称</option>
									<option value="contactName">负责人</option>
								</select>
							</div>
							<div><input class="tbMedium tbText" name="key" type="text" /></div>
							<div><input class= "btSearch" type="submit" value=""></input></div>	
						</form>
				</div>		
					<div><a href="<?php echo $this->url(array('controller'=>'index','action'=>'add'))?>"><img src="/images/icons/functions/new.png"/><p>新建</p></a></div>
					<div><a href="#msgBox" class="lightbox" id="btDel"><img src="/images/icons/functions/delete.png"/><p>删除</p></a></div>
					<div><a href="<?php echo $this->url(); ?>"><img src="/images/icons/functions/refresh.png"/><p>显示全部</p></a></div>
					<div><a href="#"><img src="/images/icons/functions/print.png"/><p>打印</p></a></div>	
					<div><a href="#"><img src="/images/icons/functions/help.png"/><p>帮助</p></a></div>	
				</div><!-- end of button group -->
			</div><!-- end of overall tool -->
			<div class="overall_content">
				<table>
					<colgroup>
						<col style="width:5%"></col>
						<col style="width:5%"></col>
						<col style="width:20%"></col>
						<col style="width:20%"></col>
						<col style="width:20%"></col>
						<col style="width:20%"></col>
						<col style="width:5%"></col>
						<col style="width:5%"></col>						
					</colgroup>
					<thead>
						<th>#</th>
						<th></th>
						<th>班组名称</th>
						<th>负责人</th>
						<th>联系电话</th>
						<th>工人数量</th>
						<th></th>
						<th></th>
					</thead>
					<tr>
						<td><input type="checkbox" id="cb_sa"></td>
						<td colspan="2">全选/取消</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>	
					<?php $counter = 1;?>
					<?php foreach($this->arrayTeams as $team):?>
					<?php $teamId = $this->escape($team->getTeamId());?>
					<tr>
						<td><input type="checkbox" name="cb" value="<?php echo $teamId ?>"></td>
						<td><?php 
							echo $counter;
							$counter++;
						?></td>
						<td><a class="lightbox" href="<?php echo $this->url(array('controller'=>'index','action'=>'ajaxdisplay','id'=>$teamId))?>"><?php echo $this->escape($team->getName()) ?></a></td>
						<td><a class="lightbox" href="/employee/index/ajaxdisplay/id/<?php echo $this->escape($team->getContactId()) ?>"><?php echo $this->escape($team->getContactName()) ?></td>	
						<td><?php echo $this->escape($team->getContactPhoneNo()) ?></td>
						<td>
						<?php echo $this->escape($team->getSum())?>
						</td>
						<td><a href="<?php echo $this->url(array('controller'=>'index','action'=>'edit','id'=>$teamId))?>">修改</a></td>
						<td><a class="lightbox" href="<?php echo $this->url(array('controller'=>'index','action'=>'ajaxdisplay','id'=>$teamId))?>">详情</a></td>
					</tr>
					<?php endforeach ?>
				</table>
				<div id="msgBox"></div>
			</div><!-- end of overall content -->
		</div><!-- end of p_content -->
	</div><!-- end of page stage -->
	</div><!-- end of contentWrapper -->
