 <?php 
 	$this->headTitle('- 工程管理 - 工程日志信息');
 	$this->headScript()->prependFile('/js/logjs/p_log.js');
 ?>
	<div id="contentWrapper">
	<div id="p_breadcrumb"></div>
	<div id="p_stage_sidebar">	
	<?php 
		echo $this->placeholder('sidebar');
	?>
		<div id="p_content">
		<h1>工程管理 - 工程日志信息 - 详情</h1>
		<div class="p_msg">
			<h3></h3>
		</div>
			<div class="overall_tool">
			<?php $log = $this->plog?>
				<div class="button_group">
					<div><a href="<?php echo $this->url(array('controller'=>'log','action'=>'edit','id'=>$log->getPLogId()))?>"><img src="/images/icons/functions/modify.png"/><p>修改</p></a></div>
					<div><a href="#"/><img src="/images/icons/functions/export.png"/><p>导出</p></a></div>
					<div><a href="#"><img src="/images/icons/functions/print.png"/><p>打印</p></a></div>	
					<div><a href="/project/index/display/id/<?php echo $log->getProjectId() ?>"><img src="/images/icons/functions/back.png"/><p>返回</p></a></div>	
				</div><!-- end of button group -->
			</div><!-- end of overall tool -->
			<div class="overall_content">
				<p class="subMenu">工程日志信息</p>
				<table>
					<colgroup>
						<col style="width:30%"></col>
						<col style="width:70%"></col>					
					</colgroup>
					<tr>
					<tr>
						<td>日期: </td>
						<td><?php echo $log->getLogDate()?></td>
					</tr>
					<tr>
						<td>天气: </td>
						<td><?php echo $log->getWeather()?></td>
					</tr>
					<tr>
						<td>最高温度: </td>
						<td><?php echo $log->getTempHi()?></td>
					</tr>
					<tr>
						<td>最低温度: </td>
						<td><?php echo $log->getTempLo()?></td>
					</tr>					
					<tr>
						<td>生产进度情况: </td>
						<td><?php echo $log->getProgress()?></td>
					</tr>					
					<tr>
						<td>质量问题: </td>
						<td><?php echo $log->getQualityPbl()?></td>
					</tr>					
					<tr>
						<td>安全问题: </td>
						<td><?php echo $log->getSafetyPbl()?></td>
					</tr>					
					<tr>
						<td>其他问题: </td>
						<td><?php echo $log->getOtherPbl()?></td>
					</tr>					
					<tr>
						<td>来往文件: </td>
						<td><?php echo $log->getRelatedFile()?></td>
					</tr>
					<tr>
						<td>会议记录: </td>
						<td><?php echo $log->getMMinutes()?></td>
					</tr>
					<tr>
						<td>变更签证: </td>
						<td><?php echo $log->getChangeSig()?></td>
					</tr>
					<tr>
						<td>材料设备使用情况: </td>
						<td><?php echo $log->getMaterial()?></td>
					</tr>
					<tr>
						<td>施工机具使用情况: </td>
						<td><?php echo $log->getMachine()?></td>
					</tr>
					<tr>
						<td>水电气情况: </td>
						<td><?php echo $log->getUtility()?></td>
					</tr>
					<tr>
						<td>备注: </td>
						<td><?php echo $log->getRemark()?></td>
					</tr>
					<tr>
						<td>创建时间: </td>
						<td><?php echo $log->getCTime()?></td>
					</tr>
				</table>
				<div id="msgBox"></div>
				</div><!-- end of overall content -->
			</div><!-- end of p_content -->
		</div><!-- end of page stage -->
	</div><!-- end of contentWrapper -->
