<?php
	$this->headTitle('- 工程管理 - 工程总进度计划');
	$this->headScript()->prependFile('/js/pment.js');
	$this->headScript()->prependFile('/js/conPrg.js');
?>
	<div id="contentWrapper">
	<div id="p_breadcrumb"></div>
	<div id="p_stage_sidebar">
	<?php
		echo $this->placeholder('sidebar');
	?>
		<div id="p_content">
		<h1>工程管理 - 工程总进度计划 - 总览</h1>
		<?php 
			$project = $this->project;
			echo $this->displayProject($project);?>
		<div class="p_msg">
			<h3></h3>
			<p class="errorMsg"><?php
				if($this->errorMsg != null)
				{
					echo $this->errorMsg;
			 		}?>
			 		</p>
			<?php if (count($this->messages)) : ?>
				<ul id="messages">
				<?php foreach ($this->messages as $message) : ?>
					<li><p class="errorMsg"><?php echo $this->escape($message); ?></p></li>
			<?php endforeach; ?>
				</ul>
			<?php endif; ?>
			</div>
			<div class="overall_tool">
				<div class="button_group">
					<div id="searchBox">
						<form method="post" action="<?php echo $this->url()?>">
							<div>
								<select name="condition" class="tbMediumer stStyle stSearch">
									<option value="task">任务名称</option>
									<option value="date">任务日期</option>
								</select>
							</div>
							<div><input class="tbMedium tbText tbSearch" name="key" type="text" /></div>
							<div><input class= "btSearch" type="submit" value=""></input></div>
						</form>
					</div>
					<div><a href="<?php echo $this->url(array('controller'=>'mstprg','action'=>'add'))?>"><img src="/images/icons/functions/new.png"/><p>新建</p></a></div>
					<div><a href="#msgBox" class="lightbox" id="btDel"><img src="/images/icons/functions/delete.png"/><p>删除</p></a></div>
					<div><a href="<?php echo $this->url(); ?>"><img src="/images/icons/functions/refresh.png"/><p>显示全部</p></a></div>
					<div><a href="#"><img src="/images/icons/functions/export.png"/><p>导出</p></a></div>
					<div><a href="#"><img src="/images/icons/functions/print.png"/><p>打印</p></a></div>
				</div><!-- end of button group -->
			</div><!-- end of overall tool -->
			<div class="overall_content">
			<p class="subMenu">工程总进度任务</p>
				<table>
					<colgroup>
						<col style="width:5%"></col>
						<col style="width:5%"></col>
						<col style="width:35%"></col>
						<col style="width:15%"></col>
						<col style="width:15%"></col>
						<col style="width:5%"></col>
						<col style="width:10%"></col>
						<col style="width:5%"></col>
						<col style="width:5%"></col>
					</colgroup>
					<thead>
						<th><input id="modelName" type="text" class="hide" value="<?php echo $this->modelName ?>"></th>
						<th>阶段号</th>
						<th>总进度任务名称</th>
						<th>开始日期</th>
						<th>结束日期</th>
						<th>工期(天)</th>
						<th>编制人</th>
						<th><input id="module" type="text" class="hide" value="<?php echo $this->module ?>"></th>
						<th><input id="controller" type="text" class="hide" value="<?php echo $this->controller ?>"></th>
					</thead>
					<tr>
						<td><input type="checkbox" id="cb_sa"></td>
						<td colspan="2">全选/取消</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<?php foreach($this->arrayMstprgs as $mstprg):?>
					<?php $mstprgId = $this->escape($mstprg->getMstprgId());?>
					<tr>
						<td><input type="checkbox" name="cb" value="<?php echo $mstprgId ?>"></td>
						<td><?php echo $this->escape($mstprg->getStage())?></td>
						<td><a href="<?php echo $this->url(array('controller'=>'mstprg','action'=>'display','id'=>$mstprgId))?>"><?php echo $this->escape($mstprg->getTask())?></a></td>
						<td><?php echo $this->escape($mstprg->getStartDate()) ?></td>
						<td><?php echo $this->escape($mstprg->getEndDate()) ?></td>
						<td><?php echo $this->escape($mstprg->getPeriod()) ?></td>
						<td><a class="lightbox" href="/employee/index/ajaxdisplay/id/<?php echo $this->escape($mstprg->getContactId()) ?>"><?php echo $this->escape($mstprg->getContactName())?></a></td>
						<td><a href="<?php echo $this->url(array('controller'=>'mstprg','action'=>'edit','id'=>$mstprgId))?>">修改</a></td>
						<td><a href="<?php echo $this->url(array('controller'=>'mstprg','action'=>'display','id'=>$mstprgId))?>">详情</a></td></tr>
					<?php endforeach ?>
					</table>
				<div id="msgBox"></div>
			</div><!-- end of overall content -->
		</div><!-- end of p_content -->
	</div><!-- end of page stage -->
	</div><!-- end of contentWrapper -->
