				<!-- append follow after 	<div class="p_msg"><h3>本页显示内容为材料总览</h3>-->
				<p class="errorMsg"><?php
				if($this->errorMsg != null)
				{
					if($this->errorMsg == 2)
					{
						echo '错误: 没有找到符合条件的结果。'; 
						}
						elseif($this->errorMsg == 1)
						{
							echo '错误: 请输入搜索关键字。';
							}
			 		}?>
			 		</p>
				<!-- append following after <div class="button_group"> -->
				<div id="searchBox">
					<form method="post" action="<?php echo $this->url()?>">
							<div>
								<select name="condition" class="tbMediumer stStyle">
  									<option value="projectName">工程名称</option>
									<option value="structype">结构类型</option>
  									<option value="contactName">负责人</option>
								</select>
							</div>
							<div><input class="tbMedium tbText" name="key" type="text" /></div>
							<div><input class= "btSearch" type="submit" value=""></input></div>	
						</form>
				</div>	