<script src="/js/jquery-1.6.1.min.js" type="text/javascript"></script>
<script src="/js/ajax_pdf.js" type="text/javascript"></script>
<div id="ajaxMsgBox">
	<div id="ajaxMsgBox_Emp">
			 <div class="overall_content">
				<h3>正在跳转到下载页面.......,如果页面无反应,也可以点击此处<a href="<?php echo $this->murl?>">下载</a></h3>
				<span id="murl" style="display:none"><?php echo $this->murl?></span>
			</div>
	</div>
</div>