 <?php 
 	$this->headTitle('- 工程管理 - 月计划材料信息');
 	$this->headScript()->prependFile('/js/pment.js');
 	$this->headScript()->prependFile('/js/conMtr.js'); 
 	$this->headScript()->prependFile('/js/rdSlide.js'); 

?>
	<div id="contentWrapper">
	<div id="p_breadcrumb"></div>
	<div id="p_stage_sidebar">	
	<?php 
		echo $this->placeholder('sidebar');
	?>
		<div id="p_content">
		<h1>工程管理 - 月计划材料信息 - 编辑材料</h1>
		<?php 
			$project = $this->project;
			echo $this->displayProject($project);?>
		<div class="p_msg">
			<h3></h3>
			<p class="errorMsg"><?php
				if($this->errorMsg != null)
				{
					echo $this->errorMsg;
			 	}?>
			</p>
		</div>
			<div class="overall_content">
				<p class="subMenu slideMenu"><a class="btRdSlide subMenu_switch_close">月计划信息</a></p>
				<?php $mplan = $this->mplan?>
				<table>
					<colgroup>
						<col style="width:15%"></col>
						<col style="width:35%"></col>
						<col style="width:15%"></col>
						<col style="width:35%"></col>
					</colgroup>
					<tr>
					<tr>
						<td>计划时间: </td>
						<td><?php echo $mplan->getYearNum()."年".$mplan->getMonNum()."月"?></td>
						<td>填报人: </td>
						<td><a class="lightbox" href="/employee/index/ajaxdisplay/id/<?php echo $this->escape($mplan->getContactId())?>"><?php echo $mplan->getContactName()?></a></td>
					</tr>
				</table>
				<div class="conRdSlide hide">
				<table>
					<colgroup>
						<col style="width:15%"></col>
						<col style="width:35%"></col>
						<col style="width:15%"></col>
						<col style="width:35%"></col>
					</colgroup>
					<tr>
						<td>填报时间: </td>
						<td><?php echo $mplan->getPDate()?></td>
						<td>上次修改时间: </td>
						<td><?php echo $mplan->getCTime()?></td>
					</tr>
					<tr>
						<td>备注: </td>
						<td colspan="3"><?php echo $mplan->getRemark()?></td>
					</tr>
				</table>
				</div>
				<p class="subMenu slideMenu"><a class="btRdSlide2 subMenu_switch_open">添加材料</a></p>
				<form action="<?php echo $this->url()?>" method="post">
				<div class="conRdSlide2">
				<table>
					<tr>
						<td><label>类别: </label></td>
						<td><select id="type" name="type" class="tbMedium tbText">
								<option value="钢材">钢材</option>
								<option value="水泥">水泥</option>
								<option value="河沙">河沙</option>
								<option value="石子">石子</option>
							</select></td>
						<td><label>材料名: </label></td>
						<td><input type="text" id="mName" name="mName" class="tbMedium tbText" /></td>
						<td><label>单位: </label></td>
						<td><input type="text" id="unit" name="unit" class="tbMedium tbText" /></td>
					</tr>
					<tr>
						<td><label>规格型号: </label></td>
						<td><input type="text" name="spec" id="spec" class="tbMedium tbText"/></td>
						<td><label>项目部核量: </label></td>
						<td><input type="text" name="amount" id="amount" class="tbMedium tbText"/></td>
						<td><label>重量: </label></td>
						<td><input type="text" name="weight" id="weight" class="tbMedium tbText"/></td>
					</tr>
					<tr>
						<td><label>限额值: </label></td>
						<td><input type="text" name="limitation" id="limitation" class="tbMedium tbText"/></td>
						<td><label>需进场时间: </label></td>
						<td><input type="text" name="inDate" id="inDate" class="tbMedium tbText datepicker"/></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td><label>备注: </label></td>
						<td colspan="5"><textarea id="remark" name="remark" class="tbText" cols="60" rows="4"></textarea></td>
					</tr>
					<tr>
						<td colspan="2"><!-- <p id ="reset" class="btConfirmVar radius floatr">重填</p> --></td>
						<td colspan="2"><input type="submit" id ="submit" value="添加" class="btConfirmVar radius floatl"/></td>
					</tr>		
					</table>
					</div>
					</form>
			</div><!-- end of overall content -->
			<div class="overall_tool">
				<div class="button_group">
					<div><a href="#msgBox" class="lightbox" id="btDel"><img src="/images/icons/functions/delete.png"/><p>删除</p></a></div>
					<div><a href="/pment/mplan/edit/id/<?php echo $this->planId?>"><img src="/images/icons/functions/pre.png"/><p>上页</p></a></div>	
					<div><a href="/pment/mplan/"><img src="/images/icons/functions/back.png"/><p>返回</p></a></div>	
				</div><!-- end of button group -->
			</div><!-- end of overall tool -->
			<div class="overall_content">
					<p class="subMenu slideMenu"><a class="btRdSlide3 subMenu_switch_open">计划相关材料信息</a></p>
					<div class="conRdSlide3">
					<table>
					<colgroup>
						<col style="width:5%"></col>
						<col style="width:5%"></col>
						<col style="width:5%"></col>
						<col style="width:20%"></col>
						<col style="width:5%"></col>
						<col style="width:15%"></col>
						<col style="width:5%"></col>
						<col style="width:5%"></col>
						<col style="width:10%"></col>
						<col style="width:5%"></col>
						<col style="width:20%"></col>
					</colgroup>
					<thead>
						<th>#</th>
						<th></th>
						<th>材料类别</th>
						<th>材料名</th>
						<th>单位</th>
						<th>规格型号</th>
						<th>项目部审核量</th>
						<th>重量</th>
						<th>限额值</th>
						<th>需进场时间</th>
						<th>备注</th>
					</thead>
					<tr>
						<td><input type="checkbox" id="cb_sa"></td>
						<td colspan="2">全选/取消</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<?php $counter = 1;?>
					<?php foreach($this->arrayMaterials as $material):?>
					<?php $mtrId = $this->escape($material->getMtrId());?>
					<tr>
						<td><input type="checkbox" name="cb" value="<?php echo $mtrId ?>"></td>
						<td><?php
							echo $counter;
							$counter++;
						?></td>
						<td><?php echo $this->escape($material->getType()) ?></td>
						<td><?php echo $this->escape($material->getMName()) ?></td>
						<td><?php echo $this->escape($material->getUnit())?></td>
						<td><?php echo $this->escape($material->getSpec())?></td>
						<td><?php echo $this->escape($material->getAmount())?></td>
						<td><?php echo $this->escape($material->getWeight())?></td>
						<td><?php echo $this->escape($material->getLimitation())?></td>
						<td><?php echo $this->escape($material->getInDate())?></td>
						<td><?php echo $this->escape($material->getRemark())?></td>
					</tr>
					<?php endforeach ?>
				</table>
				</div>
				<div id="msgBox"></div>
				<p id="ajax_id" class="hide"><?php echo $this->planId ?></p>
				<input id="modelName" type="text" class="hide" value="<?php echo $this->modelName ?>">
				<input id="module" type="text" class="hide" value="<?php echo $this->module ?>">
				<input id="controller" type="text" class="hide" value="<?php echo $this->controller ?>">
			</div><!-- end of overall content -->
		</div><!-- end of p_content -->
	</div><!-- end of page stage -->
	</div><!-- end of contentWrapper -->
