<?php $this->placeholder('sidebar')->captureStart()?>
<div id="p_sidebar" class="p_sidebar_general"> 
	<ul>
		<li><a href="/material">材料信息</a></li>
		<li><a href="/material/plan">材料需求计划</a></li>
		<li><a href="/material/price">材料比价单</a></li>
		<li><a href="/material/purchase">材料采购</a></li>
		<li><a href="/material/export">材料出库</a></li>
		<li><a href="/material/transfer">材料调拨</a></li>
	</ul>
</div>
<?php $this->placeholder('sidebar')->captureEnd()?>