 <?php 
 	$this->headTitle('-材料信息');
 	$this->headScript()->prependFile('/js/materialjs/p_material.js');
 ?>
 	<div id="p_id" class="hide">nav_generalInfo</div>
	<div id="s_id" class="hide">none</div>
	<div id="contentWrapper">
	<div id="p_breadcrumb"></div>
	<div id="p_stage_sidebar">	
	<?php 
		echo $this->placeholder('sidebar');
	?>
		<div id="p_content">
		<h1>材料管理 - 材料信息 - 新建</h1>
		<div class="p_msg">
			<h3>本页显示内容为材料信息新建</h3>
			<p>"我在测试id-------"<?php echo $this->result; ?></p>
		</div>
			<div class="overall_tool">
				<div class="button_group">
					<div><a href="/employee/index/add"><img src="/images/icons/functions/refresh.png"/><p>清空</p></a></div>	
					<div><a href="#"><img src="/images/icons/functions/print.png"/><p>打印</p></a></div>	
					<div><a href="/employee"><img src="/images/icons/functions/back.png"/><p>返回</p></a></div>	
				</div><!-- end of button group -->
			</div><!-- end of overall tool -->
			<div class="overall_content">
					<?php
						$this->addForm->setAction($this->url());
						echo $this->addForm;
					?>
			</div><!-- end of overall content -->
		</div><!-- end of p_content -->
	</div><!-- end of page stage -->
	</div><!-- end of contentWrapper -->
