<div id="ajaxMsgBox">
	<div id="ajaxMsgBox_Emp">
	<div class="overall_tool">
				<div class="button_group">
					<div><a href="#"><img src="/images/icons/functions/export.png"/><p>导出</p></a></div>	
					<div><a href="#"><img src="/images/icons/functions/print.png"/><p>打印</p></a></div>	
				</div><!-- end of button group -->
	</div><!-- end of overall tool -->
			<p><?php
			$material = $this->material;?>
			 </p>
			 <div class="overall_content">
			 <table>
					<colgroup>
						<col style="width:30%"></col>
						<col style="width:70%"></col>						
					</colgroup>
					<tr>
						<td>材料名称: </td>
						<td><?php echo $material->getName()?></td>
					</tr>	
					<tr>
						<td>类型: </td>
						<td><?php echo $material->getTypeName()?></td>
					</tr>	
					<tr>
						<td>规格型号: </td>
						<td><?php echo $material->getSpec()?></td>
					</tr>	
					<tr>
						<td>单位: </td>
						<td><?php echo $material->getUnit()?></td>
					</tr>	
					<tr>
						<td>备注: </td>
						<td><?php echo $material->getRemark()?></td>
					</tr>	
					<tr>
						<td>上次修改时间: </td>
						<td><?php echo $material->getCTime()?></td>
					</tr>		
			</table>
		</div>
	</div>
</div>