 <?php 
 	$this->headTitle('- 材料管理 - 材料信息');
 	$this->headScript()->prependFile('/js/materialjs/p_material.js');
 ?>
 	<div id="p_id" class="hide">nav_generalInfo</div>
	<div id="s_id" class="hide">none</div>
	<div id="contentWrapper">
	<div id="p_breadcrumb"></div>
	<div id="p_stage_sidebar">	
	<?php 
		echo $this->placeholder('sidebar');
	?>
		<div id="p_content">
		<h1>材料管理 - 材料信息 - 总览</h1>
		<div class="p_msg">
			<h3></h3>
			<p class="errorMsg"><?php
				if($this->errorMsg != null)
				{
					echo $this->errorMsg;
			 		}?>
			 		</p>
		</div>
			<div class="overall_tool">
				<div class="button_group">
					<div id="searchBox">
					<form method="post" action="<?php echo $this->url()?>">
							<div>
								<select name="condition" class="tbMediumer stStyle">
  									<option value="name">材料名</option>
									<option value="type">类型</option>
  									<option value="spec">规格</option>
								</select>
							</div>
							<div><input class="tbMedium tbText" name="key" type="text" /></div>
							<div><input class= "btSearch" type="submit" value=""></input></div>	
						</form>
					</div>	
					<div><a href="<?php echo $this->url(array('controller'=>'index','action'=>'add'))?>"><img src="/images/icons/functions/new.png"/><p>新建</p></a></div>
					<div><a href="#msgBox" class="lightbox" id="btDel"><img src="/images/icons/functions/delete.png"/><p>删除</p></a></div>
					<div><a href="<?php echo $this->url(); ?>"><img src="/images/icons/functions/refresh.png"/><p>显示全部</p></a></div>
					<div><a href="#"><img src="/images/icons/functions/print.png"/><p>打印</p></a></div>	
					<div><a href="#"><img src="/images/icons/functions/export.png"/><p>导出</p></a></div>	
				</div><!-- end of button group -->
			</div><!-- end of overall tool -->
			<div class="overall_content">
				<table>
					<colgroup>
						<col style="width:5%"></col>
						<col style="width:5%"></col>
						<col style="width:15%"></col>
						<col style="width:15%"></col>
						<col style="width:15%"></col>
						<col style="width:15%"></col>
						<col style="width:20%"></col>
						<col style="width:10%"></col>
					</colgroup>
					<thead>
						<th>#</th>
						<th></th>
						<th>材料名</th>
						<th>类型</th>
						<th>规格型号</th>
						<th>单位</th>
						<th>备注</th>
						<th></th>
					</thead>
					<tr>
						<td><input type="checkbox" id="cb_sa"></td>
						<td colspan="2">全选/取消</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<?php $counter = 1;?>	
					<?php foreach($this->arrayMaterials as $material):?>
					<?php $mtrId = $this->escape($material->getMtrId()); ?>
					<tr>
						<td><input type="checkbox" name="cb" value="<?php echo $mtrId; ?>"></td>
						<td><?php 
							echo $counter;
							$counter++;
						?></td>
						<td><?php echo $this->escape($material->getName()); ?></td>
						<td><?php echo $this->escape($material->getTypeName())?></td>	
						<td><?php
							echo $material->getSpec();
						?>
						</td>
						<td><?php echo $this->escape($material->getUnit()) ?></td>
						<td><?php echo $this->escape($material->getRemark()) ?></td>
						<td><a href="<?php echo $this->url(array('controller'=>'index','action'=>'edit','id'=>$mtrId))?>">修改</a></td>
					</tr>
					<?php endforeach ?>
				</table>
				<div id="msgBox"></div>
			</div><!-- end of overall content -->
		</div><!-- end of p_content -->
	</div><!-- end of page stage -->
	</div><!-- end of contentWrapper -->
