 <?php 
 	$this->headTitle('-材料管理');
 	$this->headScript()->prependFile('/js/materialjs/p_material.js');
 ?>
 	<div id="p_id" class="hide">nav_generalInfo</div>
	<div id="s_id" class="hide">none</div>
	<div id="contentWrapper">
	<div id="p_breadcrumb"></div>
	<div id="p_stage_sidebar">	
	<?php 
		echo $this->placeholder('sidebar');
	?>
		<div id="p_content">
		<h1>材料管理 - 材料管理 - 总览</h1>
		<div class="p_msg">
			<h3>本页显示内容为通材料总览</h3>
		</div>
			<div class="overall_tool">
				<div class="button_group">
					<form method="post" action="<?php echo $this->url(array('controller'=>'index','action'=>'search'))?>" class="searchForm">
						<div><input class="tbMedium tbtext" type="text" /></div>
						<div><a href="#"><img src="/images/icons/functions/search.png"/><p>查询</p></a></div>	
					</form>
					<div><a href="<?php echo $this->url(array('controller'=>'index','action'=>'add'))?>"><img src="/images/icons/functions/new.png"/><p>新建</p></a></div>
					<div><a href="#msgBox" class="lightbox" id="btDel"><img src="/images/icons/functions/delete.png"/><p>删除</p></a></div>
					<div><a href="<?php echo $this->url(); ?>"><img src="/images/icons/functions/refresh.png"/><p>显示全部</p></a></div>
					<div><a href="#"><img src="/images/icons/functions/print.png"/><p>打印</p></a></div>	
					<div><a href="<?php echo $this->url(array('controller'=>'index','action'=>'ajaxwarning'))?>" class="lightbox"><img src="/images/icons/functions/pdf.png"/><p>导出</p></a></div>	
				</div><!-- end of button group -->
			</div><!-- end of overall tool -->
			<div class="overall_content">
				<table>
					<colgroup>
						<col style="width:4%"></col>
						<col style="width:4%"></col>
						<col style="width:10%"></col>
						<col style="width:5%"></col>
						<col style="width:10%"></col>
						<col style="width:15%"></col>
						<col style="width:20%"></col>
						<col style="width:20%"></col>
						<col style="width:5%"></col>
						<col style="width:7%"></col>
					</colgroup>
					<thead>
						<th>#</th>
						<th></th>
						<th>姓名</th>
						<th>性别</th>
						<th>年龄</th>
						<th>职称</th>
						<th>电话</th>
						<th>其他联系方式</th>
						<th></th>
						<th></th>
					</thead>
					<tr>
						<td><input type="checkbox" id="cb_sa"></td>
						<td colspan="2">全选/取消</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<?php $counter = 1;?>	
					<?php foreach($this->arrayContacts as $contact):?>
					<?php $contactId = $this->escape($contact->getContactId()); ?>
					<tr>
						<td><input type="checkbox" name="cb" value="<?php echo $contactId; ?>"></td>
						<td><?php 
							echo $counter;
							$counter++;
						?></td>
						<td><a href="<?php echo $this->url(array('controller'=>'index','action'=>'ajaxdisplay','id'=>$contactId))?>" class="lightbox"><?php echo $this->escape($contact->getName()); ?></a></td>
						<td><?php 
							$gender = $this->escape($contact->getGender());
							echo $gender?"男":"女";
						?></td>	
						<td><?php
							echo $contact->getAge();
						?>
						</td>
						<td><?php echo $this->escape($contact->getTitleName()) ?></td>
						<td><?php echo $this->escape($contact->getPhoneNo()) ?></td>
						<td><?php echo $this->escape($contact->getOtherContact()) ?></td>
						<td><a class="lightbox" href="<?php echo $this->url(array('controller'=>'index','action'=>'ajaxdisplay','id'=>$contactId))?>">详情</a></td>
						<td><a href="<?php echo $this->url(array('controller'=>'index','action'=>'edit','id'=>$contactId))?>">修改</a></td>
					</tr>
					<?php endforeach ?>
				</table>
				<div id="msgBox"></div>
			</div><!-- end of overall content -->
		</div><!-- end of p_content -->
	</div><!-- end of page stage -->
	</div><!-- end of contentWrapper -->
