<?php $this->placeholder('sidebar')->captureStart()?>
<div id="p_sidebar" class="p_sidebar_general"> 
	<ul>
		<li><a id="team" href="/worker">班组信息</a></li>
		<li><a id="worker" href="/worker/worker">工人信息</a></li>
		<li><a id="wage" href="/worker/wage">日工工资信息</a></li>
		<li><a id="regular" href="/worker/regular">计划派工单信息</a></li>
		<li><a id="extra" href="/worker/extra">额外派工单信息</a></li>
		<li><a id="bonuse" href="/worker/bonuse">工人奖励信息</a></li>
		<li><a id="penalty" href="/worker/penalty">工人扣款信息</a></li>
	</ul>
</div>
<?php $this->placeholder('sidebar')->captureEnd()?>