<?php $this->placeholder('sidebar')->captureStart()?>
<div id="p_sidebar" class="p_sidebar_general"> 
	<ul>
		<li><a href="/worker">班组信息</a></li>
		<li><a href="/worker/worker">工人信息</a></li>
		<li><a href="/worker/wage">日工工资信息</a></li>
		<li><a href="/worker/regular">计划派工信息</a></li>
		<li><a href="/worker/extra">额外派工信息</a></li>
		<li><a href="/worker/bonus">工人奖励</a></li>
		<li><a href="/worker/penalty">工人扣款</a></li>
	</ul>
</div>
<?php $this->placeholder('sidebar')->captureEnd()?>