 <?php
 	$this->headTitle('- 工人管理 - 计划派工信息');
 	$this->headScript()->prependFile('/js/workerjs/p_regular.js');
 ?>

	<div id="contentWrapper">
	<div id="p_breadcrumb"></div>
	<div id="p_stage_sidebar">
	<?php
		echo $this->placeholder('sidebar');
	?>
		<div id="p_content">
		<h1>工人管理 - 计划派工信息 - 总览</h1>
		<div class="p_msg">
			<h3></h3>
			<p class="errorMsg">
			<?php
				if($this->errorMsg != null)
					echo $this->errorMsg;?></p>
			</div>
			<div class="overall_tool">
				<div class="button_group">
				<div id="searchBox">
					<form method="post" action="<?php echo $this->url()?>">
							<div>
								<select name="condition" class="tbMediumer stStyle stSearch">
  									<option value="projectName">工程名称</option>
  									<option value="date">日期</option>
								</select>
							</div>
							<div><input class="tbMedium tbText tbSearch" name="key" type="text" /></div>
							<div><input class= "btSearch" type="submit" value=""></input></div>
						</form>
				</div>
					<div><a href="<?php echo $this->url(array('controller'=>'regular','action'=>'add'))?>"><img src="/images/icons/functions/new.png"/><p>新建</p></a></div>
					<div><a href="#msgBox" class="lightbox" id="btDel"><img src="/images/icons/functions/delete.png"/><p>删除</p></a></div>
					<div><a href="<?php echo $this->url(); ?>"><img src="/images/icons/functions/refresh.png"/><p>显示全部</p></a></div>
					<div><a href="#"><img src="/images/icons/functions/export.png"/><p>导出</p></a></div>
					<div><a href="#"><img src="/images/icons/functions/print.png"/><p>打印</p></a></div>
				</div><!-- end of button group -->
			</div><!-- end of overall tool -->
			<div class="overall_content">
				<table>
					<colgroup>
						<col style="width:5%"></col>
						<col style="width:5%"></col>
						<col style="width:1３%"></col>
						<col style="width:1３%"></col>
						<col style="width:1３%"></col>
						<col style="width:1３%"></col>
						<col style="width:1４%"></col>
						<col style="width:1４%"></col>
						<col style="width:5%"></col>
						<col style="width:5%"></col>
					</colgroup>
					<thead>
						<th>#</th>
						<th><input id="modelName" type="text" class="hide" value="<?php echo $this->modelName ?>"></th><!--检查处-->
						<th>工程名称</th><!--修改处-->
						<th>派工人数</th>
						<th>开始日期</th>
						<th>结束日期</th>
						<th>预算费用</th>
						<th>实际派工费用</th>
						<th><input id="module" type="text" class="hide" value="<?php echo $this->module ?>"></th><!--检查处-->
						<th><input id="controller" type="text" class="hide" value="<?php echo $this->controller ?>"></th><!--检查处-->
					</thead>
					<tr>
						<td><input type="checkbox" id="cb_sa"></td>
						<td colspan="2">全选/取消</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<?php $counter = 1;?>
					<?php foreach($this->arrayRegulars as $regular):?>
					<?php $regId = $this->escape($regular->getRegId());?>
					<tr>
						<td><input type="checkbox" name="cb" value="<?php echo $regId ?>"></td>
						<td><?php
							echo $counter;
							$counter++;
						?></td>
						<td><?php echo $this->escape($regular->getProjectName()) ?></a></td>
						<td><?php echo $this->escape($regular->getNumber()) ?></a></td>
						<td><?php echo $this->escape($regular->getStartDate()) ?></td>
						<td><?php echo $this->escape($regular->getEndDate()) ?></td>
						<td><?php echo $this->escape($regular->getBudget()) ?></td>
						<td><?php echo $this->escape($regular->getCost()) ?></td>
						<td><a href="<?php echo $this->url(array('controller'=>'regular','action'=>'edit','id'=>$regId))?>">修改</a></td>
						<td><a class="lightbox" href="<?php echo $this->url(array('controller'=>'regular','action'=>'ajaxdisplay','id'=>$regId))?>">详情</a></td>
					</tr>
					<?php endforeach ?>
				</table>
				<div id="msgBox"></div>
			</div><!-- end of overall content -->
		</div><!-- end of p_content -->
	</div><!-- end of page stage -->
	</div><!-- end of contentWrapper -->