<div id="ajaxMsgBox">
<div id="ajaxMsgBox_Emp">
	<div class="overall_tool">
		<div class="button_group">
			<div><a href="#"><img src="/images/icons/functions/print.png"/><p>打印</p></a></div>
			<div><a href="#"><img src="/images/icons/functions/export.png"/><p>导出</p></a></div>
			</div><!-- end of button group -->
	</div><!-- end of overall tool -->
	<?php $vehicle = $this->vehicle;?>
	<div class="overall_content">
		<table>
			<colgroup>
				<col style="width:30%"></col>
				<col style="width:70%"></col>
			</colgroup>
			<tr>
				<td>车牌号：</td>
				<td><?php echo $vehicle->getPlateNo()?></td>
			</tr>
			<tr>
				<td>车辆名称：</td>
				<td><?php echo $vehicle->getName() ?></td>
			</tr>
			<tr>
				<td>车辆颜色： </td>
				<td><?php echo $vehicle->getColor()?></td>
			</tr>
			<tr>
				<td>行驶证号：</td>
				<td><?php echo $vehicle->getLicense()?></td>
			</tr>
			<tr>
				<td>车辆负责人：</td>
				<td><?php echo $vehicle->getContactName()?></td>
			</tr>
			<tr>
				<td>司机：</td>
				<td><?php echo $vehicle->getPilotName()?></td>
			</tr>
			<tr>
				<td>主要使用人员: </td>
				<td><?php echo $vehicle->getUser()?></td>
			</tr>
			<tr>
				<td>标准油耗：</td>
				<td><?php echo $vehicle->getFuelCons()?></td>
			</tr>
			<tr>
				<td>购买时间：</td>
				<td><?php echo $vehicle->getPDate()?></td>
			</tr>
			<tr>
				<td>购买品牌：</td>
				<td><?php echo $vehicle->getBrand()?></td>
			</tr>
			<tr>
				<td>购买金额：</td>
				<td><?php echo $vehicle->getPrice()?></td>
			</tr>
			<tr>
				<td>备注：</td>
				<td><?php echo $vehicle->getRemark()?></td>
			</tr>
			<tr>
				<td>上次修改时间：</td>
				<td><?php echo $vehicle->getCTime()?></td>
			</tr>
		</table>
	</div>
</div>
</div>