 <?php 
 	$this->headTitle('- 工程管理 - 材料月计划信息');
 	$this->headScript()->prependFile('/js/pment.js');
 	$this->headScript()->prependFile('/js/conMtr.js'); 
 	$this->headScript()->prependFile('/js/rdSlide.js');
 	$this->headScript()->prependFile('/js/approvc.js');
 ?>
	<div id="contentWrapper">
	<div id="p_breadcrumb"></div>
	<div id="p_stage_sidebar">	
	<?php 
		echo $this->placeholder('sidebar');
	?>
		<div id="p_content">
		<h1>工程管理 - 材料月计划信息 - 预算部审批</h1>
		<?php 
			$project = $this->project;
			echo $this->displayProject($project);?>
		<div class="p_msg">
			<h3></h3>
			<p class="errorMsg"><?php
				if($this->errorMsg != null)
				{
					echo $this->errorMsg;
					}?>
			</p>
		</div>
			<div class="overall_tool">
				<div class="button_group">
					<div><a href="/pment/mplan/display/id/<?php echo $this->id?>"><img src="/images/icons/functions/back.png"/><p>返回</p></a></div>
				</div><!-- end of button group -->
			</div><!-- end of overall tool -->
			<div class="overall_content">
				<p class="subMenu slideMenu"><a class="btRdSlide subMenu_switch_open">月计划信息</a></p>
				<?php $mplan = $this->mplan;
				$status = $this->status;
				?>
				<table>
					<colgroup>
						<col style="width:15%"></col>
						<col style="width:35%"></col>
						<col style="width:15%"></col>
						<col style="width:35%"></col>
					</colgroup>
					<tr>
						<td>计划状态</td>
						<td><img src="/images/status/<?php echo $status ?>.png">&nbsp;&nbsp;&nbsp;&nbsp;<?php 
							$dis = null;
							if($status == 0)
							{
								$dis = "项目部填报";
								}
								elseif($status == 1)
								{
									$dis = "预算部审批完成";
									}
									elseif($status == 2)
									{
										$dis = "最终审批完成";
										}
							echo $dis;
						?></td>
						<td>计划时间: </td>
						<td><?php echo $mplan->getYearNum()."年".$mplan->getMonNum()."月"?></td>
					</tr>
					<tr>
						<td>填报人: </td>
						<td><a class="lightbox" href="/employee/index/ajaxdisplay/id/<?php echo $this->escape($mplan->getContactId())?>"><?php echo $mplan->getContactName()?></a></td>
						<td>填报时间: </td>
						<td><?php echo $mplan->getPDate()?></td>
					</tr>
				</table>
				<div class="conRdSlide">
				<table>
					<colgroup>
						<col style="width:15%"></col>
						<col style="width:35%"></col>
						<col style="width:15%"></col>
						<col style="width:35%"></col>
					</colgroup>
					<tr>
						<td>备注: </td>
						<td colspan="3"><?php echo $mplan->getRemark()?></td>
					</tr>
				</table>
				</div>
				<p class="subMenu slideMenu"><a class="btRdSlide3 subMenu_switch_open">计划相关材料信息</a></p>
					<div class="conRdSlide3">
					<table>
					<colgroup>
						<col style="width:15%"></col>
						<col style="width:10%"></col>
						<col style="width:5%"></col>
						<col style="width:5%"></col>
						<col style="width:7%"></col>
						<col style="width:7%"></col>
						<col style="width:7%"></col>
						<col style="width:7%"></col>
						<col style="width:7%"></col>
						<col style="width:5%"></col>
						<col style="width:5%"></col>
						<col style="width:5%"></col>
						<col style="width:10%"></col>
					</colgroup>
					<thead>
						<th>材料名</th>
						<th>规格型号</th>
						<th>限额值</th>
						<th>项目部审核量</th>
						<th>预算部审核量</th>
						<th>成本单价</th>
						<th>成本合价</th>
						<th>预算单价</th>
						<th>预算合价</th>
						<th>重量</th>
						<th>单位</th>
						<th>需进场时间</th>
						<th>备注</th>
					</thead>
				</table>
				<?php $arrayMaterials = $this->arrayMaterials;?>
				<?php if ($arrayMaterials != null) : ?>
				<?php foreach($arrayMaterials as $key => $value):?>
				<div>
				<p class="subMenu"><?php echo $key ?></p>
				<form method="post" action="<?php echo $this->url ?>">
				<table>
					<colgroup>
						<col style="width:15%"></col>
						<col style="width:10%"></col>
						<col style="width:5%"></col>
						<col style="width:5%"></col>
						<col style="width:7%"></col>
						<col style="width:7%"></col>
						<col style="width:7%"></col>
						<col style="width:7%"></col>
						<col style="width:7%"></col>
						<col style="width:5%"></col>
						<col style="width:5%"></col>
						<col style="width:5%"></col>
						<col style="width:10%"></col>
					</colgroup>
					<?php foreach($value as $val):?>
					<tr>
						<td><?php echo $this->escape($val->getMName()) ?></td>
						<td><?php echo $this->escape($val->getSpec())?></td>
						<td><?php echo $this->escape($val->getLimitation())?></td>
						<td><?php echo $this->escape($val->getAmount())?></td>
						<td><input name="amountc_<?php echo $val->getMtrId()?>" id="amountc_<?php echo $val->getMtrId()?>" type="text" class="ajax_amountc tbTextS tbMax"/></td>
						<td><input name="cost_<?php echo $val->getMtrId()?>" id="cost_<?php echo $val->getMtrId()?>" type="text" class="ajax_cost tbTextS tbMax"/></td>
						<td><input name="costTotal_<?php echo $val->getMtrId()?>" id="costTotal_<?php echo $val->getMtrId()?>" type="text" class="ajax_costTotal tbTextS tbMax"/></td>
						<td><input name="budget_<?php echo $val->getMtrId()?>" id="budget_<?php echo $val->getMtrId()?>" type="text" class="ajax_budget tbTextS tbMax ajax_budget"/></td>
						<td><input name="budgetTotal_<?php echo $val->getMtrId()?>" id="budgetTotal_<?php echo $val->getMtrId()?>" type="text" class="tbTextS tbMax ajax_budgetTotal"/></td>
						<td><?php echo $this->escape($val->getWeight())?></td>
						<td><?php echo $this->escape($val->getUnit())?></td>
						<td><?php echo $this->escape($val->getInDate())?></td>
						<td><?php echo $this->escape($val->getRemark())?></td>
					</tr>
					<?php endforeach ?>
				</table>
				</div>
				<?php endforeach ?>
				<table>
					<colgroup>
						<col style="width:15%"></col>
						<col style="width:10%"></col>
						<col style="width:5%"></col>
						<col style="width:5%"></col>
						<col style="width:7%"></col>
						<col style="width:7%"></col>
						<col style="width:7%"></col>
						<col style="width:7%"></col>
						<col style="width:7%"></col>
						<col style="width:5%"></col>
						<col style="width:5%"></col>
						<col style="width:5%"></col>
						<col style="width:10%"></col>
					</colgroup>
					<tr>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td>成本总价: </td>
						<td><p id="calCost"></p></td>
						<td>预算总价: </td>
						<td><p id="calBudget"></p></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
				</table>
				<table>
					<colgroup>
						<col style="width:15%"></col>
						<col style="width:30%"></col>
						<col style="width:55%"></col>
					</colgroup>
					<tr>
						<td>预算部审批意见</td>
						<td><textarea name="approvcRemark" id="approvcRemark" class="tbText" cols="60" rows="4"></textarea></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td><input type="submit" value="完成审批" class="btConfirm radius" /></td>
						<td></td>
					</tr>
				</table>
				</form>
				<?php endif; ?>
				<div id="msgBox"></div>
				<p id="ajax_id" class="hide"><?php echo $this->id?></p>
				<input id="modelName" type="text" class="hide" value="<?php echo $this->modelName ?>">
				<input id="module" type="text" class="hide" value="<?php echo $this->module ?>">
				<input id="controller" type="text" class="hide" value="<?php echo $this->controller ?>">
			</div><!-- end of overall content -->
		</div><!-- end of p_content -->
	</div><!-- end of page stage -->
	</div><!-- end of contentWrapper -->