 <?php 
 	$this->headTitle('- 工程管理 - 材料计划信息');
 	$this->headScript()->prependFile('/js/pment.js');
 	$this->headScript()->prependFile('/js/conMtr.js');
 ?>
	<div id="contentWrapper">
	<div id="p_breadcrumb"></div>
	<div id="p_stage_sidebar">	
	<?php 
		echo $this->placeholder('sidebar');
	?>
		<div id="p_content">
		<h1>工程管理 - 材料计划信息 - 总览</h1>
		<?php 
			$project = $this->project;
			echo $this->displayProject($project);?>
		<div class="p_msg">
			<h3></h3>
			<p class="errorMsg"><?php
				if($this->errorMsg != null)
				{
					echo $this->errorMsg;
			 		}?>
			 		</p>
			<?php if (count($this->messages)) : ?>
				<ul id="messages">
				<?php foreach ($this->messages as $message) : ?>
					<li><p class="errorMsg"><?php echo $this->escape($message); ?></p></li>
			<?php endforeach; ?>
				</ul>
			<?php endif; ?>
		</div>
			<div class="overall_tool">
				<div class="button_group">
					<div id="searchBox">
					<form method="post" action="<?php echo $this->url()?>">
							<div>
								<select name="condition" class="tbMediumer stStyle">
  									<option value="contactName">录入人</option>
								</select>
							</div>
							<div><input class="tbMedium tbText" name="key" type="text" /></div>
							<div><input class= "btSearch" type="submit" value=""></input></div>	
						</form>
					</div>	
					<div><a href="<?php echo $this->url(array('controller'=>'mplan','action'=>'add'))?>"><img src="/images/icons/functions/new.png"/><p>新建</p></a></div>
					<div><a href="#msgBox" class="lightbox" id="btDel"><img src="/images/icons/functions/delete.png"/><p>删除</p></a></div>
					<div><a href="<?php echo $this->url(); ?>"><img src="/images/icons/functions/refresh.png"/><p>显示全部</p></a></div>
					<div><a href="#"><img src="/images/icons/functions/export.png"/><p>导出</p></a></div>	
					<div><a href="#"><img src="/images/icons/functions/print.png"/><p>打印</p></a></div>	
				</div><!-- end of button group -->
			</div><!-- end of overall tool -->
			<div class="overall_content">
				<table>
					<colgroup>
						<col style="width:5%"></col>
						<col style="width:5%"></col>
						<col style="width:22%"></col>
						<col style="width:22%"></col>
						<col style="width:22%"></col>
						<col style="width:8%"></col>
						<col style="width:8%"></col>
						<col style="width:8%"></col>
					</colgroup>
					<thead>
						<th>#</th>
						<th>计划状态<input id="modelName" type="text" class="hide" value="<?php echo $this->modelName ?>"></th>
						<th>计划时间</th>
						<th>填报人</th>
						<th>填报日期</th>
						<th></th>
						<th><input id="module" type="text" class="hide" value="<?php echo $this->module ?>"></th>
						<th><input id="controller" type="text" class="hide" value="<?php echo $this->controller ?>"></th>
					</thead>
					<tr>
						<td><input type="checkbox" id="cb_sa"></td>
						<td>全选/取消</td>
						<td colspan="3"><img src="/images/status/0.png"> 工程部填报&nbsp;&nbsp;&nbsp;&nbsp;<img src="/images/status/1.png"> 预算部审批完成&nbsp;&nbsp;&nbsp;&nbsp;<img src="/images/status/2.png"> 最终审批完成</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<?php foreach($this->arrayMplans as $plan):?>
					<?php $planId = $this->escape($plan->getPlanId()); ?>
					<tr>
						<td><input type="checkbox" name="cb" value="<?php echo $planId; ?>"></td>
						<td><img src="/images/status/<?php echo $plan->getStatus()?>.png"/></td>
						<td><?php echo $this->escape($plan->getYearNum())."年".$this->escape($plan->getMonNum())."月"?></td>	
						<td><a class="lightbox" href="/employee/index/ajaxdisplay/id/<?php echo $this->escape($plan->getContactId())?>"><?php echo $this->escape($plan->getContactName()) ?></a></td>
						<td><?php echo $this->escape($plan->getPDate())?></td>
						<td><a href="<?php echo $this->url(array('controller'=>'mplan','action'=>'edit','id'=>$planId))?>">修改计划</a></td>
						<td><a href="/pment/material/index/id/<?php echo $planId ?>">修改材料</a></td>
						<td><a href="<?php echo $this->url(array('controller'=>'mplan','action'=>'display','id'=>$planId))?>">详情</a></td>
					</tr>
					<?php endforeach ?>
				</table>
				<div id="msgBox"></div>
			</div><!-- end of overall content -->
		</div><!-- end of p_content -->
	</div><!-- end of page stage -->
	</div><!-- end of contentWrapper -->
