 <?php 
 	$this->headTitle('- 工程管理 - 材料计划信息');
 	$this->headScript()->prependFile('/js/pment.js');
 	$this->headScript()->prependFile('/js/conMtr.js'); 
 	$this->headScript()->prependFile('/js/rdSlide.js');
 	$this->headScript()->prependFile('/js/mfinal.js');
 ?>
<div id="contentWrapper">
<div id="p_breadcrumb"></div>
<div id="p_stage_sidebar">	
	<?php 
		echo $this->placeholder('sidebar');
	?>
	<div id="p_content">
		<h1>工程管理 - 材料部 - 材料计划信息 - 材料部完善</h1>
		<?php 
			$project = $this->project;
			echo $this->displayProject($project);?>
		<div class="p_msg">
			<h3></h3>
			<p class="errorMsg"><?php
				if($this->errorMsg != null)
				{
					echo $this->errorMsg;
					}?>
			</p>
		</div><!-- end of p_msg -->
			<div class="overall_tool">
				<div class="button_group">
					<div><a id="btAddMtr" class="lightbox" href="#msgBox"><img src="/images/icons/functions/new.png"/><p>新增材料</p></a></div>
					<div><a href="/pment/mplan/mindex"><img src="/images/icons/functions/back.png"/><p>返回</p></a></div>
				</div><!-- end of button group -->
			</div><!-- end of overall tool -->
			<div class="overall_content">
				<p class="subMenu slideMenu"><a class="btAllSlide subMenu_switch_open"><span>关闭</span>全部内容</a></p>
				<div>
				<p class="subMenu slideMenu"><a class="btRdSlide subMenu_switch_open">材料计划信息</a></p>
				<?php $mplan = $this->mplan;?>
				<table>
					<colgroup>
						<col style="width:15%"></col>
						<col style="width:35%"></col>
						<col style="width:15%"></col>
						<col style="width:35%"></col>
					</colgroup>
					<tr>
						<td>材料计划名称: </td>
						<td><?php echo $mplan->getPlanName() ?></td>
						<td>材料计划类型: </td>
						<td><?php echo $mplan->getTypeName()?></td>
					</tr>
					<tr>
						<td>计划状态</td>
						<td><?php echo $mplan->getStatusName()?></td>
						<td>材料计划时间: </td>
						<td><?php echo $mplan->getYearNum()."年".$mplan->getMonNum()."月"?></td>
					</tr>
					<tr>
						<td>填报人: </td>
						<td><a class="lightbox" href="/employee/index/ajaxdisplay/id/<?php echo $this->escape($mplan->getContactId())?>"><?php echo $mplan->getContactName()?></a></td>
						<td>填报时间: </td>
						<td><?php echo $mplan->getPDate()?></td>
					</tr>
				</table>
				<div class="conRdSlide">
				<table>
					<colgroup>
						<col style="width:15%"></col>
						<col style="width:35%"></col>
						<col style="width:15%"></col>
						<col style="width:35%"></col>
					</colgroup>
					<tr>
						<td>备注: </td>
						<td colspan="3"><?php echo $mplan->getRemark()?></td>
					</tr>
					<tr>
						<td>预算部审批人: </td>
						<td><a class="lightbox" href="/employee/index/ajaxdisplay/id/<?php echo $this->escape($mplan->getApprovcId())?>"><?php echo $mplan->getApprovcName()?></a></td>
						<td>预算部审批时间: </td>
						<td><?php echo $mplan->getApprovcDate()?></td>
					</tr>
					<tr>
						<td>预算部审批意见: </td>
						<td colspan="3"><?php echo $mplan->getApprovcRemark()?></td>
					</tr>
					<tr>
						<td>材料部审批人: </td>
						<td><a class="lightbox" href="/employee/index/ajaxdisplay/id/<?php echo $this->escape($mplan->getApprovfId())?>"><?php echo $mplan->getApprovfName()?></a></td>
						<td>材料部审批时间: </td>
						<td><?php echo $mplan->getApprovfDate()?></td>
					</tr>
					<tr>
						<td>材料部审批意见: </td>
						<td colspan="3"><?php echo $mplan->getApprovfRemark()?></td>
					</tr>
				</table>
				</div><!-- end of conRdSlide -->
				</div>
				<form method="post" action="<?php echo $this->url ?>">
				<div>
					<p class="subMenu slideMenu"><a class="btRdSlide subMenu_switch_open">计划相关材料信息</a></p>
					<div class="conRdSlide">
					<table>
						<colgroup>
						<col style="width:15%"></col>
						<col style="width:20%"></col>
						<col style="width:10%"></col>
						<col style="width:10%"></col>
						<col style="width:10%"></col>
						<col style="width:10%"></col>
						<col style="width:25%"></col>
						</colgroup>
						<thead>
							<th>材料名</th>
							<th>规格型号</th>
							<th>预算部核量</th>
							<th>实收数量</th>
							<th>成本价(人民币)</th>
							<th>成本价合价(人民币)</th>
							<th>供应商名称</th>
						</thead>
					</table>
					<?php $arrayMaterials = $this->arrayMaterials;?>
					<?php if ($arrayMaterials != null) : ?>
					<?php foreach($arrayMaterials as $key => $value):?>
					<div>
					<p class="subMenu"><?php echo $key ?></p>
					<table>
						<colgroup>
						<col style="width:15%"></col>
						<col style="width:20%"></col>
						<col style="width:10%"></col>
						<col style="width:10%"></col>
						<col style="width:10%"></col>
						<col style="width:10%"></col>
						<col style="width:25%"></col>
						</colgroup>
						<?php foreach($value as $val):?>
						<tr>
							<td><?php echo $this->escape($val->getMName()) ?></td>
							<td><?php echo $this->escape($val->getSpec())?></td>
							<td><?php echo $val->getAmountc()?></td>
							<td><input name="amountf_<?php echo $val->getMtrId()?>" id="amountf_<?php echo $val->getMtrId()?>" type="text" class="ajax_amountf tbText tbMax" value="<?php echo $this->escape($val->getAmountf())?>"/></td>
							<td><input name="cost_<?php echo $val->getMtrId()?>" id="cost_<?php echo $val->getMtrId()?>" type="text" class="ajax_cost tbText tbMax" value="<?php echo $this->escape($val->getCost())?>"/></td>
							<td><input name="costTotal_<?php echo $val->getMtrId()?>" id="costTotal_<?php echo $val->getMtrId()?>" type="text" class="ajax_costTotal tbText tbMax" value="<?php echo $this->escape($val->getCostTotal())?>"/></td>
							<td><input name="vendorName_<?php echo $val->getMtrId()?>" id="vendorName_<?php echo $val->getMtrId()?>" type="text" class="tbText tbMax" value="<?php echo $this->escape($val->getVendorName())?>"/></td>
						</tr>
						<tr>
							<td colspan="11">
								<p class="hide mc_mtrId"><?php echo $this->escape($val->getMtrId()) ?></p>
								<p class="listMc ajaxButton">+查看材料详情</p>
								<div class="conList hide">
									<table class="conListTable">
										<colgroup>
											<col style="width:15%"></col>
											<col style="width:15%"></col>
											<col style="width:15%"></col>
											<col style="width:10%"></col>
											<col style="width:15%"></col>
											<col style="width:30%"></col>
										</colgroup>
									</table>
								</div>
							</td>
						</tr>
						<?php endforeach ?>
					</table>
					</div><!-- end of sub Menu $key -->
					<?php endforeach ?>
					<?php endif?>
					<p class="subMenu">新增材料</p>
					<table id="conAddMtr">
						<colgroup>
							<col style="width:15%"></col>
							<col style="width:20%"></col>
							<col style="width:10%"></col>
							<col style="width:10%"></col>
							<col style="width:10%"></col>
							<col style="width:10%"></col>
							<col style="width:25%"></col>
						</colgroup>
					</table>
					</div> <!-- end of conRdSlide3 -->
					</div>
					<div>
					<p class="subMenu slideMenu"><a class="btRdSlide subMenu_switch_open">核验人</a></p>
					<div class="conRdSlide">
						<table id="tableAp">
						<colgroup>
							<col style="width:15%"></col>
							<col style="width:20%"></col>
							<col style="width:65%"></col>
						</colgroup>
						<tr>
							<td>核验人</td>
							<td>状态</td>
							<td>核验时间</td>
						</tr>
						<?php $arrayReviewers = $this->arrayReviewers; ?>
						<?php if($arrayReviewers != null ):?>
						<?php foreach($arrayReviewers as $val):?>
						<tr>
							<td><a class="lightbox" href="/employee/index/ajaxdisplay/id/<?php echo $val->getContactId() ?>"><?php echo $val->getContactName()?></a></td>
							<td><?php echo $this->escape($val->getStatusName())?></td>
							<td><?php echo $this->escape($val->getAddDate())?></td>
						</tr>
						<?php endforeach ?>
						<?php endif;?>
						</table>
					</div><!-- end of conRdSlide2 -->
					</div>
					<div>
					<p class="subMenu slideMenu"><a class="btRdSlide subMenu_switch_open">历史修改记录</a></p>
					<div class="conRdSlide">
						<table>
						<colgroup>
							<col style="width:15%"></col>
							<col style="width:15%"></col>
							<col style="width:15%"></col>
							<col style="width:55%"></col>
						</colgroup>
						<?php $arrayBhistories = $this->arrayBhistories; ?>
						<?php if(count($this->arrayBhistories) != 0):?>
						<?php foreach($arrayBhistories as $val):?>
						<tr>
							<td><a class="lightbox" href="/employee/index/ajaxdisplay/id/<?php echo $val->getContactId() ?>"><?php echo $val->getContactName()?></a></td>
							<td><?php echo $val->getEditDate()?></td>
							<td><?php echo $val->getEditType()?></td>
							<td></td>
						</tr>
						<?php endforeach ?>
						<?php else:?>
						<tr>
							<td colspan="4"><span class="highlight">暂无记录</span></td>
						</tr>
						<?php endif;?>
						</table>
					</div><!-- end of conRdSlide4 -->
					</div>
					<table>
					<colgroup>
						<col style="width:10%"></col>
						<col style="width:30%"></col>
						<col style="width:60%"></col>
					</colgroup>
					<tr>
						<td></td>
						<td><input type="submit" value="保存采购信息" name = "btSub" class="btConfirm radius" /></td>
						<td></td>
					</tr>
					</table>
					</form>
				</div><!-- end of overall content -->
				<div id="msgBox">
				<div id="ajax_btAddMtr">
					<div class='overall_tool'>
						<div class='button_group'>
							<div>
								<a id='btClear' class='c_pointer radius'><img src='/images/icons/functions/undo.png'/><p>清空重填</p></a>
							</div>
							<div>
								<a id='btAdd' class='c_pointer radius'><img src='/images/icons/functions/save.png'/><p>确认添加</p></a>
							</div>
						</div>
					</div>
					<div class='overall_content'>
					<table>
						<colgroup>
							<col style="width:20%"></col>
							<col style="width:30%"></col>
							<col style="width:20%"></col>
							<col style="width:30%"></col>
						</colgroup>
					<tr>
						<td><label>类别: </label></td>
						<td><select id="add_type" name="add_type" class="tbMedium tbText">
								<option value="钢材">钢材</option>
								<option value="水泥">水泥</option>
								<option value="河沙">河沙</option>
								<option value="石子">石子</option>
							</select></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td><label>*材料名: </label></td>
						<td colspan="3"><input type="text" id="add_mName" name="add_mName" class="tbLarge tbText" /></td>
					</tr>
					<tr>
						<td><label>*规格型号: </label></td>
						<td colspan="3"><input type="text" name="add_spec" id="add_spec" class="tbLarge tbText"/></td>
					</tr>
					<tr>
						<td><label>项目部报量: </label></td>
						<td><input type="text" name="add_amount" id="add_amount" class="tbMedium tbText" value="0" disabled="disabled"/></td>
						<td><label>单位: </label></td>
						<td><input type="text" id="add_unit" name="add_unit" class="tbMedium tbText" /></td>
					</tr>
					<tr>
						<td><label>*预算部核量: </label></td>
						<td><input type="text" name="add_amountc" id="add_amountc" class="tbMedium tbText"/></td>
						<td><label>*控制价(人民币): </label></td>
						<td><input type="text" name="add_budget" id="add_budget" class="tbMedium tbText"/></td>
					</tr>
					<tr>
						<td><label>*控制价合价(人民币): </label></td>
						<td colspan="3"><input type="text" name="add_budgetTotal" id="add_budgetTotal" class="tbMedium tbText"/></td>
					</tr>
					<tr>
						<td><label>实际收量: </label></td>
						<td><input type="text" name="add_amountf" id="add_amountf" class="tbMedium tbText"/></td>
						<td><label>成本价(人民币): </label></td>
						<td><input type="text" name="add_cost" id="add_cost" class="tbMedium tbText"/></td>
					</tr>
					<tr>
						<td><label>成本价合价(人民币): </label></td>
						<td colspan="3"><input type="text" name="add_cost" id="add_costTotal" class="tbMedium tbText"/></td>
					</tr>
					<tr>
						<td><label>需进场日期: </label></td>
						<td><input type="text" name="add_inDate" id="add_inDate" class="tbMedium tbText datepicker"/></td>
						<td><label>供应商名称: </label></td>
						<td><input type="text" name="add_vendorName" id="add_vendorName" class="tbMedium tbText"/></td>
					</tr>
					<tr>
						<td><label>备注: </label></td>
						<td colspan="3"><textarea id="add_remark" name="add_remark" class="tbText" cols="60" rows="4"></textarea><span id="add_planId" class="hide"><?php echo $mplan->getPlanId() ?></span></td>
					</tr>
					</table>
					</div>
				</div><!-- btAddMtr Wrapper -->
				</div>
				<p id="ajax_id" class="hide"><?php echo $this->id?></p>
				<input id="modelName" type="text" class="hide" value="<?php echo $this->modelName ?>">
				<input id="module" type="text" class="hide" value="<?php echo $this->module ?>">
				<input id="controller" type="text" class="hide" value="<?php echo $this->controller ?>">
	</div><!-- end of p_content -->
</div><!-- end of page stage -->
</div><!-- end of contentWrapper -->
