 <?php 
 	$this->headTitle('- 工程管理 - 材料计划信息');
 	$this->headScript()->prependFile('/js/pment.js');
 	$this->headScript()->prependFile('/js/conMtr.js');
 	$this->headScript()->prependFile('/js/rdSlide.js');
 ?>
	<div id="contentWrapper">
	<div id="p_breadcrumb"></div>
	<div id="p_stage_sidebar">	
	<?php 
		echo $this->placeholder('sidebar');
	?>
		<div id="p_content">
		<h1>工程管理 - 项目部 - 材料计划信息 - 总览</h1>
		<?php 
			$project = $this->project;
			echo $this->displayProject($project);?>
		<div class="p_msg">
			<h3></h3>
			<p class="errorMsg"><?php
				if($this->errorMsg != null)
				{
					echo $this->errorMsg;
			 		}?>
			 		</p>
			<?php if (count($this->messages)) : ?>
				<ul id="messages">
				<?php foreach ($this->messages as $message) : ?>
					<li><p class="errorMsg"><?php echo $this->escape($message); ?></p></li>
			<?php endforeach; ?>
				</ul>
			<?php endif; ?>
		</div>
			<div class="overall_tool">
				<div class="button_group">
					<div><a href="<?php echo $this->url(array('controller'=>'mplan','action'=>'add'))?>"><img src="/images/icons/functions/new.png"/><p>新建</p></a></div>
					<div><a href="#msgBox" class="lightbox" id="btDel"><img src="/images/icons/functions/delete.png"/><p>删除</p></a></div>
					<div><a href="<?php echo $this->url(); ?>"><img src="/images/icons/functions/refresh.png"/><p>显示全部</p></a></div>
					<div><a href="#"><img src="/images/icons/functions/export.png"/><p>导出</p></a></div>	
				</div><!-- end of button group -->
			</div><!-- end of overall tool -->
			<div class="overall_content">
			<p class="subMenu slideMenu"><a class="btAllSlide subMenu_switch_open"><span>关闭</span>全部内容</a></p>
			<div><!-- Content Wrapper -->
			<p class="subMenu slideMenu"><a class="btRdSlide subMenu_switch_open">未提交审批的材料计划</a></p>
			<div class="conRdSlide">
				<table>
					<colgroup>
						<col style="width:5%"></col>
						<col style="width:25%"></col>
						<col style="width:10%"></col>
						<col style="width:10%"></col>
						<col style="width:10%"></col>
						<col style="width:10%"></col>
						<col style="width:10%"></col>
						<col style="width:10%"></col>
						<col style="width:10%"></col>
					</colgroup>
					<thead>
						<th>#</th>
						<th>材料计划名称</th>
						<th>材料计划类型</th>
						<th>计划时间</th>
						<th>填报人</th>
						<th>填报日期</th>
						<th></th>
						<th></th>
						<th></th>
					</thead>
					<tr>
						<td><input type="checkbox" id="cb_sa"></td>
						<td colspan="3">全选/取消</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<?php if(count($this->arrayMplans1) != 0):?>
					<?php foreach($this->arrayMplans1 as $plan):?>
					<?php $planId = $this->escape($plan->planId); ?>
					<tr>
						<td><input type="checkbox" name="cb" value="<?php echo $planId; ?>"></td>
						<td><?php echo $this->escape($plan->planName)?></td>
						<td><?php echo $this->escape($plan->typeName)?></td>
						<td><?php echo $this->escape($plan->yearNum)."年".$this->escape($plan->monNum)."月"?></td>	
						<td><a class="lightbox" href="/employee/index/ajaxdisplay/id/<?php echo $this->escape($plan->contactId)?>"><?php echo $this->escape($plan->contactName) ?></a></td>
						<td><?php echo $this->escape($plan->pDate)?></td>
						<td><a href="<?php echo $this->url(array('controller'=>'mplan','action'=>'edit','id'=>$planId))?>">修改计划</a></td>
						<td><a href="/pment/material/index/id/<?php echo $planId ?>">修改材料</a></td>
						<td><a href="<?php echo $this->url(array('controller'=>'mplan','action'=>'apply','id'=>$planId))?>">提交审批</a></td>
					</tr>
					<?php endforeach ?>
					<?php
						echo "<tr><td colspan='9'>".$this->paginationControl($this->arrayMplans1, 'Sliding', 'tmp/control.phtml')."</td></tr>";?>
					<?php else:?>
					<tr>
						<td colspan="9"><span class="highlight">暂无记录</span></td>
					</tr>
					<?php endif;?>
				</table>
			</div><!-- end of conSlide -->
			</div><!-- End of Content Wrapper -->
			<div><!-- Content Wrapper -->
			<p class="subMenu slideMenu"><a class="btRdSlide subMenu_switch_open">已提交审批的材料计划</a></p>
			<div class="conRdSlide">
				<table>
					<colgroup>
						<col style="width:25%"></col>
						<col style="width:25%"></col>
						<col style="width:10%"></col>
						<col style="width:10%"></col>
						<col style="width:10%"></col>
						<col style="width:10%"></col>
						<col style="width:10%"></col>
					</colgroup>
					<thead>
						<th>材料计划状态</th>
						<th>材料计划名称</th>
						<th>材料计划类型</th>
						<th>计划时间</th>
						<th>填报人</th>
						<th>填报日期</th>
						<th></th>
					</thead>
					<?php if(count($this->arrayMplans2) != 0):?>
					<?php foreach($this->arrayMplans2 as $plan):?>
					<?php $planId = $this->escape($plan->planId); ?>
					<tr>
						<td><img class="m_status" src="/images/status/<?php echo $this->escape($plan->status)?>.png"/><?php echo $this->escape($plan->statusName)?></td>
						<td><?php echo $this->escape($plan->planName)?></td>
						<td><?php echo $this->escape($plan->typeName)?></td>
						<td><?php echo $this->escape($plan->yearNum)."年".$this->escape($plan->monNum)."月"?></td>	
						<td><a class="lightbox" href="/employee/index/ajaxdisplay/id/<?php echo $this->escape($plan->contactId)?>"><?php echo $this->escape($plan->contactName) ?></a></td>
						<td><?php echo $this->escape($plan->pDate)?></td>
						<td><a href="<?php echo $this->url(array('controller'=>'mplan','action'=>'display','id'=>$planId))?>">详情</a></td>
					</tr>
					<?php endforeach ?>
					<?php
						echo "<tr><td colspan='7'>".$this->paginationControl($this->arrayMplans2, 'Sliding', 'tmp/control.phtml')."</td></tr>";?>
					<?php else:?>
					<tr>
						<td colspan="7"><span class="highlight">暂无记录</span></td>
					</tr>
					<?php endif;?>
				</table>
			</div>
			</div><!-- End of Content Wrapper -->
			<div><!-- Content Wrapper -->
			<p class="subMenu slideMenu"><a class="btRdSlide subMenu_switch_open">审批完成的材料计划</a></p>
			<div class="conRdSlide">
				<table>
					<colgroup>
						<col style="width:10%"></col>
						<col style="width:10%"></col>
						<col style="width:10%"></col>
						<col style="width:10%"></col>
						<col style="width:10%"></col>
						<col style="width:10%"></col>
						<col style="width:10%"></col>
						<col style="width:10%"></col>
						<col style="width:10%"></col>
						<col style="width:10%"></col>
					</colgroup>
					<thead>
						<th>材料计划名称</th>
						<th>材料计划类型</th>
						<th>材料计划时间</th>
						<th>填报人</th>
						<th>填报日期</th>
						<th>预算部审批人</th>
						<th>预算部审批时间</th>
						<th>材料部审批人</th>
						<th>材料部审批时间</th>
						<th></th>
					</thead>
					<?php if(count($this->arrayMplans3) != 0):?>
					<?php foreach($this->arrayMplans3 as $plan):?>
					<?php $planId = $this->escape($plan->planId); ?>
					<tr>
						<td><?php echo $this->escape($plan->planName)?></td>
						<td><?php echo $this->escape($plan->typeName)?></td>
						<td><?php echo $this->escape($plan->yearNum)."年".$this->escape($plan->monNum)."月"?></td>	
						<td><a class="lightbox" href="/employee/index/ajaxdisplay/id/<?php echo $this->escape($plan->contactId)?>"><?php echo $this->escape($plan->contactName) ?></a></td>
						<td><?php echo $this->escape($plan->pDate)?></td>
						<td><a class="lightbox" href="/employee/index/ajaxdisplay/id/<?php echo $this->escape($plan->approvcId)?>"><?php echo $this->escape($plan->approvName) ?></a></td>
						<td><?php echo $this->escape($plan->approvcDate)?></td>
						<td><a class="lightbox" href="/employee/index/ajaxdisplay/id/<?php echo $this->escape($plan->approvfId)?>"><?php echo $this->escape($plan->approvfName) ?></a></td>
						<td><?php echo $this->escape($plan->approvfDate)?></td>
						<td><a href="<?php echo $this->url(array('controller'=>'mplan','action'=>'display','id'=>$planId))?>">详情</a></td>
					</tr>
					<?php endforeach ?>
					<?php
						echo "<tr><td colspan='10'>".$this->paginationControl($this->arrayMplans3, 'Sliding', 'tmp/control.phtml')."</td></tr>";?>
					<?php else:?>
					<tr>
						<td colspan="10"><span class="highlight">暂无记录</span></td>
					</tr>
					<?php endif;?>
				</table>
			</div>
			</div><!-- End of Content Wrapper -->
			<div id="msgBox"></div>
			</div><!-- end of overall content -->
		</div><!-- end of p_content -->
	</div><!-- end of page stage -->
	</div><!-- end of contentWrapper -->
