<?php $this->placeholder('sidebar')->captureStart()?>
<div id="p_sidebar" class="p_sidebar_general"> 
	<ul>
		<li><a href="/vehicle">车辆信息</a></li>
		<!-- <li><a href="/system/emsg/construction">车辆保险记录</a></li> -->
		<li><a href="/vehicle/drirecord">车辆行驶记录</a></li>
		<li><a href="/vehicle/repair">车辆维修记录</a></li>
		<li><a href="/vehicle/mtnc">车辆保养记录</a></li>
		<li><a href="/vehicle/verecord">车辆使用记录</a></li>
	</ul>
</div>
<?php $this->placeholder('sidebar')->captureEnd()?>