<?php
	$this->headTitle(' - '.$this->modCName.' - '.$this->sidName);
	$this->headScript()->prependFile('/js/pment.js');
?>
	<div id="contentWrapper">
	<div id="p_breadcrumb"></div>
	<div id="p_stage_sidebar">
	<?php
		echo $this->placeholder('sidebar');
		$arrayFuncs = $this->arrayFuncs;
	?>
		<div id="p_content">
		<h1><?php echo $this->modCName.' - '.$this->sidName.' - '.$this->actCName?></h1>
		<?php 
			$project = $this->project;
			echo $this->displayProject($project);?>
		<div class="p_msg">
			<h3></h3>
			<p class="errorMsg"><?php
				if($this->errorMsg != null)
				{
					echo $this->errorMsg;
			 		}?>
			 		</p>
			<?php if (count($this->messages)) : ?>
				<ul id="messages">
				<?php foreach ($this->messages as $message) : ?>
					<li><p class="errorMsg"><?php echo $this->escape($message); ?></p></li>
			<?php endforeach; ?>
				</ul>
			<?php endif; ?>
			</div>
			<div class="overall_tool">
				<div class="button_group">
					<div id="searchBox">
						<form method="post" action="<?php echo $this->url()?>">
							<div>
								<select name="condition" class="tbMediumer stStyle stSearch">
									<option value="name">用章名称</option>
									<option value="date">使用日期</option>
								</select>
							</div>
							<div><input class="tbMedium tbText tbSearch datepicker" name="key" type="text" /></div>
							<div><input class= "btSearch" type="submit" value=""></input></div>
						</form>
					</div>
					<?php if($arrayFuncs['add'] == 1):?>
					<div><a href="<?php echo $this->url(array('controller'=>'seal','action'=>'add'))?>"><img src="/images/icons/functions/new.png"/><p>新建</p></a></div>
					<?php endif;?>
					<?php if($arrayFuncs['ajaxdelete'] == 1):?>
					<div><a href="#msgBox" class="lightbox" id="btDel"><img src="/images/icons/functions/delete.png"/><p>删除</p></a></div>
					<?php endif;?>
					<div><a href="<?php echo $this->url(); ?>"><img src="/images/icons/functions/refresh.png"/><p>显示全部</p></a></div>
					<?php if($arrayFuncs['ajaxpdf'] == 1):?>
					<div><a href="#"><img src="/images/icons/functions/export.png"/><p>导出</p></a></div>
					<?php endif;?>
				</div><!-- end of button group -->
			</div><!-- end of overall tool -->
			<div class="overall_content">
			<p class="subMenu">印章使用信息</p>
				<table>
					<colgroup>
						<col style="width:5%"></col>
						<col style="width:5%"></col>
						<col style="width:24%"></col>
						<col style="width:23%"></col>
						<col style="width:10%"></col>
						<col style="width:10%"></col>
						<col style="width:5%"></col>
						<col style="width:5%"></col>
						<?php if($arrayFuncs['edit'] == 1):?>
						<col style="width:5%"></col>
						<col style="width:8%"></col>
						<?php else:?>
						<col style="width:13%"></col>
						<?php endif;?>
					</colgroup>
					<thead>
						<th></th>
						<th>#</th>
						<th>用章名称</th>
						<th>用章文件</th>
						<th>经办人</th>
						<th>使用日期</th>
						<th>归还日期</th>
						<th>带出</th>
						<?php if($arrayFuncs['edit'] == 1):?>
						<th></th>
						<?php endif;?>
						<th></th>
					</thead>
					<tr>
						<td><input type="checkbox" id="cb_sa"></td>
						<td colspan="2">全选/取消</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<?php if($arrayFuncs['edit'] == 1):?>
						<td></td>
						<?php endif;?>
						<td></td>
					</tr>
					<?php $counter = 1;?>
					<?php foreach($this->arraySeals as $seal):?>
					<?php $seaId = $this->escape($seal->seaId);?>
					<tr>
						<td><input type="checkbox" name="cb" value="<?php echo $seaId ?>"></td>
						<td><?php
							echo $counter;
							$counter++;
						?></td>
						<td><a class="lightbox" href="<?php echo $this->url(array('controller'=>'seal','action'=>'ajaxdisplay','id'=>$seaId))?>"><?php echo $this->escape($seal->name)?></a></td>
						<td><?php echo $this->escape($seal->sealFile) ?></td>
						<td><a class="lightbox" href="/employee/index/ajaxdisplay/id/<?php echo $this->escape($seal->contactId) ?>"><?php echo $this->escape($seal->contactName)?></a></td>
						<td><?php echo $this->escape($seal->sealDate) ?></td>
						<td><?php echo $this->escape($seal->returnDate) ?></td>
						<td><?php echo $this->escape($seal->takeOut) ?></td>
						<?php if($arrayFuncs['edit'] == 1):?>
						<td><a href="<?php echo $this->url(array('controller'=>'seal','action'=>'edit','id'=>$seaId))?>">修改</a></td>
						<?php endif;?>
						<td><a class="lightbox" href="<?php echo $this->url(array('controller'=>'seal','action'=>'ajaxdisplay','id'=>$seaId))?>">快速查看</a></td></tr>
					<?php endforeach ?>
					<?php if(count($this->arraySeals) != 0)
						echo "<tr><td colspan='10'>".$this->paginationControl($this->arraySeals, 'Sliding', 'tmp/control.phtml')."</td></tr>";?>
					</table>
				<div id="msgBox"></div>
			</div><!-- end of overall content -->
		</div><!-- end of p_content -->
	</div><!-- end of page stage -->
	</div><!-- end of contentWrapper -->
