<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
 	<title>工程管理DEMO</title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="version" content="0.1" />
	<meta name="author" content="Project Luckyrabbit" />
	<meta name="" content="description" />
	<link rel="stylesheet" href="css/nyroModal.css" type="text/css" media="screen" />
	<?php echo $this->headLink()->appendStylesheet('/css/global_style.css') ?>
	<script type="text/javascript" src="/js/jquery-1.5.1.min.js"></script> 
	<script type="text/javascript" src="/js/lightbox/jquery.nyroModal.custom.js"></script>
	<script type="text/javascript" src="/js/global.js"></script>
</head>
<body>
<div id="p_header">
	<a id="p_logo" href="index.php">管理平台首页</a>
	<ul id="panel_uinfo" class="radius">
		<li class="c_user">管理员 您好！</li>
		<li class="c_info"><a href="#">个人设置</a></li>
		<li class="c_info"><a href="#">帮助</a></li>
		<li class="c_info"><a href="login.php">退出</a></li>
	</ul>
	<ul id="nav_main" class="radius nav_general">
		<li><a href="index"><span class="hide">nav_home</span>首页</a></li>
		<li><a href="project">基本信息管理<span class="hide">nav_generalinfo</span></a></li>
		<li><a href="#">工人管理</a></li>
		<li><a href="#">公司员工管理</a></li>
		<li><a href="#">分包管理</a></li>
		<li><a href="#">固定资产管理</a></li>
		<li><a href="#">设备管理</a></li>
		<li><a href="#">材料管理</a></li>
		<li><a href="#">财务管理</a></li>
		<li><a href="#">工程进度管理</a></li>
		<li><a href="#">文件管理</a></li>
		<li><a href="#">工程统计</a></li>
	</ul>
	<ul id="nav_sub" class="radius nav_general">
		<li><a href="#">站内通知</a></li>
		<li><a href="#">系统管理</a></li>
	</ul>
</div>
<?php echo $this->layout()->content ?>
<div id="p_footer">
		<a href="#">隐私策略</a></li>
		<a href="#">服务条款</a></li>
		<a href="#">Alpha Project Team保留所有权</a>
</div>
</body>
</html>