 <?php 
 	$this->headTitle('- 员工及岗位管理 - 项目岗位信息');
 	$this->headScript()->prependFile('/js/employeejs/p_cpp.js');
 ?>
	<div id="contentWrapper">
	<div id="p_breadcrumb"></div>
	<div id="p_stage_sidebar">	
	<?php 
		echo $this->placeholder('sidebar');
	?>
		<div id="p_content">
		<h1>员工及岗位管理 - 项目岗位信息 - 总览</h1>
		<div class="p_msg">
			<h3></h3>
			<p class="errorMsg"><?php
				if($this->errorMsg != null)
				{
					echo $this->errorMsg;
			 		}?>
			 		</p>
			</div>
			<div class="overall_tool">
				<div class="button_group">
				<div id="searchBox">
					<form method="post" action="<?php echo $this->url()?>">
							<div>
								<select name="condition" class="tbMediumer stStyle">
  									<option value="name">姓名</option>
									<option value="projectName">项目名</option>
  									<option value="postName">岗位名</option>
								</select>
							</div>
							<div><input class="tbMedium tbText" name="key" type="text" /></div>
							<div><input class= "btSearch" type="submit" value=""></input></div>	
						</form>
					</div>	
					<div><a href="<?php echo $this->url(array('controller'=>'cpp','action'=>'add'))?>"><img src="/images/icons/functions/new.png"/><p>新建</p></a></div>
					<div><a href="#msgBox" class="lightbox" id="btDel"><img src="/images/icons/functions/delete.png"/><p>删除</p></a></div>
					<div><a href="<?php echo $this->url(); ?>"><img src="/images/icons/functions/refresh.png"/><p>显示全部</p></a></div>
					<div><a href="#"><img src="/images/icons/functions/print.png"/><p>打印</p></a></div>	
					<div><a href="#"><img src="/images/icons/functions/help.png"/><p>帮助</p></a></div>	
				</div><!-- end of button group -->
			</div><!-- end of overall tool -->
			<div class="overall_content">
				<table>
					<colgroup>
						<col style="width:3%"></col>
						<col style="width:2%"></col>
						<col style="width:10%"></col>
						<col style="width:15%"></col>
						<col style="width:10%"></col>
						<col style="width:15%"></col>
						<col style="width:20%"></col>
						<col style="width:20%"></col>
						<col style="width:5%"></col>
					</colgroup>
					<thead>
						<th>#</th>
						<th></th>
						<th>姓名</th>
						<th>项目名</th>
						<th>岗位名</th>
						<th>岗位证类型</th>
						<th>岗位证编号</th>
						<th>安全能力考核证</th>
						<th></th>
					</thead>
					<tr>
						<td><input type="checkbox" id="cb_sa"></td>
						<td colspan="2">全选/取消</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>	
					<?php $counter = 1;?>
					<?php foreach($this->arrayCpps as $cpp):?>
					<tr>
						<td><input type="checkbox" name="cb" value="<?php echo $this->escape($cpp->cppId); ?>"></td>
						<td><?php 
							echo $counter;
							$counter++;
						?></td>
						<td><a href="<?php echo $this->url(array('controller'=>'index','action'=>'ajaxdisplay','id'=>$this->escape($cpp->contactId)))?>" class="lightbox"><?php echo $this->escape($cpp->contactName) ?></a></td>
						<td><?php echo $this->escape($cpp->projectName) ?></td>
						<td><?php echo $this->escape($cpp->postName) ?></td>	
						<td><?php echo $this->escape($cpp->postType) ?></td>
						<td><?php echo $this->escape($cpp->postCardId) ?></td>
						<td><?php echo $this->escape($cpp->certId) ?></td>
						<td><a href="<?php echo $this->url(array('controller'=>'cpp','action'=>'edit','id'=>$this->escape($cpp->cppId)))?>">修改</a></td>
					</tr>
					<?php endforeach ?>
				</table>
				<div id="msgBox"></div>
			</div><!-- end of overall content -->
		</div><!-- end of p_content -->
	</div><!-- end of page stage -->
	</div><!-- end of contentWrapper -->
