<div id="ajaxMsgBox">
	<div id="ajaxMsgBox_Emp">
	<div class="overall_tool">
				<div class="button_group">
					<div><a href="#"><img src="/images/icons/functions/export.png"/><p>导出</p></a></div>	
					<div><a href="#"><img src="/images/icons/functions/print.png"/><p>打印</p></a></div>	
				</div><!-- end of button group -->
	</div><!-- end of overall tool -->
			<p><?php
			$contact = $this->contact;?>
			 </p>
			 <div class="overall_content">
			 <table>
					<colgroup>
						<col style="width:30%"></col>
						<col style="width:70%"></col>						
					</colgroup>
					<tr>
						<td>姓名: </td>
						<td><?php echo $contact->getName()?></td>
					</tr>
					<tr>
						<td>性别: </td>
						<td><?php echo $contact->getGender()?></td>
					</tr>
					<tr>
						<td>年龄: </td>
						<td><?php echo $contact->getAge() ?></td>
					</tr>
					<tr>
						<td>职称专业: </td>
						<td><?php echo $contact->getTitleSpec()?></td>
					</tr>
					<tr>
						<td>职称: </td>
						<td><?php echo $contact->getTitleName()?></td>
					</tr>
					<tr>
						<td>部门: </td>
						<td><?php echo $contact->getDeptName()?></td>
					</tr>
					<tr>
						<td>职务: </td>
						<td><?php echo $contact->getDutyName()?></td>
					</tr>
					<tr>
						<td>手机: </td>
						<td><?php echo $contact->getPhoneMob()?></td>
					</tr>
					<tr>
						<td>上次修改时间: </td>
						<td><?php echo $contact->getCTime()?></td>
					</tr>
			</table>
		</div>
	</div>
</div>