<?php 
	$this->headTitle('- 公司员工管理 - 公司员工信息');
?>
	<div id="contentWrapper">
	<div id="p_breadcrumb"></div>
	<div id="p_stage_sidebar">	
	<?php 
		echo $this->placeholder('sidebar');
	?>
		<div id="p_content">
		<h1>公司员工管理 - 公司员工信息 - 详情</h1>
		<?php 
			$project = $this->project;
			echo $this->displayProject($project);?>
		<div class="p_msg">
			<h3></h3>
		</div>
			<div class="overall_tool">
				<div class="button_group">
					<div><a href="#"/><img src="/images/icons/functions/export.png"/><p>导出</p></a></div>
					<div><a href="#"><img src="/images/icons/functions/print.png"/><p>打印</p></a></div>	
					<div><a href="/pment/mstprg"><img src="/images/icons/functions/back.png"/><p>返回</p></a></div>	
				</div><!-- end of button group -->
			</div><!-- end of overall tool -->
			<div class="overall_content">
				<p class="subMenu slideMenu"><a id="btMst" class="subMenu_switch_open">任务详情</a></p>
				<?php $mstprg = $this->mstprg?>
				<table>
					<colgroup>
						<col style="width:30%"></col>
						<col style="width:70%"></col>
					</colgroup>
					<tr>
						<td>阶段号: </td>
						<td><?php echo $mstprg->getStage()?></td>
					</tr>
					<tr>
						<td>总进度任务名称: </td>
						<td><?php echo $mstprg->getTask()?></td>
					</tr>
				</table>
				<div id="conMst">
				<table>
					<colgroup>
						<col style="width:30%"></col>
						<col style="width:70%"></col>
					</colgroup>
					<tr>
						<td>开始日期: </td>
						<td><?php echo $mstprg->getStartDate()?></td>
					</tr>
					<tr>
						<td>结束日期: </td>
						<td><?php echo $mstprg->getEndDate()?></td>
					</tr>
					<tr>
						<td>工期(天): </td>
						<td><?php echo $mstprg->getPeriod()?></td>
					</tr>
					<tr>
						<td>编制人: </td>
						<td><a class="lightbox" href="/employee/index/ajaxdisplay/id/<?php echo $mstprg->getContactId() ?>"><?php echo $mstprg->getContactName() ?></td>
					</tr>
					<tr>
						<td>备注: </td>
						<td><?php echo $mstprg->getRemark()?></td>
					</tr>
					<tr>
						<td>创建时间: </td>
						<td><?php echo $mstprg->getCTime()?></td>
					</tr>
				</table>
				</div>
			<div id="msgBox"></div>
			</div><!-- end of overall content -->
		</div><!-- end of p_content -->
	</div><!-- end of page stage -->
	</div><!-- end of contentWrapper -->
