 <?php 
 	$this->headTitle('- 员工及岗位管理 - 通讯录信息');
 	$this->headScript()->prependFile('/js/p_employee.js');
 ?>
 	<div id="p_id" class="hide">nav_generalInfo</div>
	<div id="s_id" class="hide">none</div>
	<div id="contentWrapper">
	<div id="p_breadcrumb"></div>
	<div id="p_stage_sidebar">	
	<?php 
		echo $this->placeholder('sidebar');
	?>
		<div id="p_content">
		<h1>员工及岗位管理 - 通讯录信息 - 修改</h1>
		<div class="p_msg">
			<h3>本页显示内容为通讯录信息修改</h3>
		</div>
			<div class="overall_tool">
				<div class="button_group">
					<div><a href="/employee/index/edit/id/<?php echo $this->id; ?>"><img src="/images/icons/functions/refresh.png"/><p>刷新</p></a></div>	
					<div><a href="#"><img src="/images/icons/functions/print.png"/><p>打印</p></a></div>	
					<div><a href="/employee"><img src="/images/icons/functions/back.png"/><p>返回</p></a></div>	
				</div><!-- end of button group -->
			</div><!-- end of overall tool -->
			<div class="overall_content">
					<?php
						$this->editForm->setAction($this->url());
						echo $this->editForm;
					?>
			</div><!-- end of overall content -->
		</div><!-- end of p_content -->
	</div><!-- end of page stage -->
	</div><!-- end of contentWrapper -->
