 <?php 
 	$this->headTitle('- 车辆管理 - 车辆使用记录信息');
 	$this->headScript()->prependFile('/js/vehiclejs/p_verecord.js');
 ?>
	<div id="contentWrapper">
	<div id="p_breadcrumb"></div>
	<div id="p_stage_sidebar">	

		<div id="p_content">
		<div class="p_msg">
			<h3>建设中</h3>
			<p class="errorMsg"><?php
				if($this->errorMsg != null)
				{
					echo $this->errorMsg;
			 		}?>
		</p>
		</div>
			<div class="overall_tool">
				
			<div class="overall_content">
			</div><!-- end of overall content -->
		</div><!-- end of p_content -->
	</div><!-- end of page stage -->
	</div><!-- end of contentWrapper -->
