<?php
	$this->headTitle(' - '.$this->modCName.' - '.$this->sidName);
	$this->headScript()->prependFile('/js/pment.js');
?>
	<div id="contentWrapper">
	<div id="p_breadcrumb"></div>
	<div id="p_stage_sidebar">
	<?php
		echo $this->placeholder('sidebar');
		$arrayFuncs = $this->arrayFuncs;
	?>
		<div id="p_content">
		<h1><?php echo $this->modCName.' - '.$this->sidName.' - '.$this->actCName?></h1>
		<?php 
			$project = $this->project;
			echo $this->displayProject($project);?>
		<div class="p_msg">
			<h3></h3>
			<p class="errorMsg"><?php
				if($this->errorMsg != null)
				{
					echo $this->errorMsg;
			 		}?>
			 		</p>
			<?php if (count($this->messages)) : ?>
				<ul id="messages">
				<?php foreach ($this->messages as $message) : ?>
					<li><p class="errorMsg"><?php echo $this->escape($message); ?></p></li>
			<?php endforeach; ?>
				</ul>
			<?php endif; ?>
			</div>
			<div class="overall_tool">
				<div class="button_group">
					<div id="searchBox">
						<form method="post" action="<?php echo $this->url()?>">
							<div>
								<select name="condition" class="tbMediumer stStyle stSearch">
									<option value="recUnit">备案单位</option>
									<option value="recNumber">备案号</option>
									<option value="date">备案日期</option>
								</select>
							</div>
							<div><input class="tbMedium tbText tbSearch datepicker" name="key" type="text" /></div>
							<div><input class= "btSearch" type="submit" value=""></input></div>
						</form>
					</div>
					<?php if($arrayFuncs['add'] == 1):?>
					<div><a href="<?php echo $this->url(array('controller'=>'record','action'=>'add'))?>"><img src="/images/icons/functions/new.png"/><p>新建</p></a></div>
					<?php endif;?>
					<?php if($arrayFuncs['ajaxdelete'] == 1):?>
					<div><a href="#msgBox" class="lightbox" id="btDel"><img src="/images/icons/functions/delete.png"/><p>删除</p></a></div>
					<?php endif;?>
					<div><a href="<?php echo $this->url(); ?>"><img src="/images/icons/functions/refresh.png"/><p>显示全部</p></a></div>
					<?php if($arrayFuncs['ajaxpdf'] == 1):?>
					<div><a href="#"><img src="/images/icons/functions/export.png"/><p>导出</p></a></div>
					<?php endif;?>
				</div><!-- end of button group -->
			</div><!-- end of overall tool -->
			<div class="overall_content">
			<p class="subMenu">工程备案信息</p>
				<table>
					<colgroup>
						<col style="width:5%"></col>
						<col style="width:5%"></col>
						<col style="width:20%"></col>
						<col style="width:20%"></col>
						<col style="width:20%"></col>
						<col style="width:17%"></col>
						<?php if($arrayFuncs['edit'] == 1):?>
						<col style="width:5%"></col>
						<col style="width:8%"></col>
						<?php else:?>
						<col style="width:13%"></col>
						<?php endif;?>
					</colgroup>
					<thead>
						<th></th>
						<th>#</th>
						<th>备案日期</th>
						<th>备案单位</th>
						<th>备案号</th>
						<th>经办人</th>
						<?php if($arrayFuncs['edit'] == 1):?>
						<th></th>
						<?php endif;?>
						<th></th>
					</thead>
					<tr>
						<td><input type="checkbox" id="cb_sa"></td>
						<td colspan="2">全选/取消</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<?php if($arrayFuncs['edit'] == 1):?>
						<td></td>
						<?php endif;?>
						<td></td>
					</tr>
					<?php $counter = 1;?>
					<?php foreach($this->arrayRecords as $record):?>
					<?php $recId = $this->escape($record->recId);?>
					<tr>
						<td><input type="checkbox" name="cb" value="<?php echo $recId ?>"></td>
						<td><?php
							echo $counter;
							$counter++;
						?></td>
						<td><?php echo $this->escape($record->recDate)?></td>
						<td><?php echo $this->escape($record->recUnit) ?></td>
						<td><?php echo $this->escape($record->recNumber) ?></td>
						<td><a class="lightbox" href="/employee/index/ajaxdisplay/id/<?php echo $this->escape($record->contactId) ?>"><?php echo $this->escape($record->contactName)?></a></td>
						<?php if($arrayFuncs['edit'] == 1):?>
						<td><a href="<?php echo $this->url(array('controller'=>'record','action'=>'edit','id'=>$recId))?>">修改</a></td>
						<?php endif;?>
						<td><a class="lightbox" href="<?php echo $this->url(array('controller'=>'record','action'=>'ajaxdisplay','id'=>$recId))?>">快速查看</a></td></tr>
					<?php endforeach ?>
					<?php if(count($this->arrayRecords) != 0)
						echo "<tr><td colspan='8'>".$this->paginationControl($this->arrayRecords, 'Sliding', 'tmp/control.phtml')."</td></tr>";?>
					</table>
				<div id="msgBox"></div>
			</div><!-- end of overall content -->
		</div><!-- end of p_content -->
	</div><!-- end of page stage -->
	</div><!-- end of contentWrapper -->
