<?php 
	$this->headTitle('- 系统管理 - 用户信息');
?>
	<div id="contentWrapper">
	<div id="p_breadcrumb"></div>
	<div id="p_stage_sidebar">	
	<?php 
		echo $this->placeholder('sidebar');
	?>
		<div id="p_content">
		<h1>系统管理 - 用户信息 - 总览</h1>
		<div class="p_msg">
			<h3></h3>
			<p class="errorMsg"><?php
				if($this->errorMsg != null)
				{
					echo $this->errorMsg;
					}?>
					</p>
			<?php if (count($this->messages)) : ?>
				<ul id="messages">
				<?php foreach ($this->messages as $message) : ?>
				<li><p class="errorMsg"><?php echo $this->escape($message); ?></p></li>
			<?php endforeach; ?>
			</ul>
			<?php endif; ?>
		</div>
			<div class="overall_tool">
				<div class="button_group">
				<div id="searchBox">
					<form method="post" action="<?php echo $this->url()?>">
							<div>
								<select name="condition" class="tbMediumer stStyle">
									<option value="username">用户名</option>
								</select>
							</div>
							<div><input class="tbMedium tbText" name="key" type="text" /></div>
							<div><input class= "btSearch" type="submit" value=""></input></div>	
						</form>
				</div>		
					<div><a href="<?php echo $this->url(array('controller'=>'user','action'=>'add'))?>"><img src="/images/icons/functions/new.png"/><p>新建</p></a></div>
					<div><a href="#msgBox" class="lightbox" id="btDel"><img src="/images/icons/functions/delete.png"/><p>删除</p></a></div>
					<div><a href="<?php echo $this->url(); ?>"><img src="/images/icons/functions/refresh.png"/><p>显示全部</p></a></div>
					<div><a href="#"><img src="/images/icons/functions/export.png"/><p>导出</p></a></div>	
					<div><a href="#"><img src="/images/icons/functions/print.png"/><p>打印</p></a></div>	
				</div><!-- end of button group -->
			</div><!-- end of overall tool -->
			<div class="overall_content">
				<table>
					<colgroup>
						<col style="width:5%"></col>
						<col style="width:5%"></col>
						<col style="width:17%"></col>
						<col style="width:17%"></col>
						<col style="width:17%"></col>
						<col style="width:17%"></col>
						<col style="width:17%"></col>
						<col style="width:5%"></col>
					</colgroup>
					<thead>
						<th>#</th>
						<th></th>
						<th>用户名</th>
						<th>所属用户组</th>
						<th>用户真实姓名</th>
						<th>创建时间</th>
						<th>创建人</th>
						<th></th>
					</thead>
					<tr>
						<td><input type="checkbox" id="cb_sa"></td>
						<td colspan="2">全选/取消</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<?php $counter = 1;?>
					<?php foreach($this->arrayUsers as $user):?>
					<?php $userId = $this->escape($user->id);?>
					<tr>
						<td><input type="checkbox" name="cb" value="<?php echo $userId ?>"></td>
						<td><?php echo $counter;
							$counter++;?></td>
						<td><?php echo $this->escape($user->username) ?></td>
						<td>
						<?php echo $this->escape($user->groupName)?>
						</td>
						<td><a class="lightbox" href="/employee/index/ajaxdisplay/id/<?php echo $this->escape($user->contactId) ?>"><?php echo $this->escape($user->cName) ?></a></td>
						<td><?php echo $this->escape($user->cTime) ?></td>
						<td><a class="lightbox" href="/employee/index/ajaxdisplay/id/<?php echo $this->escape($user->creatorId) ?>"><?php echo $this->escape($user->rName) ?></a></td>
						<td></td>
					</tr>
					<?php endforeach ?>
					<?php if(count($this->arrayUsers) != 0)
						echo "<tr><td colspan='8'>".$this->paginationControl($this->arrayUsers, 'Sliding', 'tmp/control.phtml')."</td></tr>";?>
				</table>
				<div id="msgBox"></div>
			</div><!-- end of overall content -->
		</div><!-- end of p_content -->
	</div><!-- end of page stage -->
	</div><!-- end of contentWrapper -->
