<?php 
	$this->headTitle('- 车辆管理 - 车辆行驶记录');
?>
	<div id="contentWrapper">
	<div id="p_breadcrumb"></div>
	<div id="p_stage_sidebar">	
	<?php 
		echo $this->placeholder('sidebar');
	?>
		<div id="p_content">
		<h1>车辆管理 - 车辆行驶记录 - 总览</h1>
		<div class="p_msg">
			<h3></h3>
			<p class="errorMsg"><?php
				if($this->errorMsg != null)
				{
					echo $this->errorMsg;
					}?>
					</p>
					<?php if (count($this->messages)) : ?>
				<ul id="messages">
				<?php foreach ($this->messages as $message) : ?>
				<li><p class="errorMsg"><?php echo $this->escape($message); ?></p></li>
			<?php endforeach; ?>
			</ul>
			<?php endif; ?>
		</div>
			<div class="overall_tool">
				<div class="button_group">
				<div id="searchBox">
					<form method="post" action="<?php echo $this->url()?>">
							<div>
								<select name="condition" class="tbMediumer stStyle">
									<option value="plateNo">车牌号</option>
								</select>
							</div>
							<div><input class="tbMedium tbText" name="key" type="text" /></div>
							<div><input class= "btSearch" type="submit" value=""></input></div>	
						</form>
				</div>		
					<div><a href="<?php echo $this->url(array('controller'=>'drirecord','action'=>'add'))?>"><img src="/images/icons/functions/new.png"/><p>新建</p></a></div>
					<div><a href="#msgBox" class="lightbox" id="btDel"><img src="/images/icons/functions/delete.png"/><p>删除</p></a></div>
					<div><a href="<?php echo $this->url(); ?>"><img src="/images/icons/functions/refresh.png"/><p>显示全部</p></a></div>
					<div><a href="#"><img src="/images/icons/functions/export.png"/><p>导出</p></a></div>	
					<div><a href="#"><img src="/images/icons/functions/print.png"/><p>打印</p></a></div>	
				</div><!-- end of button group -->
			</div><!-- end of overall tool -->
			<div class="overall_content">
				<table>
					<colgroup>
						<col style="width:5%"></col>
						<col style="width:5%"></col>
						<col style="width:20%"></col>
						<col style="width:18%"></col>
						<col style="width:18%"></col>
						<col style="width:20%"></col>
						<col style="width:5%"></col>
						<col style="width:9%"></col>
					</colgroup>
					<thead>
						<th>#</th>
						<th></th>
						<th>车牌号</th>
						<th>年份</th>
						<th>月份</th>
						<th>当月行驶公里数</th>
						<th></th>
						<th></th>
					</thead>
					<tr>
						<td><input type="checkbox" id="cb_sa"></td>
						<td colspan="2">全选/取消</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>	
					<?php $counter = 1;?>
					<?php foreach($this->arrayDrirecords as $drirecord):?>
					<?php $recordId = $this->escape($drirecord->recordId);?>
					<tr>
						<td><input type="checkbox" name="cb" value="<?php echo $recordId ?>"></td>
						<td><?php 
							echo $counter;
							$counter++;
						?></td>
						<td><a class="lightbox" href="/vehicle/index/ajaxdisplay/id/<?php echo $this->escape($drirecord->veId)?>"><?php echo $this->escape($drirecord->plateNo) ?></a></td>
						<td><?php echo $this->escape($drirecord->rYear) ?></td>	
						<td><?php echo $this->escape($drirecord->rMonth) ?></td>
						<td>
						<?php echo $this->escape($drirecord->mile)?>
						</td>
						<td><a href="<?php echo $this->url(array('controller'=>'drirecord','action'=>'edit','id'=>$recordId))?>">修改</a></td>
						<td><a class="lightbox" href="<?php echo $this->url(array('controller'=>'drirecord','action'=>'ajaxdisplay','id'=>$recordId))?>">快速查看</a></td>
					</tr>
					<?php endforeach ?>
					<?php if(count($this->arrayDrirecords) != 0)
						echo "<tr><td colspan='8'>".$this->paginationControl($this->arrayDrirecords, 'Sliding', 'tmp/control.phtml')."</td></tr>";?>
				</table>
				<div id="msgBox"></div>
			</div><!-- end of overall content -->
		</div><!-- end of p_content -->
	</div><!-- end of page stage -->
	</div><!-- end of contentWrapper -->
